//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTInstrumentsFoundation/DTXAllowedRPC-Protocol.h>

@class NSArray, NSNumber, NSString;

@protocol DTConditionInducerServiceAPI <DTXAllowedRPC>
- (NSNumber *)enableConditionWithIdentifier:(NSString *)arg1 profileIdentifier:(NSString *)arg2;
- (NSNumber *)disableConditionWithIdentifier:(NSString *)arg1;
- (NSNumber *)disableActiveCondition;
- (NSArray *)availableConditionInducers;
@end

