//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DTKPCPU, DTKPCPUCounterAllocatorRecord, NSMutableArray, NSString;

@interface DTKPCPUCounterAllocator : NSObject
{
    struct kpep_config *_kpepConfig;
    NSMutableArray *_eventRecords;
    NSString *_pmiEventOrAliasName;
    unsigned long long _pmiThreshold;
    unsigned long long _fixedCounterCount;
    unsigned long long _configurableCounterCount;
    unsigned long long _eventsUniqueIds;
    DTKPCPU *_cpu;
}

- (void).cxx_destruct;
@property(readonly, retain, nonatomic) DTKPCPU *cpu; // @synthesize cpu=_cpu;
- (int)stopHardwareCounters:(id *)arg1;
- (int)startHardwareCounters:(id *)arg1;
- (int)unforceCounters:(id *)arg1;
- (int)forceCounters:(id *)arg1;
- (int)configurePMIActionID:(unsigned int)arg1 error:(id *)arg2;
- (int)configureHardwarePMIPeriods:(id *)arg1;
- (int)configureHardwareCounters:(id *)arg1;
- (unsigned long long)recordConfigWordsIntoBuffer:(unsigned long long *)arg1;
@property(readonly, nonatomic) unsigned long long pmiThreshold;
@property(readonly, nonatomic) BOOL pmiEnabled;
- (unsigned long long)eventCount;
@property(readonly, nonatomic) unsigned long long pmcEventCount;
- (unsigned int)kpcClasses;
@property(readonly, retain, nonatomic) DTKPCPUCounterAllocatorRecord *allocatedPMIRecord;
- (void)enumerateAllocatedPMCs:(CDUnknownBlockType)arg1;
- (void)_enumerateAllocatedEventsWithIndex:(CDUnknownBlockType)arg1;
- (void)removeAllEvents;
- (int)addPMCEventName:(id)arg1 error:(id *)arg2;
- (int)setPMIEventName:(id)arg1 pmiThreshold:(unsigned long long)arg2 error:(id *)arg3;
- (id)_counterNameForEvent:(id)arg1 error:(id *)arg2;
- (unsigned long long)_counterIndexForEvent:(id)arg1 absolute:(BOOL)arg2 error:(id *)arg3;
- (unsigned int)_counterClassForEvent:(id)arg1 error:(id *)arg2;
- (unsigned long long)_hardwareEventCount;
- (void)dealloc;
- (id)initWithCPU:(id)arg1 error:(id *)arg2;

@end

