//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTInstrumentsFoundation/DTTapLocalDelegate-Protocol.h>

@class DTKPSession, DTKTraceTapConfig, DTTapLocal, NSArray, NSMutableArray, NSString;

@interface DTKTraceTapLocalDelegate : NSObject <DTTapLocalDelegate>
{
    DTTapLocal *_tap;
    DTKTraceTapConfig *_config;
    CDUnknownBlockType _taskForPid;
    BOOL _removeArchivingURLWhenComplete;
    long long _triggerCount;
    unsigned int *_triggerIDs;
    NSMutableArray *_metadataByTriggerIndex;
    DTKPSession *_session;
    BOOL _stopWasCalled;
    NSArray *_localEventProducers;
}

- (void).cxx_destruct;
- (void)fetchDataForReason:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (BOOL)canFetchWhileArchiving;
- (void)unpause;
- (void)pause;
- (void)stop;
- (void)start;
- (void)setTaskForPidBlock:(CDUnknownBlockType)arg1;
- (void)setTap:(id)arg1;
- (id)validateConfig;
- (id)initWithConfig:(id)arg1;
- (id)_getSessionMetadata;
- (unsigned long long)bufferSizeForConfiguration:(id)arg1;
- (unsigned long long)_clampBufferSize:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

