//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DTNetworkInterfaceInfo : NSObject
{
}

+ (id)interfaceNameMappings;
+ (void)addInterface:(struct __SCNetworkInterface *)arg1 toNameMapping:(id)arg2;

@end

