//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DTOSLogStackReferenceWrapper;

__attribute__((visibility("hidden")))
@interface DTOSLogArgumentConstReferences : NSObject
{
    DTOSLogStackReferenceWrapper *etype;
    DTOSLogStackReferenceWrapper *stringVal;
    DTOSLogStackReferenceWrapper *prefix;
    DTOSLogStackReferenceWrapper *name;
    DTOSLogStackReferenceWrapper *tmpArgStruct;
}

- (void).cxx_destruct;

@end

