//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DTTapFactory : NSObject
{
}

+ (id)defaultFactory;
- (id)createNewTapWithConfig:(id)arg1 connection:(id)arg2 options:(id)arg3;

@end

