//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface RemoteBundleLoader : NSObject
{
    unsigned int _targetTask;
    int _targetPid;
    CDUnknownBlockType _releaseOpaqueSymbolicator;
    struct {
        unsigned long long _field1;
        unsigned long long _field2;
        unsigned long long _field3;
        unsigned long long _field4;
        unsigned long long _field5;
        unsigned long long _field6;
        unsigned long long _field7;
        unsigned long long _field8;
        unsigned long long _field9;
        unsigned long long _field10;
        unsigned long long _field11;
        unsigned long long _field12;
        unsigned long long _field13;
        unsigned long long _field14;
        unsigned long long _field15;
        unsigned long long _field16;
        unsigned long long _field17;
    } *_remoteFunctionAddresses;
    NSString *_helperLaunchPath;
    NSObject<OS_dispatch_queue> *_symbolLookupQueue;
    NSObject<OS_dispatch_queue> *_injectionQueue;
    _Bool _attemptedSymbolLookup;
    _Bool _exited;
    _Bool _missingSymbol;
}

- (void).cxx_destruct;
- (void)scheduleLibraryLoad:(id)arg1 calling:(id)arg2 arguments:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)dealloc;
- (id)initWithTask:(unsigned int)arg1;
- (void)_lookupFunctionAddresses:(struct _CSTypeRef)arg1;

@end

