//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBDocumentInspectorViewController.h>

@interface IBCocoaTouchDocumentInspectorViewController : IBDocumentInspectorViewController
{
}

+ (id)documentPlatform;
+ (id)keyPathsForValuesAffectingShouldShowGlobalTintColor;
- (void)didApplyDependencyValue:(id)arg1 toDependency:(id)arg2 forDocument:(id)arg3;
- (id)informativeTextForDisablingConfigurations;
- (id)informativeTextForEnablingConfigurations;
- (id)userLabelForConfigurations;
- (BOOL)shouldShowGlobalTintColor;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

