//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IBCocoaTouchToolFoundation/IBCocoaTouchScreenSizeLayoutConstraintAbstraction.h>

@interface IBCocoaTouchScreenSizeLayoutConstraintAbstraction (IBCocoaTouchLayoutConstraintAbstractionIntegration)
+ (id)ibClassDefaultImage;
- (id)ibDefaultImage;
- (id)ibDefaultLabel;
@end

