//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBCocoaTouchStoryboardAbstractShowSegue.h>

@interface IBCocoaTouchStoryboardShowDetailSegue : IBCocoaTouchStoryboardAbstractShowSegue
{
}

+ (id)classIdentifier;
+ (id)defaultAction;
+ (double)displayOrderPriority;
- (id)effectiveConnectionForDisablingConfigurationsInDocument:(id)arg1 segueReachabilityContext:(id)arg2;
- (id)metricChainSucceedingMetric:(id)arg1;

@end

