//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBDeviceSubtype.h>

@class NSArray, NSDictionary;

@interface IBCocoaTouchDeviceSubtype : IBDeviceSubtype
{
    NSDictionary *_screenMetricsByLayout;
    NSArray *_allScreenMetrics;
}

@property(readonly, nonatomic) NSArray *allScreenMetrics; // @synthesize allScreenMetrics=_allScreenMetrics;
- (void).cxx_destruct;
- (id)idiom;
- (id)defaultScreenMetrics;
- (id)_makeScreenMetricsForAdaptationsWithLayout:(id)arg1;
- (id)screenMetricsForAdaptation:(id)arg1;
- (id)makeScreenMetricsWithIdiom:(id)arg1 displayName:(id)arg2 archiveIdentifier:(id)arg3 landscapeSize:(struct CGSize)arg4 portraitSize:(struct CGSize)arg5 minimumSupportedOSVersion:(id)arg6 legacyIdentifiersForMigration:(id)arg7;
- (id)screenMetricsArchivingIdentifierForLayout:(id)arg1;
- (id)initWithExtension:(id)arg1 idiom:(id)arg2;

@end

