//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBObjectiveCValidator.h>

@interface IBCocoaTouchObjectiveCValidator : IBObjectiveCValidator
{
}

+ (BOOL)isValidActionSelector:(id)arg1 error:(id *)arg2;

@end

