//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBDocumentArchivingSchemaBitmaskComponent.h>

@interface IBDocumentArchivingSchemaBitmaskComponent_IBUIRectEdge : IBDocumentArchivingSchemaBitmaskComponent
{
}

+ (id)sharedInstance;
- (id)schemaIdentifier;
- (id)typeName;
- (id)elementName;

@end

