//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBCocoaTouchOSVersion.h>

@interface IBIOS7XVersion : IBCocoaTouchOSVersion
{
}

- (id)firstInapplicableSystemTarget;
- (id)firstApplicableSystemTarget;
- (id)hybridNIBPackageRuntimeFileName;
- (id)targetRuntimeIdentifierSuffix;
- (id)explicitArchiveIdentifier;
- (id)identifier;

@end

