//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEInterfaceBuilderCocoaTouchIntegration/NSCoding-Protocol.h>
#import <IDEInterfaceBuilderCocoaTouchIntegration/NSCopying-Protocol.h>

@class IBCocoaTouchTargetRuntime;
@protocol IBUIMenuChild;

@interface IBMenuElementInsertion : NSObject <NSCopying, NSCoding>
{
    NSObject<IBUIMenuChild> *_anchor;
    NSObject<IBUIMenuChild> *_child;
    IBCocoaTouchTargetRuntime *_targetRuntime;
}

@property(retain, nonatomic) IBCocoaTouchTargetRuntime *targetRuntime; // @synthesize targetRuntime=_targetRuntime;
@property(nonatomic) __weak NSObject<IBUIMenuChild> *child; // @synthesize child=_child;
@property(nonatomic) __weak NSObject<IBUIMenuChild> *anchor; // @synthesize anchor=_anchor;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTargetRuntime:(id)arg1;

@end

