//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBUITabBarControllerEditor.h>

@class DVTDelayedInvocation, IBMutableIdentityDictionary, IBUITabBarItem;
@protocol DVTCancellable, DVTInvalidation;

@interface IBUIStoryboardTabBarControllerEditor : IBUITabBarControllerEditor
{
    IBUITabBarItem *_draggedTabBarItem;
    IBMutableIdentityDictionary *tabBarItemToSegueMap;
    DVTDelayedInvocation *contentInvocation;
    id <DVTCancellable> _tabBarItemsObservationToken;
    id <DVTInvalidation> _keyFrameObserver;
}

+ (Class)ibDropTargetResolverClass;
- (void).cxx_destruct;
- (void)reattachDraggedObjects:(id)arg1 dragContext:(id)arg2;
- (void)detachDraggedObjects:(id)arg1 dragContext:(id)arg2;
- (id)acceptDragInfo:(id)arg1 context:(id)arg2;
- (unsigned long long)dragOperationForDraggingInfo:(id)arg1 initialOperation:(unsigned long long)arg2;
- (void)customizeDraggingPasteboard:(id)arg1 draggingContext:(id)arg2;
- (id)uniquePasteboardType;
- (BOOL)interceptEvent:(id)arg1;
- (void)noteDescendant:(id)arg1 didChangeProperty:(id)arg2 fromValue:(id)arg3;
- (void)pullOrderOfSeguesFromArrangedTabBarItems:(id)arg1;
- (void)_setSimulatedTabBarItems:(id)arg1;
- (id)effectiveDisplayedTabBarItems;
- (void)synchronizeArrangementView;
- (id)editedTabBarControllerSeguesToRelatedDownstreamControllers;
- (void)_updateDisplaysAllTabsForReordering;
- (void)willClose;
- (void)didOpen;
- (id)initWithEditedObject:(id)arg1 parentEditor:(id)arg2 frameController:(id)arg3;

@end

