//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBUIViewCachedGeometryInfo.h>

@class IBUITableView;

@interface IBUITableViewCachedSectionLayoutInfoInfo : IBUIViewCachedGeometryInfo
{
    IBUITableView *_tableView;
}

- (void).cxx_destruct;
@property __weak IBUITableView *tableView; // @synthesize tableView=_tableView;
- (id)cachedValueFromRequestedValue:(id)arg1;
- (id)initWithTableView:(id)arg1;

@end

