//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBUIViewCachedGeometryInfo.h>

@class IBUINavigationBar, NSString;

@interface IBUINavigationBarItemsArrayCachedFramesInfo : IBUIViewCachedGeometryInfo
{
    IBUINavigationBar *_navBar;
    NSString *_itemsKeyPath;
}

@property(copy, nonatomic) NSString *itemsKeyPath; // @synthesize itemsKeyPath=_itemsKeyPath;
@property __weak IBUINavigationBar *navBar; // @synthesize navBar=_navBar;
- (void).cxx_destruct;
- (id)cachedValueFromRequestedValue:(id)arg1;
- (id)initWithNavigationBar:(id)arg1 itemsKeyPath:(id)arg2 cachedKeyPath:(id)arg3 requestedKeyPath:(id)arg4;

@end

