//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBUISimulatedSizeMetrics.h>

@interface IBUISplitViewMasterSimulatedSizeMetrics : IBUISimulatedSizeMetrics
{
}

+ (id)sharedInstance;
- (id)configurationForScreenMetrics:(id)arg1 orientationMetrics:(id)arg2;
- (id)fixedSizeMetricsForScreenMetrics:(id)arg1 orientationMetrics:(id)arg2 freeformSize:(struct CGSize)arg3;
- (id)displayName;
- (void)encodeWithCoder:(id)arg1;

@end

