//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBDropTargetResolverDelegate-Protocol.h>

@class IBUIStackViewDropTargetResolver;

@protocol IBUIStackViewDropTargetResolverDelegate <IBDropTargetResolverDelegate>
- (void)dropTargetResolver:(IBUIStackViewDropTargetResolver *)arg1 insertionIndexDidChange:(long long)arg2;
- (void)dropTargetResolver:(IBUIStackViewDropTargetResolver *)arg1 insertionIndexWillChange:(long long)arg2;
@end

