//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEImageMediaResource.h>

@class IBCocoaTouchPlatform;

@interface IBUIImageMediaResource : IDEImageMediaResource
{
    IBCocoaTouchPlatform *_platform;
}

+ (id)fetchContentForSystemImageName:(id)arg1 platform:(id)arg2 minimumSize:(struct CGSize)arg3 maximumSize:(struct CGSize)arg4;
+ (id)createPlaceholderImage;
+ (id)generateContentWithContext:(id)arg1;
+ (id)generateIconWithContext:(id)arg1;
@property(readonly) IBCocoaTouchPlatform *platform; // @synthesize platform=_platform;
- (void).cxx_destruct;
- (id)detailViewHeading;
- (BOOL)detailViewShowsAlternates;
- (BOOL)alwaysShowsIconAsLibraryDetailViewPreview;
- (id)captureContextOnMainThreadBeforeGeneratingContent;
- (id)captureContextOnMainThreadBeforeGeneratingIcon;
- (id)initWithName:(id)arg1 metadata:(id)arg2 platform:(id)arg3;

@end

