//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DebuggerFoundation/NSObject-Protocol.h>

@class DBGLazyObservableDictionary, NSString;

@protocol DBGLazyObservableDictionaryDelegate <NSObject>
- (id)valueForKey:(NSString *)arg1 forLazyDictionary:(DBGLazyObservableDictionary *)arg2;
@end

