//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface DBGViewDebuggerAssetManager : NSObject
{
    NSMutableDictionary *_assets;
}

@property(retain) NSMutableDictionary *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;
- (void)clearData;
- (id)_assetIdentifierForItemIdentifier:(id)arg1 query:(id)arg2;
- (void)storeAsset:(id)arg1 forItemWithIdentifier:(id)arg2 query:(id)arg3;
- (id)assetForItemWithIdentifier:(id)arg1 query:(id)arg2 creationBlock:(CDUnknownBlockType)arg3;
- (id)assetForItemWithIdentifier:(id)arg1 query:(id)arg2;
- (id)init;

@end

