//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DebuggerFoundation/DBGViewObject.h>

#import <DebuggerFoundation/DBGSelectableViewObject-Protocol.h>

@class DBGApplicationObject, NSArray, NSMapTable, NSString;

@interface DBGWindowControllerObject : DBGViewObject <DBGSelectableViewObject>
{
    NSMapTable *_addressesToViewObjectsCache;
    DBGApplicationObject *_application;
    NSArray *_contentViewControllers;
    NSArray *_windows;
}

- (void).cxx_destruct;
@property(retain) NSArray *windows; // @synthesize windows=_windows;
@property(retain) NSArray *contentViewControllers; // @synthesize contentViewControllers=_contentViewControllers;
@property __weak DBGApplicationObject *application; // @synthesize application=_application;
- (void)_recursivelyUpdateAddressesToViewObjectsWithMapTable:(id)arg1;
- (id)_createAddressesToViewObjectsMap;
- (id)selectableViewObjectForIdentifier:(id)arg1;
- (void)updateSelectableViewObjectsCache;
- (unsigned long long)recursivelyUpdateNumberOfChildObjectsWithIssues;
- (void)setChildViewObjects:(id)arg1;
- (void)primitiveInvalidate;
- (id)_formattedDisplayNameForUISceneInstance:(id)arg1;
- (id)computedSecondaryDisplayName;
- (void)updateChildrenWithSnapshotGroup:(id)arg1 forRequest:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

