//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class IDEGaugeReportTableView;

@interface IDEDebugGaugeReportEntityListViewController : NSViewController
{
    IDEGaugeReportTableView *_tableView;
}

@property(retain, nonatomic) IDEGaugeReportTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)loadView;
- (id)init;

@end

