//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTMarkup/_TtC9DVTMarkup6XPView.h>

@class MISSING_TYPE;

@interface _TtC9DVTMarkupP33_8D794F29D5B038FCB7B9F093D50033A411OrdinalView : _TtC9DVTMarkup6XPView
{
    MISSING_TYPE *drawingMode;
    MISSING_TYPE *label;
    MISSING_TYPE *style;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

