//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC13MLComposerKit14TrainingWorker : _TtCs12_SwiftObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: taskType
    // Error parsing type: , name: trainer
    // Error parsing type: , name: modelName
    // Error parsing type: , name: controlCenter
    // Error parsing type: , name: master
}

@end

