//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MLComposerKit/_TtC13MLComposerKit31ProjectObservableViewController.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit21ProjectViewController : _TtC13MLComposerKit31ProjectObservableViewController
{
    MISSING_TYPE *outlineView;
    MISSING_TYPE *summaryViewController;
    MISSING_TYPE *settingViewController;
    MISSING_TYPE *data;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end

