//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit13WTPreviewItem : NSCollectionViewItem
{
    MISSING_TYPE *cellView;
    MISSING_TYPE *result;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;

@end

