//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit28ComposerEditorViewController : NSViewController
{
    MISSING_TYPE *projectEditor;
    MISSING_TYPE *experimentEditors;
    MISSING_TYPE *dataSourceEditors;
    MISSING_TYPE *backgroundView;
    MISSING_TYPE *currentEditor;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end

