//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindow.h>

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit14ComposerWindow : NSWindow
{
    // Error parsing type: , name: selectedButtonType
}

- (void).cxx_destruct;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;
@property(nonatomic, readonly) BOOL acceptsFirstResponder;
@property(nonatomic, readonly) BOOL canBecomeKeyWindow;

@end

