//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit22TimelineControlBarView : NSView
{
    // Error parsing type: , name: rewindButton
    // Error parsing type: , name: playButton
    // Error parsing type: , name: forwardButton
    // Error parsing type: , name: separatorView
    // Error parsing type: , name: backgroundView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

