//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC13MLComposerKit10Evaluation : _TtCs12_SwiftObject
{
    // Error parsing type: , name: accuracy
    // Error parsing type: , name: startTime
    // Error parsing type: , name: finishTime
    // Error parsing type: , name: duration
    // Error parsing type: , name: trainedEvaluationURL
    // Error parsing type: , name: trainedEvaluationItemCount
    // Error parsing type: , name: dataResult
    // Error parsing type: , name: analysedDataType
    // Error parsing type: , name: error
    // Error parsing type: , name: result
}

@end

