//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13MLComposerKit14TrainingWorker : _TtCs12_SwiftObject
{
    MISSING_TYPE *id;
    MISSING_TYPE *taskType;
    MISSING_TYPE *trainer;
    MISSING_TYPE *modelName;
    MISSING_TYPE *controlCenter;
    MISSING_TYPE *master;
}

@end

