//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC13MLComposerKit12AnalysedData : _TtCs12_SwiftObject
{
    // Error parsing type: , name: dataSourceID
    // Error parsing type: , name: dataURL
    // Error parsing type: , name: classesCount
    // Error parsing type: , name: itemsCount
    // Error parsing type: , name: partitionAmount
    // Error parsing type: , name: suggestedMaxIterations
    // Error parsing type: , name: error
    // Error parsing type: , name: analysis
    // Error parsing type: , name: columns
    // Error parsing type: , name: columnTypes
    // Error parsing type: , name: columnValues
    // Error parsing type: , name: targetRange
}

@end

