//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MLComposerKit/_TtC13MLComposerKit16ComposerDocument.h>

@class NSDate;

@interface _TtC13MLComposerKit16ComposerDocument (MLComposerKit1)
@property(nonatomic, copy) NSDate *fileModificationDate;
@end

