//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _TtC13MLComposerKit32GeneralRegressorMetricColumnData;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit30GeneralRegressorMetricsRowData : NSObject
{
    // Error parsing type: , name: metricNameColumn
    // Error parsing type: , name: metricValueColumn
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) _TtC13MLComposerKit32GeneralRegressorMetricColumnData *metricValueColumn; // @synthesize metricValueColumn;
@property(nonatomic, retain) _TtC13MLComposerKit32GeneralRegressorMetricColumnData *metricNameColumn; // @synthesize metricNameColumn;

@end

