//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MLComposerKit/_TtC13MLComposerKit34ExperimentObservableViewController.h>

@class MISSING_TYPE, NSView, _TtC13MLComposerKit16HeaderButtonView;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit30ExperimentEditorViewController : _TtC13MLComposerKit34ExperimentObservableViewController
{
    MISSING_TYPE *setupButtonView;
    MISSING_TYPE *trainingButtonView;
    MISSING_TYPE *validationButtonView;
    MISSING_TYPE *evaluationButtonView;
    MISSING_TYPE *outputButtonView;
    MISSING_TYPE *headerContainer;
    MISSING_TYPE *headerView;
    MISSING_TYPE *containerView;
    MISSING_TYPE *currentSelectedButton;
    MISSING_TYPE *setupViewController;
    MISSING_TYPE *trainingViewController;
    MISSING_TYPE *validationViewController;
    MISSING_TYPE *evaluationViewController;
    MISSING_TYPE *previewViewController;
    MISSING_TYPE *currentViewController;
    MISSING_TYPE *storedMaxIterationsForTextClassifierAndWordTagger;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(nonatomic) __weak NSView *containerView; // @synthesize containerView;
@property(nonatomic) __weak NSView *headerContainer; // @synthesize headerContainer;
@property(nonatomic) __weak _TtC13MLComposerKit16HeaderButtonView *outputButtonView; // @synthesize outputButtonView;
@property(nonatomic) __weak _TtC13MLComposerKit16HeaderButtonView *evaluationButtonView; // @synthesize evaluationButtonView;
@property(nonatomic) __weak _TtC13MLComposerKit16HeaderButtonView *validationButtonView; // @synthesize validationButtonView;
@property(nonatomic) __weak _TtC13MLComposerKit16HeaderButtonView *trainingButtonView; // @synthesize trainingButtonView;
@property(nonatomic) __weak _TtC13MLComposerKit16HeaderButtonView *setupButtonView; // @synthesize setupButtonView;

@end

