//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MLComposerKit/_TtC13MLComposerKit34DataSourceObservableViewController.h>

@class MISSING_TYPE, NSStackView, NSTextField, _TtC13MLComposerKit9ColorView;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit35DataSourceSetupStatusViewController : _TtC13MLComposerKit34DataSourceObservableViewController
{
    MISSING_TYPE *statusView;
    MISSING_TYPE *categoriesLabel;
    MISSING_TYPE *trainingItemsLabel;
    MISSING_TYPE *sizeOnDiskLabel;
    MISSING_TYPE *lineView;
    MISSING_TYPE *backgroundView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC13MLComposerKit9ColorView *lineView; // @synthesize lineView;
@property(nonatomic) __weak NSTextField *sizeOnDiskLabel; // @synthesize sizeOnDiskLabel;
@property(nonatomic) __weak NSTextField *trainingItemsLabel; // @synthesize trainingItemsLabel;
@property(nonatomic) __weak NSTextField *categoriesLabel; // @synthesize categoriesLabel;
@property(nonatomic) __weak NSStackView *statusView; // @synthesize statusView;

@end

