//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MLComposerKit/_TtC13MLComposerKit34ExperimentObservableViewController.h>

@class NSScrollView, NSTextField, _TtC13MLComposerKit9ColorView;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit27TCPreviewDataViewController : _TtC13MLComposerKit34ExperimentObservableViewController
{
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: contentTextField
    // Error parsing type: , name: resultLabel
    // Error parsing type: , name: lineView
    // Error parsing type: , name: predictionHeaderLabel
    // Error parsing type: , name: delegate
    // Error parsing type: , name: startTimer
    // Error parsing type: , name: tempURL
    // Error parsing type: , name: isLiveText
    // Error parsing type: , name: result
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)analyzeLiveText;
- (void)controlTextDidChange:(id)arg1;
- (void)inferenceFinishedWithNotification:(id)arg1;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(nonatomic) __weak NSTextField *predictionHeaderLabel; // @synthesize predictionHeaderLabel;
@property(nonatomic) __weak _TtC13MLComposerKit9ColorView *lineView; // @synthesize lineView;
@property(nonatomic) __weak NSTextField *resultLabel; // @synthesize resultLabel;
@property(nonatomic) __weak NSTextField *contentTextField; // @synthesize contentTextField;
@property(nonatomic) __weak NSScrollView *scrollView; // @synthesize scrollView;

@end

