//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MLComposerKit/_TtC13MLComposerKit34DataSourceObservableViewController.h>

@class NSImageView;

__attribute__((visibility("hidden")))
@interface _TtC13MLComposerKit38ODDataSourceSetupPreviewViewController : _TtC13MLComposerKit34DataSourceObservableViewController
{
    // Error parsing type: , name: previewImageView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (void)loadView;
@property(nonatomic) __weak NSImageView *previewImageView; // @synthesize previewImageView;

@end

