//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC13MLComposerKit23ErrorReductionChartView;

@protocol _TtP13MLComposerKit29ErrorReductionChartDataSource_
- (long long)numberOfEnteriesIn:(_TtC13MLComposerKit23ErrorReductionChartView *)arg1;
@end

