//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (XREngineeringValueHelpers)
+ (BOOL)xr_object:(id)arg1 isEqual:(id)arg2;
- (id)uuidFromEngineeringValue;
- (id)xr_clipsStringRepresentation;
- (BOOL)xr_isCLIPSSymbol;
- (int)agentStopDiagnosticsTypeCode;
@end

