//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTInstrumentsUtilities/XRFrameActivityManagerPrivate-Protocol.h>
#import <DVTInstrumentsUtilities/XRMobileAgentStop-Protocol.h>

@class NSString, XRFrameActivity;

@interface XRFrameActivityManager : NSObject <XRFrameActivityManagerPrivate, XRMobileAgentStop>
{
    shared_ptr_5180c3d3 _managerImpl;
    shared_ptr_5180c3d3 _secondTierManagerImpl;
    XRFrameActivity *_syncActivity;
    int _kdebugCodeBase;
    unsigned long long _signpostID;
    unsigned long long _ringSignpostID;
    unsigned char _currentSlot;
}

+ (void)initialize;
+ (BOOL)_establishesAffinity;
+ (int)_identifierForSignposting;
+ (unsigned int)_activityQoS;
+ (BOOL)supportsQoS;
+ (BOOL)enableConcurrentActivities;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned char currentSlot; // @synthesize currentSlot=_currentSlot;
- (BOOL)holdBackArrivingAgent:(id)arg1;
- (BOOL)holdBackRevisitingAgent:(id)arg1;
- (void)startingMajorFrame;
- (void)extendingMinorFrame:(unsigned char)arg1;
- (void)underrunMinorFrame:(unsigned char)arg1;
- (void)yieldingMinorFrame:(unsigned char)arg1;
- (void)enteringMinorFrame:(unsigned char)arg1;
- (shared_ptr_5180c3d3 *)_secondTierManagerImplPtr;
- (shared_ptr_5180c3d3 *)_managerImplPtr;
- (void)_shutdown;
- (void)_startingMajorFrame;
- (void)_extendingMinorFrame:(unsigned char)arg1;
- (void)_underrunMinorFrame:(unsigned char)arg1;
- (void)_yieldingMinorFrame:(unsigned char)arg1;
- (void)_acquiredMinorFrame:(unsigned char)arg1;
- (void)activateNextMajorFrame;
- (void)_needsScheduling;
- (void)_finalShutdown;
- (void)_prepareMinorFrameAgent:(id)arg1;
- (void)_escortMinorFrameAgentToExit:(id)arg1;
- (void)_reevaluateArrivingAgent:(id)arg1;
- (void)receiveMobileAgent:(id)arg1;
- (void)setupVisitDuringMinorFrame:(id)arg1 agent:(id)arg2 mode:(id)arg3 ticket:(id)arg4;
- (void)scheduleInactivity:(CDUnknownBlockType)arg1;
- (void)scheduleActivity:(CDUnknownBlockType)arg1;
- (id)scheduleActivityAsOperation:(CDUnknownBlockType)arg1;
- (void)performOutsideMinorFrame:(CDUnknownBlockType)arg1;
- (void)performDuringMinorFrame:(CDUnknownBlockType)arg1;
- (int)agentStopDiagnosticsTypeCode;
- (void)dealloc;
- (id)init;
- (id)initWithRing:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

