//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTDaemonControl/XCTConfigurableDebugLogger-Protocol.h>

@class NSString, NSUUID, XCTCapabilities;
@protocol XCTDebugLogDelegate;

@interface XCTDaemonInitiateSessionRequest : NSObject <XCTConfigurableDebugLogger>
{
    id <XCTDebugLogDelegate> _logDelegate;
    NSUUID *_sessionIdentifier;
    XCTCapabilities *_IDECapabilities;
    CDUnknownBlockType _completion;
}

+ (id)daemonCapabilitiesForLegacyProtocolVersion:(unsigned long long)arg1;
+ (id)currentProcessDisplayPath;
+ (id)clientProcessUniqueIdentifier;
- (void).cxx_destruct;
@property(readonly) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly) XCTCapabilities *IDECapabilities; // @synthesize IDECapabilities=_IDECapabilities;
@property(readonly) NSUUID *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
@property __weak id <XCTDebugLogDelegate> logDelegate; // @synthesize logDelegate=_logDelegate;
- (void)_attemptVersion9APIWithDaemonProxy:(id)arg1;
- (void)executeWithDaemonProxy:(id)arg1;
- (id)initWithSessionIdentifier:(id)arg1 capabilities:(id)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

