//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTDaemonControl/XCTDaemonRequest-Protocol.h>

@class NSArray, NSString;

@interface XCTDaemonCollectCrashReportsRequest : NSObject <XCTDaemonRequest>
{
    NSArray *_directories;
    NSArray *_processNames;
    CDUnknownBlockType _completion;
}

- (void).cxx_destruct;
@property(readonly) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly) NSArray *processNames; // @synthesize processNames=_processNames;
@property(readonly) NSArray *directories; // @synthesize directories=_directories;
- (void)handleConnectionFailure:(id)arg1;
- (void)executeWithDaemonProxy:(id)arg1 daemonCapabilities:(id)arg2;
- (id)initWithDirectories:(id)arg1 matchingProcessNames:(id)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

