//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/NSObject-Protocol.h>

@class IBAbstractPlatformToolExecutionContext, IBSimDeviceDebuggingViewController, SimDevice;

@protocol IBSimDeviceDebuggingViewControllerDelegate <NSObject>
- (SimDevice *)simDeviceForSimDeviceDebuggingViewController:(IBSimDeviceDebuggingViewController *)arg1;
- (IBAbstractPlatformToolExecutionContext *)executionContextForSimDeviceDebuggingViewController:(IBSimDeviceDebuggingViewController *)arg1;
@end

