//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC10DVTIconKit27GeneratedIconDrawingContext : NSObject
{
    MISSING_TYPE *_specificationContext;
    MISSING_TYPE *_currentIconName;
    MISSING_TYPE *_cachedResolutionAndIconSpec;
    MISSING_TYPE *_cachedDrawable;
    MISSING_TYPE *currentIconSetName;
    MISSING_TYPE *currentBundle;
    MISSING_TYPE *intendedSize;
    MISSING_TYPE *scaleFactor;
    MISSING_TYPE *aspects;
    MISSING_TYPE *$__lazy_storage_$_cacheKey;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;

@end

