//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTIconKit/_TtC10DVTIconKitP33_024E449D696B72C5F7638FF7B5849B9F19_FileLoadedIconSpec.h>

@interface _TtC10DVTIconKitP33_024E449D696B72C5F7638FF7B5849B9F31_IconSpecLoadedFromCompiledFile : _TtC10DVTIconKitP33_024E449D696B72C5F7638FF7B5849B9F19_FileLoadedIconSpec
{
}

@end

