//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCFC13MarkupSupport21MarkupLanguageServiceP33_B4A80E1A1A64C2C01127DA1BAE35B1F315updateLandmarksFT_T_L_14HeadingDetails : _TtCs12_SwiftObject
{
    MISSING_TYPE *level;
    MISSING_TYPE *singleLineOnly;
    MISSING_TYPE *start;
    MISSING_TYPE *nameComponents;
    MISSING_TYPE *nameStart;
    MISSING_TYPE *nameEnd;
}

@end

