//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderRelationshipPredicateDouble.h>

@interface IDEIntentBuilderRelationshipPredicateDoubleValueIsLessThan : IDEIntentBuilderRelationshipPredicateDouble
{
}

+ (id)relationshipPredicate;
- (long long)doesSatisfyRelationshipPredicate:(id)arg1;

@end

