//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface IDEIntentBuilderPropertyTypeUnsupportedReason : NSObject
{
    NSString *_code;
    NSString *_formatString;
    NSArray *_tokens;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *tokens; // @synthesize tokens=_tokens;
@property(copy, nonatomic) NSString *formatString; // @synthesize formatString=_formatString;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
- (id)description;
- (id)initWithCode:(id)arg1 formatString:(id)arg2 tokens:(id)arg3;

@end

