//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HXQueryWorkingData : NSObject
{
    struct DefaultQueryWorkingData m_dataStruct;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)sortResultIndices;
- (BOOL)hasIndex:(long long)arg1;
- (long long)objectAtIndexedSubscript:(long long)arg1;
@property(readonly, nonatomic) long long resultCount;
- (id)init;

@end

