//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class MISSING_TYPE;

@interface _TtC29IDESourceCodeComparisonEditor16BlameSidebarView : NSView
{
    MISSING_TYPE *borderLayer;
}

- (void).cxx_destruct;
- (BOOL)isFlipped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(nonatomic, readonly) BOOL flipped;

@end

