//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC12DVTAnalytics22DiskWriteLogStackFrame : NSObject
{
    MISSING_TYPE *rawFrame;
    MISSING_TYPE *offset;
    MISSING_TYPE *function;
    MISSING_TYPE *fileName;
    MISSING_TYPE *library;
    MISSING_TYPE *sampleCount;
    MISSING_TYPE *lineNumber;
    MISSING_TYPE *address;
    MISSING_TYPE *$__lazy_storage_$_uuidFromLibrary;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;

@end

