//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTAnalytics/DVTCrashLogStackFrameParser.h>

@interface DVTUnsymbolicatedStackFrameParser : DVTCrashLogStackFrameParser
{
}

- (id)parsedStackFrameFromText:(id)arg1;

@end

