//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7XCBUtil12BinaryReader : _TtCs12_SwiftObject
{
    MISSING_TYPE *data;
    MISSING_TYPE *size;
    MISSING_TYPE *cursors;
    MISSING_TYPE *startingOffset;
}

@end

