//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSString;

@interface DVTLibraryTileViewSection : NSObject
{
    MISSING_TYPE *title;
    MISSING_TYPE *items;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithTitle:(id)arg1 items:(id)arg2;
@property(nonatomic, readonly) NSArray *items;
@property(nonatomic, readonly) NSString *title;

@end

