//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEITunesSoftwareServiceFoundation/IDEITunesConnectVersionDescription.h>

@interface _TtC34IDEITunesSoftwareServiceFoundation41IDEITunesConnectAppClipVersionDescription : IDEITunesConnectVersionDescription
{
}

+ (BOOL)supportsSecureCoding;
- (id)init;
- (id)initWithITunesSoftwareBundleDescription:(id)arg1;
- (id)initWithName:(id)arg1 displayableDescription:(id)arg2 platformIdentifier:(id)arg3 bundleIdentifier:(id)arg4 marketingVersion:(id)arg5 shortVersion:(id)arg6 version:(id)arg7 isMacOSEligible:(BOOL)arg8 generations:(id)arg9;
- (id)initWithITunesSoftwareVersionDescription:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 displayableDescription:(id)arg2 platformIdentifier:(id)arg3 bundleIdentifier:(id)arg4;
- (id)initWithITunesSoftwareAppClipVersionDescription:(id)arg1;

@end

