//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEModelFoundation/NSObject-Protocol.h>

@class NSNumber, NSString;

@protocol CDMIdentification <NSObject>
@property(copy) NSNumber *uniqueID;
@property(copy, nonatomic) NSString *name;
@end

