//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEModelFoundation/XDMappingCompilerCallback-Protocol.h>

@class NSDictionary, NSMappingModel, NSMutableArray, XDMappingModelManager;

@interface XDMappingCompilerSupport : NSObject <XDMappingCompilerCallback>
{
    XDMappingModelManager *_modelManager;
    NSMutableArray *_errorsAndWarnings;
    NSMappingModel *_result;
    BOOL _hasErrors;
    NSDictionary *_options;
}

+ (id)stringForErrorCategory:(int)arg1;
- (void).cxx_destruct;
- (BOOL)continueGeneration;
- (void)addWarningForElement:(id)arg1 prefix:(id)arg2 message:(id)arg3 category:(int)arg4;
- (void)addErrorForElement:(id)arg1 prefix:(id)arg2 message:(id)arg3 category:(int)arg4;
- (void)printCompiledObject:(id)arg1;
- (id)printErrorsAndWarnings:(BOOL)arg1;
- (BOOL)hasErrors;
- (id)errorsAndWarnings;
- (id)result;
- (BOOL)compileSourcePath:(id)arg1 options:(id)arg2;
- (void)generateCompileResultForMappingModel:(id)arg1 sourceModelHashes:(id)arg2 destinationModelHashes:(id)arg3;
- (id)init;

@end

