//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCBCore/_TtC7XCBCore4Spec.h>

@class MISSING_TYPE;

@interface _TtC7XCBCore12FileTypeSpec : _TtC7XCBCore4Spec
{
    MISSING_TYPE *isBundle;
    MISSING_TYPE *isFramework;
    MISSING_TYPE *extensions;
    MISSING_TYPE *languageDialect;
    MISSING_TYPE *isEmbeddableInProduct;
    MISSING_TYPE *codeSignOnCopy;
    MISSING_TYPE *validateOnCopy;
}

@end

