//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCZFC7XCBCore21MacroConfigFileParser29parseMacroNameAndConditionSetFSSTGSqSS_GSqGSaT5paramSS7patternSS____L_23SingleMacroNameDelegate : _TtCs12_SwiftObject
{
    MISSING_TYPE *macroName;
    MISSING_TYPE *conditions;
}

@end

