//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCBCore/_TtC7XCBCore12FileTypeSpec.h>

@interface _TtC7XCBCore34PlugInKitPluginWrapperFileTypeSpec : _TtC7XCBCore12FileTypeSpec
{
}

@end

