//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCBCore/_TtC7XCBCore19GenericCompilerSpec.h>

@interface _TtC7XCBCore15MetalLinkerSpec : _TtC7XCBCore19GenericCompilerSpec
{
}

@end

