//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7XCBCore18DependencyResolver : _TtCs12_SwiftObject
{
    MISSING_TYPE *buildRequest;
    MISSING_TYPE *workspaceContext;
    MISSING_TYPE *delegate;
    MISSING_TYPE *serialQueue;
    MISSING_TYPE *buildParametersByTarget;
    MISSING_TYPE *configuredTargetsByTarget;
}

@end

