//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7XCBCore7Project : _TtCs12_SwiftObject
{
    MISSING_TYPE *signature;
    MISSING_TYPE *guid;
    MISSING_TYPE *xcodeprojPath;
    MISSING_TYPE *sourceRoot;
    MISSING_TYPE *name;
    MISSING_TYPE *targets;
    MISSING_TYPE *groupTree;
    MISSING_TYPE *buildConfigurations;
    MISSING_TYPE *defaultConfigurationName;
    MISSING_TYPE *developmentRegion;
    MISSING_TYPE *classPrefix;
    MISSING_TYPE *appPreferencesBuildSettings;
    MISSING_TYPE *isPackage;
}

@end

