//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface IBICIssueGenerationContext : NSObject
{
    int _phase;
    NSMutableDictionary *_userInfo;
}

+ (id)issueGenerationContextWithPhase:(int)arg1;
- (void).cxx_destruct;
@property(readonly) int phase; // @synthesize phase=_phase;
@property(readonly) NSMutableDictionary *userInfo; // @synthesize userInfo=_userInfo;
- (id)initWithPhase:(int)arg1;
- (id)init;

@end

