//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSConditionLock;

@interface IBSemaphore : NSObject
{
    NSConditionLock *_lock;
    long long _count;
}

- (void).cxx_destruct;
- (void)increment;
- (BOOL)decrementWithTimeout:(id)arg1;
- (void)decrementWithoutBlocking;
- (void)decrement;
- (id)initWithCount:(long long)arg1;

@end

