//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s12DVTAnalytics19ProcessorUsagePointCN.h"

@interface _$s12DVTAnalytics19ProcessorUsagePointCN (IDEProducts)
- (id)debuggerPointFor:(id)arg1 containing:(id)arg2 workspace:(id)arg3 productVersion:(id)arg4 error:(id *)arg5;
@end

