//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC25DVTAnalyticsMetricsClient29AnalyticsMetricsAppIdentifier : NSObject
{
    MISSING_TYPE *adamIdentifier;
    MISSING_TYPE *bundleIdentifier;
    MISSING_TYPE *platform;
    MISSING_TYPE *analyticsPlatform;
}

- (void).cxx_destruct;
- (id)initWithAdamIdentifier:(id)arg1 bundleIdentifier:(id)arg2 platform:(id)arg3;
- (id)init;
@property(nonatomic, readonly) NSString *debugDescription;
@property(nonatomic, readonly) NSString *identifier;
@property(nonatomic, copy) NSString *analyticsPlatform;
@property(nonatomic, copy) NSString *platform;
@property(nonatomic, copy) NSString *bundleIdentifier;
@property(nonatomic, copy) NSString *adamIdentifier;

@end

