//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;
@protocol IDEPlaygroundDeviceOwner;

@protocol IDEPlaygroundDeviceOwner
- (void)playgroundDeviceWithIdentifier:(NSString *)arg1 wasAssignedToOwner:(id <IDEPlaygroundDeviceOwner>)arg2;
- (void)playgroundDeviceWithIdentifier:(NSString *)arg1 wasRequestedBy:(id <IDEPlaygroundDeviceOwner>)arg2;
@end

