//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/DVTCharacterRangeFrameConverter-Protocol.h>
#import <IDEInterfaceBuilderKit/DVTLineRangeCharacterRangeConverter-Protocol.h>
#import <IDEInterfaceBuilderKit/DVTSourceCodeLanguageEditorView-Protocol.h>
#import <IDEInterfaceBuilderKit/DVTSourceLandmarkItemContainer-Protocol.h>
#import <IDEInterfaceBuilderKit/DVTSourceModelProvider-Protocol.h>
#import <IDEInterfaceBuilderKit/DVTTextInsertionPointLocator-Protocol.h>

@protocol DVTSourceEditorViewProtocol <DVTSourceModelProvider, DVTSourceCodeLanguageEditorView, DVTSourceLandmarkItemContainer, DVTLineRangeCharacterRangeConverter, DVTCharacterRangeFrameConverter, DVTTextInsertionPointLocator>
@end

