//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IBFoundation/IBBitmap.h>

@interface IBBitmap (IBAppKitAdditions)
- (id)debugQuickLookObject;
- (id)nsImageWithColorSpace:(struct CGColorSpace *)arg1 scaleFactor:(double)arg2;
- (id)nsImageWithColorSpace:(struct CGColorSpace *)arg1;
@end

