//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface IBConnectionPanelClipView : NSView
{
}

- (void)makeRectVisible:(struct CGRect)arg1 ofView:(id)arg2;
- (BOOL)isFlipped;
- (id)documentView;
- (id)scrollView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

