//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTViewControllerKit/DVTViewController.h>

#import <IDEInterfaceBuilderKit/IBDeviceBarGroupViewControllerDelegate-Protocol.h>
#import <IDEInterfaceBuilderKit/IBDeviceTraitPickerPopoverViewControllerDelegate-Protocol.h>
#import <IDEInterfaceBuilderKit/NSPopoverDelegate-Protocol.h>

@class DVTObservingToken, IBDeviceAppearance, IBDeviceBarBranchModeButton, IBDeviceBarGroupViewController, IBDeviceConfiguration, IBDeviceLayout, IBDeviceOrientation, IBDeviceRenderMode, IBDocument, NSArray, NSMutableArray, NSMutableDictionary, NSPopover, NSStackView, NSString, _IBDeviceBarStackDividerView;

@interface IBDeviceBarViewController : DVTViewController <NSPopoverDelegate, IBDeviceBarGroupViewControllerDelegate, IBDeviceTraitPickerPopoverViewControllerDelegate>
{
    IBDocument *_document;
    NSStackView *_configurationsStackView;
    NSMutableArray *_visibleGroups;
    NSArray *_outerStackViewPinningConstraints;
    _IBDeviceBarStackDividerView *_stackDividerBeforeAppearancesGroup;
    _IBDeviceBarStackDividerView *_stackDividerBeforeRenderModeGroup;
    _IBDeviceBarStackDividerView *_stackDividerBeforeOrientationsGroup;
    _IBDeviceBarStackDividerView *_stackDividerBeforeLayoutsGroup;
    IBDeviceAppearance *_downstreamSelectedAppearance;
    IBDeviceRenderMode *_downstreamSelectedRenderMode;
    IBDeviceOrientation *_downstreamSelectedOrientation;
    IBDeviceLayout *_downstreamSelectedLayout;
    IBDeviceConfiguration *_deviceConfigurationBeforeCustomizing;
    IBDeviceBarBranchModeButton *_customizeButton;
    NSPopover *_customizePopover;
    id _deviceImageGenerationContext;
    NSMutableDictionary *_deviceConfigurationsToDeviceImagesMap;
    NSMutableDictionary *_deviceConfigurationsToPopUpDeviceImagesMap;
    struct CGSize _devicesGroupConfiguredSize;
    DVTObservingToken *_usesConfigurationsObservingToken;
    BOOL _customizing;
    CDUnknownBlockType _deviceConfigurationChangedCallback;
    CDUnknownBlockType _customizationModeChangedStateCallback;
    IBDeviceConfiguration *_selectedDeviceConfiguration;
    NSArray *_deviceSubtypes;
    IBDeviceConfiguration *_deviceConfiguration;
    IBDeviceBarGroupViewController *_devicesGroup;
    IBDeviceBarGroupViewController *_appearancesGroup;
    IBDeviceBarGroupViewController *_renderModeGroup;
    IBDeviceBarGroupViewController *_orientationsGroup;
    IBDeviceBarGroupViewController *_layoutsGroup;
    IBDeviceBarGroupViewController *_devicesGroupForBranchMode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IBDeviceBarGroupViewController *devicesGroupForBranchMode; // @synthesize devicesGroupForBranchMode=_devicesGroupForBranchMode;
@property(retain, nonatomic) IBDeviceBarGroupViewController *layoutsGroup; // @synthesize layoutsGroup=_layoutsGroup;
@property(retain, nonatomic) IBDeviceBarGroupViewController *orientationsGroup; // @synthesize orientationsGroup=_orientationsGroup;
@property(retain, nonatomic) IBDeviceBarGroupViewController *renderModeGroup; // @synthesize renderModeGroup=_renderModeGroup;
@property(retain, nonatomic) IBDeviceBarGroupViewController *appearancesGroup; // @synthesize appearancesGroup=_appearancesGroup;
@property(retain, nonatomic) IBDeviceBarGroupViewController *devicesGroup; // @synthesize devicesGroup=_devicesGroup;
@property(retain, nonatomic) IBDeviceConfiguration *deviceConfiguration; // @synthesize deviceConfiguration=_deviceConfiguration;
@property(readonly, nonatomic) NSArray *deviceSubtypes; // @synthesize deviceSubtypes=_deviceSubtypes;
@property(nonatomic, getter=isCustomizing) BOOL customizing; // @synthesize customizing=_customizing;
@property(retain, nonatomic) IBDeviceConfiguration *selectedDeviceConfiguration; // @synthesize selectedDeviceConfiguration=_selectedDeviceConfiguration;
@property(copy, nonatomic) CDUnknownBlockType customizationModeChangedStateCallback; // @synthesize customizationModeChangedStateCallback=_customizationModeChangedStateCallback;
@property(copy, nonatomic) CDUnknownBlockType deviceConfigurationChangedCallback; // @synthesize deviceConfigurationChangedCallback=_deviceConfigurationChangedCallback;
- (id)groupViewController:(id)arg1 popUpImageForDeviceConfiguration:(id)arg2;
- (id)_customizationSessionSummaryWithDeviceConfigurations:(id)arg1 memberConfiguration:(id)arg2 selectedConfigurationDevice:(id)arg3;
- (void)_customizationStateChanged;
- (void)_fireCustomizationModeCallback:(id)arg1;
- (void)popoverDidClose:(id)arg1;
- (void)popoverWillShow:(id)arg1;
- (void)_changeCustomizeButtonToDoneButton;
- (void)customize:(id)arg1;
- (void)deviceTraitPickerPopoverViewController:(id)arg1 didSelectTraits:(id)arg2;
- (void)_userDidSelectTraitsForBranching:(id)arg1;
- (id)_deviceConfigurationsMatchingMemberConfiguration:(id)arg1;
- (void)finishCustomizing:(id)arg1;
- (void)_resetAndReconfigure;
- (void)_addCustomizationsButton;
- (void)_updateCustomizeButtonTitle;
- (id)_selectedMemberConfiguration;
- (id)_sortedSelectionButtonsForButtons:(id)arg1;
- (id)buttonForConfiguration:(id)arg1 image:(id)arg2 accessibilityIdentifier:(id)arg3 displayName:(id)arg4 forBranchMode:(BOOL)arg5;
- (id)buttonForConfiguration:(id)arg1 accessibilityIdentifier:(id)arg2 displayName:(id)arg3 forBranchMode:(BOOL)arg4;
- (id)_addGroupDividerView;
- (void)_makeConfigurationsStackView;
- (void)restoreConfiguration:(id)arg1 resetAll:(BOOL)arg2;
- (id)validRenderModesForDeviceSubtype:(id)arg1 buildSettingsSnapshot:(id)arg2;
- (id)defaultDevice;
- (id)selectedConfigurationDevice;
- (id)selectedConfigurationLayout;
- (id)selectedConfigurationRenderMode;
- (id)selectedConfigurationOrientation;
- (id)selectedConfigurationAppearance;
- (id)sizeClassFieldsFont;
- (id)labelFont;
- (id)labelColor;
- (id)customizationModeBackgroundColor;
- (id)defaultBackgroundColor;
- (id)_layoutGroupButtons;
- (id)_orientationGroupButtons;
- (id)_renderModeGroupButtons;
- (id)_appearanceGroupButtons;
- (id)_deviceGroupButtonsForBranchMode:(BOOL)arg1;
- (void)_selectButtonsMatchingSelectedConfiguration;
- (id)applyDownstreamSelectionsToConfiguration:(id)arg1;
- (void)_configureGroupViewControllers;
- (void)_updateGroupsStartingFromLayouts;
- (void)_updateGroupsStartingFromOrientations;
- (void)_updateGroupsStartingFromRenderModes;
- (void)_updateGroupsStartingFromAppearances;
- (void)_updateGroupsStartingFromDevicesInCustomizationMode:(BOOL)arg1;
- (BOOL)isShowingLayoutsGroup;
- (BOOL)isShowingOrientationsGroup;
- (BOOL)isShowingRenderModeGroup;
- (BOOL)isShowingAppearancesGroup;
- (BOOL)isShowingDevicesGroup;
- (void)_removeGroupViewController:(id)arg1;
- (void)_addGroupViewController:(id)arg1;
- (void)_configureBar;
- (void)_relayoutStacksAsNeeded;
- (void)primitiveInvalidate;
- (void)viewWillAppear;
- (id)devicePickerView;
- (void)_resetForDocumentUsesConfigurationsChanged;
- (void)_createDeviceImageGenerationContext;
- (id)_deviceConfigurationsForDocument;
- (id)initWithDocument:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

