//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@protocol IBDocumentEditorLoadingBlockingEventViewDelegate;

@interface IBDocumentEditorLoadingBlockingEventView : NSView
{
    id <IBDocumentEditorLoadingBlockingEventViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <IBDocumentEditorLoadingBlockingEventViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)scrollWheel:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

