//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface IBEditedMenu : NSObject
{
    BOOL _isTopLevelInMenuBar;
    BOOL _representsMainMenuOrDescendantOfMainMenu;
    NSString *_title;
    NSArray *_itemArray;
}

@property(nonatomic) BOOL representsMainMenuOrDescendantOfMainMenu; // @synthesize representsMainMenuOrDescendantOfMainMenu=_representsMainMenuOrDescendantOfMainMenu;
@property(nonatomic) BOOL isTopLevelInMenuBar; // @synthesize isTopLevelInMenuBar=_isTopLevelInMenuBar;
@property(copy, nonatomic) NSArray *itemArray; // @synthesize itemArray=_itemArray;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2 shouldLogTree:(BOOL)arg3;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
- (id)description;

@end

