//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class NSCollectionView, NSCollectionViewLayout, NSIndexPath;

@protocol IBICCatalogOverviewLayoutDelegate <NSObject>
- (double)collectionView:(NSCollectionView *)arg1 layout:(NSCollectionViewLayout *)arg2 heightForItemAtIndexPath:(NSIndexPath *)arg3 forWidth:(double)arg4;
@end

