//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSClipView.h>

@protocol IBViewDragDelegate;

@interface IBICDetailClipView : NSClipView
{
    id <IBViewDragDelegate> _delegate;
}

+ (void)initialize;
@property(nonatomic) __weak id <IBViewDragDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;

@end

