//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBICAbstractCollectionCapsule.h>

@interface IBICStickerPackCapsule : IBICAbstractCollectionCapsule
{
}

- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (BOOL)getAssetIdentifier:(id *)arg1 andDropLocation:(long long *)arg2 nearestPoint:(struct CGPoint)arg3 allowingDropOnto:(BOOL)arg4;

@end

