//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IBFoundation/IBICStickersCatalog.h>

@interface IBICStickersCatalog (DisplayAdditions)
- (id)updateSelectionRelativeIDsForSelectionRestoration:(id)arg1;
- (id)updatePreviousSourceItemIDsForSelectionRestoration:(id)arg1;
- (BOOL)shouldAvoidDeletingChild:(id)arg1;
@end

