//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IBFoundation/IBICAppIconSet.h>

@interface IBICAppIconSet (DisplayAdditions)
- (void)setIbInspectedPreRendered:(BOOL)arg1;
- (BOOL)ibInspectedPreRendered;
- (id)includedAttributesInspectorSlicesForChild:(id)arg1;
@end

