//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IBInsecureDocumentErrorHandler : NSObject
{
}

+ (id)errorForURL:(id)arg1;
+ (BOOL)isAllowedToOpenURL:(id)arg1;

@end

