//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IBLiveViewsTrackedBuildOperation;

@interface IBLiveViewsTwoEntryBuildQueue : NSObject
{
    IBLiveViewsTrackedBuildOperation *_activeTrackedBuildOperation;
    IBLiveViewsTrackedBuildOperation *_pendingTrackedBuildOperation;
}

@property(retain, nonatomic) IBLiveViewsTrackedBuildOperation *pendingTrackedBuildOperation; // @synthesize pendingTrackedBuildOperation=_pendingTrackedBuildOperation;
@property(retain, nonatomic) IBLiveViewsTrackedBuildOperation *activeTrackedBuildOperation; // @synthesize activeTrackedBuildOperation=_activeTrackedBuildOperation;
- (void).cxx_destruct;

@end

