//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class IBLiveViewsBundle, NSError, NSObject;
@protocol IBLiveViewsBundleObserverEnvironment;

@protocol IBLiveViewsBundleObserver <NSObject>
- (NSObject<IBLiveViewsBundleObserverEnvironment> *)environmentForObservingLiveViewsBundle:(IBLiveViewsBundle *)arg1;
- (void)liveViewsBundleWillInvalidate:(IBLiveViewsBundle *)arg1;
- (void)liveViewsBundleDidFinishBuilding:(IBLiveViewsBundle *)arg1 error:(NSError *)arg2;
- (void)liveViewsBundleNeedsToBeRebuilt:(IBLiveViewsBundle *)arg1;
@end

