//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/DVTOutlineViewDelegate-Protocol.h>

@class IBOutlineView, NSEvent, NSOutlineView;

@protocol IBOutlineViewDelegate <DVTOutlineViewDelegate>
- (BOOL)outlineView:(NSOutlineView *)arg1 isGroupHeaderItem:(id)arg2;

@optional
- (void)outlineView:(IBOutlineView *)arg1 handleRightOrControlLeftDrag:(NSEvent *)arg2;
- (void)outlineView:(IBOutlineView *)arg1 handleRightOrControlLeftClick:(NSEvent *)arg2;
- (void)outlineView:(IBOutlineView *)arg1 didHandleMouseDown:(NSEvent *)arg2;
- (void)outlineView:(IBOutlineView *)arg1 handleMouseDown:(NSEvent *)arg2;
@end

