//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IBMemberConfiguration, NSString;

@interface IBPropertyConfigurationLocation : NSObject
{
    NSString *_property;
    IBMemberConfiguration *_configuration;
}

+ (id)locationWithProperty:(id)arg1 configuration:(id)arg2;
@property(readonly) IBMemberConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly) NSString *property; // @synthesize property=_property;
- (void).cxx_destruct;
- (id)description;
- (void)setEvaluatedValue:(id)arg1 forMember:(id)arg2;
- (void)setValue:(id)arg1 forMember:(id)arg2;
- (id)effectiveValueForMember:(id)arg1;
- (id)explicitValueForMember:(id)arg1;
- (id)configurationPropertyStorageForMember:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToPropertyConfigurationLocation:(id)arg1;
- (unsigned long long)hash;
- (id)initWithProperty:(id)arg1 configuration:(id)arg2;

@end

