//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEInterfaceBuilderKit/IBDocumentArchiving-Protocol.h>
#import <IDEInterfaceBuilderKit/IBStoryboardSceneExitPlaceholder-Protocol.h>

@class IBTargetRuntime, NSString;

@interface IBSceneExitPlaceholder : NSObject <IBStoryboardSceneExitPlaceholder, IBDocumentArchiving>
{
    IBTargetRuntime *_targetRuntime;
}

+ (id)instantiateWithDocumentUnarchiver:(id)arg1;
- (void).cxx_destruct;
@property(retain) IBTargetRuntime *targetRuntime; // @synthesize targetRuntime=_targetRuntime;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTargetRuntime:(id)arg1;
- (BOOL)ibIsCopyableGivenSelection:(id)arg1;
- (BOOL)ibNeedsToBeArchived;
- (BOOL)ibIsInspectorSliceApplicable:(id)arg1 forCategory:(id)arg2;
- (BOOL)ibTopLevelSceneObjectWantsInclusionInCompiledStoryboard;
- (void)unarchiveWithDocumentUnarchiver:(id)arg1;
- (void)archiveWithDocumentArchiver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

