//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTSourceModelItem, NSString;

@interface IBSourceModelItemInfo : NSObject
{
    DVTSourceModelItem *_item;
    NSString *_type;
    NSString *_name;
    NSString *_collectionType;
    long long _relationshipType;
    unsigned long long _annotationKind;
    struct _NSRange _range;
}

+ (id)sourceModelInfoForSourceModelItem:(id)arg1 inSourceModel:(id)arg2 matchingAnnotationKindMask:(unsigned long long)arg3;
+ (id)sourceModelInfoForBindingObjCPropertyContextItem:(id)arg1 inSourceModel:(id)arg2;
+ (id)sourceModelInfoForBindingObjCInstanceVariableContextItem:(id)arg1 inSourceModel:(id)arg2;
+ (id)firstSourceModelItemOccurringBeforeRange:(struct _NSRange)arg1 fromSourceModelItem:(id)arg2 inSourceModel:(id)arg3;
+ (id)extendedTypeNameFromSourceModelItem:(id)arg1 inSourceModel:(id)arg2 range:(struct _NSRange *)arg3;
+ (id)sourceModelInfoForObjCInstanceVariableOutletContextItem:(id)arg1 inSourceModel:(id)arg2;
+ (id)sourceModelInfoForObjCPropertyOutletContextItem:(id)arg1 inSourceModel:(id)arg2;
+ (id)sourceModelInfoForObjCInstanceVariableOutletCollectionContextItem:(id)arg1 inSourceModel:(id)arg2;
+ (id)sourceModelInfoForObjCPropertyOutletCollectionContextItem:(id)arg1 inSourceModel:(id)arg2;
+ (id)sourceModelInfoForSegueActionContextItem:(id)arg1 inSourceModel:(id)arg2 languageSpecification:(id)arg3;
+ (BOOL)sourceModelItemHasDescendantIBSegueActionItem:(id)arg1 inSourceModel:(id)arg2;
+ (id)sourceModelInfoForActionContextItem:(id)arg1 inSourceModel:(id)arg2 languageSpecification:(id)arg3;
+ (BOOL)sourceModelItemHasDescendantIBActionItem:(id)arg1 inSourceModel:(id)arg2;
- (void).cxx_destruct;
@property unsigned long long annotationKind; // @synthesize annotationKind=_annotationKind;
@property long long relationshipType; // @synthesize relationshipType=_relationshipType;
@property(retain) NSString *collectionType; // @synthesize collectionType=_collectionType;
@property(retain) NSString *name; // @synthesize name=_name;
@property(retain) NSString *type; // @synthesize type=_type;
@property struct _NSRange range; // @synthesize range=_range;
@property(retain) DVTSourceModelItem *item; // @synthesize item=_item;
- (id)initWithSourceModelItem:(id)arg1 name:(id)arg2 type:(id)arg3 collectionType:(id)arg4 range:(struct _NSRange)arg5 relationshipType:(long long)arg6;

@end

