//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBDocumentSelectionGeniusResultsFinder.h>

@interface IBStoryboardSelectionGeniusResultsFinder : IBDocumentSelectionGeniusResultsFinder
{
}

- (BOOL)_getUpdateGeniusResultsPhase1Block:(CDUnknownBlockType *)arg1 phase2Block:(CDUnknownBlockType *)arg2 phase3Block:(CDUnknownBlockType *)arg3;
- (id)editorDocument;

@end

