//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IBMemberID, NSString;

@interface IBStructureRepresentingConnection : NSObject
{
    IBMemberID *_sourceOID;
    IBMemberID *_destinationOID;
    NSString *_label;
}

- (void).cxx_destruct;
@property(copy) NSString *label; // @synthesize label=_label;
@property(copy) IBMemberID *destinationOID; // @synthesize destinationOID=_destinationOID;
@property(copy) IBMemberID *sourceOID; // @synthesize sourceOID=_sourceOID;
- (id)description;
- (id)initWithSourceOID:(id)arg1 destinationOID:(id)arg2 label:(id)arg3;

@end

