//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBEmbeddingPolicy.h>

@class NSView;

@interface IBSubviewEmbeddingPolicy : IBEmbeddingPolicy
{
    NSView *_templateContainer;
}

@property(retain) NSView *templateContainer; // @synthesize templateContainer=_templateContainer;
- (void).cxx_destruct;
- (BOOL)canEmbedObjects:(id)arg1 fromDocument:(id)arg2;
- (id)embedObjects:(id)arg1 fromDocument:(id)arg2 context:(id)arg3;
- (void)moveViews:(id)arg1 intoDesignableContentView:(id)arg2 ofView:(id)arg3 withRootContainer:(id)arg4 forDocument:(id)arg5;
- (id)initWithRepresentedExtension:(id)arg1;

@end

