//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBSourceCodeParser.h>

@class NSString;

@interface IBSwiftParser : IBSourceCodeParser
{
    NSString *_parserIdentifier;
}

+ (id)secondaryParsableFileTypeIdentifiers;
+ (id)primaryParsableFileTypeIdentifiers;
+ (id)supportedFileExtensions;
- (void).cxx_destruct;
@property(retain) NSString *parserIdentifier; // @synthesize parserIdentifier=_parserIdentifier;
- (id)parseData:(id)arg1 fromFile:(id)arg2 withToolchainIdentifiers:(id)arg3 errors:(id *)arg4;
- (id)partialDescriptionsForDocumentAtPath:(id)arg1 withContents:(id)arg2 toolchainIdentifiers:(id)arg3;
- (void)enumerateMembersOfClass:(CDStruct_68506f87)arg1 inDocumentWithContents:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)senderTypeOfClassMember:(CDStruct_68506f87)arg1;
- (void)enumerateMembersOfClassInDocumentWithIdentifier:(id)arg1 withContents:(id)arg2 toolchainIdentifiers:(id)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (void)enumerateClassesInDocumentAtPath:(id)arg1 withContents:(id)arg2 toolchainIdentifiers:(id)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (id)init;

@end

