//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class IBXMLDecoder, NSString;

@protocol IBXMLDecoderDelegate <NSObject>
- (Class)xmlDecoder:(IBXMLDecoder *)arg1 overridingClassForClassName:(NSString *)arg2;
- (Class)xmlDecoder:(IBXMLDecoder *)arg1 cannotDecodeObjectOfClassName:(NSString *)arg2;
@end

