//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class NSString;

@protocol IDEGeniusResultNavigableRepresentedObject <NSObject>
- (NSString *)geniusResult_identifierForGeniusCategory;
@end

