//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/NSObject-Protocol.h>

@class NSString;
@protocol NSCoding;

@protocol IDENavigableItemArchivableRepresentationSupport <NSObject>

@optional
- (NSString *)navigableItem_archivingIdentifer;
- (unsigned long long)navigableItem_indexOfRepresentedObjectForIdentifier:(id <NSCoding>)arg1 inRelationshipKeyPath:(NSString *)arg2;
- (id <NSCoding>)navigableItem_identifierForRepresentedObjectAtIndex:(unsigned long long)arg1 inRelationshipKeyPath:(NSString *)arg2;
@end

