//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@interface NSPopUpButton (IBPopUpButtonAdditions)
- (void)selectItemWithRepresentedObject:(id)arg1;
- (long long)tagOfSelectedItem;
@end

