//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MLRecipeKit/_TtC11MLRecipeKit19DroppableTargetView.h>

@class MISSING_TYPE;

@interface _TtC11MLRecipeKit14DropTargetView : _TtC11MLRecipeKit19DroppableTargetView
{
    MISSING_TYPE *promptField;
    MISSING_TYPE *borderView;
    MISSING_TYPE *imageView;
    MISSING_TYPE *prompt;
    MISSING_TYPE *image;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

