//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DVT_VMUTaskThreadStates : NSObject
{
    unsigned int _threadCount;
    unsigned int _threadStateSize;
    void *_threadStates;
    unsigned long long *_stackPointers;
}

@property(readonly, nonatomic) unsigned int threadStateSize; // @synthesize threadStateSize=_threadStateSize;
@property(readonly, nonatomic) unsigned int threadCount; // @synthesize threadCount=_threadCount;
- (unsigned long long)stackPointerForThreadNum:(unsigned int)arg1;
- (void *)threadStateForThreadNum:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithPid:(int)arg1 task:(unsigned int)arg2;

@end

