//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC15XCSourceControl33XCSourceControlHostRequestContext : NSObject
{
    // Error parsing type: , name: context
    // Error parsing type: , name: account
    // Error parsing type: , name: executor
    // Error parsing type: , name: endpointURL
}

- (void).cxx_destruct;
- (id)init;

@end

