//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSourceControl/_TtC15XCSourceControl33XCSourceControlHostRequestContext.h>

@interface _TtC15XCSourceControl48XCSourceControlHostRequestMultipartUploadContext : _TtC15XCSourceControl33XCSourceControlHostRequestContext
{
    // Error parsing type: , name: fileURLs
    // Error parsing type: , name: boundary
}

- (void).cxx_destruct;

@end

