//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCSourceControl/XCSourceControlHostTokenAuthentication.h>

@interface XCSourceControlHostPrivateTokenAuthentication : XCSourceControlHostTokenAuthentication
{
}

+ (BOOL)supportsSecureCoding;
+ (id)name;
- (id)httpAuthorizationValue;
- (id)httpAuthorizationType;

@end

