//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderEnumValue.h>

@class NSString;

@interface IDEIntentBuilderEnumValue (EditorAdditions)
+ (id)enumValueFromPasteboardWithParentEnum:(id)arg1;
+ (BOOL)canPasteFromPasteboardWithParentEnum:(id)arg1;
+ (id)keyPathsForValuesAffectingRemovable;
+ (id)keyPathsForValuesAffectingEditable;
+ (id)keyPathsForValuesAffectingSynonymsDisclosureViewTitle;
- (void)copyToPasteboard;
@property(readonly, getter=isDisplayNameEditable) BOOL displayNameEditable;
@property(readonly, getter=isEnabled) BOOL enabled;
@property(readonly, getter=isRemovable) BOOL removable;
@property(readonly, getter=isEditable) BOOL editable;
@property(readonly, copy) NSString *synonymsDisclosureViewTitle;
@property(readonly) BOOL canAddSynonyms;
@end

