//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEIntentBuilderCore/IDEIntentBuilderIntentParameterResolutionReason.h>

@interface IDEIntentBuilderIntentParameterResolutionReason (EditorAdditions)
@property(readonly, getter=isCodeEnabled) BOOL codeEnabled;
@property(readonly, getter=isEnabled) BOOL enabled;
@property(readonly, getter=isCodeEditable) BOOL codeEditable;
@property(readonly, getter=isEditable) BOOL editable;
@property(readonly, getter=isRemovable) BOOL removable;
@end

