//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSMenu.h>

@interface NSMenu (IDEIntentBuilderEditor)
- (void)_IDEIntentBuilderEditor_selectPropertySubMenuItemClicked:(id)arg1;
- (void)IDEIntentBuilderEditor_updateWithSupportedTypes:(id)arg1 visibleTypes:(unsigned long long)arg2 actionTarget:(id)arg3;
@end

