//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit27SigningEditorViewController.h>

#import <IDEKit/IDESigningEditorCapabilityEditingItemChangeExistenceProtocol-Protocol.h>

@interface _TtC6IDEKit27SigningEditorViewController (IDEKit2) <IDESigningEditorCapabilityEditingItemChangeExistenceProtocol>
- (void)addCapabilityItemWithIdentifiers:(id)arg1;
@end

