//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@interface IDEAttributedStringScrollView : NSScrollView
{
}

- (void)scrollWheel:(id)arg1;

@end

