//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEBlueprintMenuBuilder : NSObject
{
}

+ (id)blueprintMenuForBlueprintProviders:(id)arg1 blueprintEnabledBlock:(CDUnknownBlockType)arg2 target:(id)arg3 selector:(SEL)arg4;
+ (id)menuImageForImage:(id)arg1;

@end

