//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEBatchFindWorkspaceLocationPredicate.h>

@interface IDEBatchFindWorkspaceLocationPredicate (UIAdditions)
+ (id)batchFindPredicateForNavigableItem:(id)arg1;
+ (id)containerItemsForNavigableItem:(id)arg1;
+ (unsigned long long)ruleEditorRowType;
+ (id)predicateFromClauseChoices:(id)arg1 subpredicates:(id)arg2;
+ (id)displayValueForRuleEditorClause:(id)arg1;
+ (id)followOnClausesForRuleEditorClause:(id)arg1;
+ (id)operandRuleEditorClause;
+ (id)isWithinPackageDependencyGroup;
+ (id)isWithinWorkspace;
+ (id)rootRuleEditorClause;
- (id)ruleEditorClauses;
- (id)displayValueForRuleEditorClause:(id)arg1;
@end

