//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEDistributionStepViewController.h>

@class NSButton, NSTextField;

@interface IDEDistributionSigningMethodStepViewController : IDEDistributionStepViewController
{
    NSTextField *_messageField;
    NSButton *_automaticRadio;
    NSButton *_manualRadio;
}

+ (BOOL)skipStepForContext:(id)arg1 assistantDirection:(long long)arg2;
- (void).cxx_destruct;
@property(retain) NSButton *manualRadio; // @synthesize manualRadio=_manualRadio;
@property(retain) NSButton *automaticRadio; // @synthesize automaticRadio=_automaticRadio;
@property(retain) NSTextField *messageField; // @synthesize messageField=_messageField;
- (id)helpID;
@property(nonatomic) BOOL useAutomatic;
- (id)title;
- (void)viewDidLoad;
- (id)appName;

@end

