//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSString, NSTextField;

@interface IDEDiagnosticsTabAdvisoryContentController : NSViewController
{
    NSTextField *messageField;
    NSString *_message;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

