//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEGaugeDocumentLocation.h>

@class NSImage;

@interface IDEGaugeDocumentLocation (IDEKitAdditions)
- (id)navigableItem_image;
- (id)navigableItem_name;
@property(retain) NSImage *displayImage;
@end

