//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEOpenQuicklyAlternateGroupResult.h>

@interface IDEOpenQuicklyAlternateGroupResult (DisplayAdditions)
- (id)generateImage;
@end

