//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class IDEAttributedStringControlParagraphStylePopoverController;

@protocol IDEParagraphStylePopoverControllerDelegate <NSObject>
- (void)paragraphStylePopoverControllerDidChangeAttributes:(IDEAttributedStringControlParagraphStylePopoverController *)arg1;
@end

