//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

#import <IDEKit/IDESigningEditorConfigurationDataSourceDelegate-Protocol.h>

@protocol IDESigningEditorBundleIdentifierDataSource;

@interface IDEProvisioningBundleIdentifierViewController : IDEViewController <IDESigningEditorConfigurationDataSourceDelegate>
{
    id <IDESigningEditorBundleIdentifierDataSource> _dataSource;
}

@property(retain, nonatomic) id <IDESigningEditorBundleIdentifierDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)willUpdateConfigurationScope:(id)arg1;
- (id)initWithDataSource:(id)arg1;

@end

