//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class DVTObservingToken, NSProgressIndicator, NSTextField;
@protocol IDEProvisioningSigningSelectionDataSource;

@interface IDEProvisioningRepairProgressIndicatorViewController : IDEViewController
{
    id <IDEProvisioningSigningSelectionDataSource> _dataSource;
    NSTextField *_busyReasonLabel;
    NSProgressIndicator *_busyIndicator;
    DVTObservingToken *_repairBusyReasonObserver;
}

@property(retain, nonatomic) DVTObservingToken *repairBusyReasonObserver; // @synthesize repairBusyReasonObserver=_repairBusyReasonObserver;
@property __weak NSProgressIndicator *busyIndicator; // @synthesize busyIndicator=_busyIndicator;
@property __weak NSTextField *busyReasonLabel; // @synthesize busyReasonLabel=_busyReasonLabel;
@property(readonly, nonatomic) id <IDEProvisioningSigningSelectionDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)startObservations;
- (void)viewDidLoad;
- (id)initWithDataSource:(id)arg1;

@end

