//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDENavigatorDataCell.h>

@class NSCell;

@interface IDERunSheetDataCell : IDENavigatorDataCell
{
    NSCell *_imageCell;
}

- (void).cxx_destruct;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

