//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class NSArray, NSSet, NSString;

@protocol IDETestContainer <NSObject>
@property(nonatomic, readonly) NSArray *arrangedSubtests;
@property(nonatomic, readonly) NSSet *subtests;
@property(nonatomic, readonly) BOOL canHaveSubtests;
@property(nonatomic, readonly) NSString *name;
@end

