//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC15XCBBuildService17OperationDelegate10TargetInfo : _TtCs12_SwiftObject
{
    MISSING_TYPE *id;
    MISSING_TYPE *hasStarted;
    MISSING_TYPE *upToDateTasks;
}

@end

