//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTStructuredLayoutKit/DVTLayoutView_ML.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC19IDEMLModelEditorKit42IDEMLModelViewerResizingCapsuleContentView : DVTLayoutView_ML
{
    MISSING_TYPE *subViewInset;
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutBottomUp;
- (void)awakeFromNib;

@end

