//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTWrapperView.h>

@class NSView;

__attribute__((visibility("hidden")))
@interface _TtC19IDEMLModelEditorKit49IDEMLModelViewerExperimentationCapsuleContentView : DVTWrapperView
{
    // Error parsing type: , name: customView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutBottomUp;
- (void)awakeFromNib;
@property(nonatomic) __weak NSView *customView; // @synthesize customView;

@end

