//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DebuggerLLDB/NSObject-Protocol.h>

@protocol DBGSBFileSpec, DBGSBLineEntry;

@protocol DBGSBCompileUnit <NSObject>
- (id <DBGSBLineEntry>)GetLineEntryAtIndex:(unsigned int)arg1;
- (unsigned int)FindLineEntryIndex:(unsigned int)arg1 line:(unsigned int)arg2 inline_file_spec:(id <DBGSBFileSpec>)arg3;
- (unsigned int)GetNumLineEntries;
- (_Bool)IsValid;
@end

