//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s22IDESwiftPackageSupport0aB15ModuleBlueprintCN.h"

#import <IDESwiftPackageSupportUI/IDEKeyDrivenNavigableItemRepresentedObject-Protocol.h>

@class NSImage, NSString;

@interface _$s22IDESwiftPackageSupport0aB15ModuleBlueprintCN (IDESwiftPackageSupportUI) <IDEKeyDrivenNavigableItemRepresentedObject>
+ (id)keyPathsForValuesAffectingNavigableItem_Name;
@property(nonatomic, readonly) NSImage *navigableItem_image;
@property(nonatomic, readonly) NSString *navigableItem_name;
@end

