//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _TtC24IDESwiftPackageSupportUI33IDESwiftPackageFolderIconProvider : NSObject
{
}

+ (id)overridingIconForFileType:(id)arg1;
- (id)init;

@end

