//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DebugHierarchyKit/DBGValue-Protocol.h>
#import <DebugHierarchyKit/DBGValueJSONSerialization-Protocol.h>

@class NSData, NSDictionary, NSImage, NSString;

@interface DBGImage : NSObject <DBGValueJSONSerialization, DBGValue>
{
    NSImage *_image;
    NSData *_imageData;
    struct __CFString *_imageType;
    NSDictionary *_metadata;
}

+ (id)withImageData:(id)arg1 type:(struct __CFString *)arg2 metadata:(id)arg3;
+ (id)valueWithEncodedValue:(id)arg1 format:(id)arg2 error:(id *)arg3;
@property(readonly) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(readonly) struct __CFString *imageType; // @synthesize imageType=_imageType;
@property(readonly) NSData *imageData; // @synthesize imageData=_imageData;
- (void).cxx_destruct;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (id)objectValue;
@property(readonly) NSImage *image; // @synthesize image=_image;
- (id)initWithImageData:(id)arg1 type:(struct __CFString *)arg2 metadata:(id)arg3;
- (id)JSONCompatibleRepresentation;

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

