//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DebugHierarchyKit/NSObject-Protocol.h>

@class NSString;

@protocol DBGValueJSONSerialization <NSObject>
+ (id)valueWithEncodedValue:(id)arg1 format:(NSString *)arg2 error:(id *)arg3;
- (id)JSONCompatibleRepresentation;
@end

