//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTKit/DVTOutlineView.h>

#import <IDESpriteKitParticleEditor/NSUserInterfaceValidations-Protocol.h>

@class NSTrackingArea, SKOutlineViewHoverInfo;

@interface SKOutlineView : DVTOutlineView <NSUserInterfaceValidations>
{
    BOOL _mouseOver;
    NSTrackingArea *_trackingArea;
    SKOutlineViewHoverInfo *_hoverInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SKOutlineViewHoverInfo *hoverInfo; // @synthesize hoverInfo=_hoverInfo;
- (void)_updateHoverInfoWithEvent:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)dealloc;
- (void)awakeFromNib;

@end

