//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SKSnapLine : NSObject
{
    unsigned long long _plane;
    double _value;
}

+ (id)snapLineOnPlane:(unsigned long long)arg1 withValue:(double)arg2;
@property(nonatomic) double value; // @synthesize value=_value;
@property(nonatomic) unsigned long long plane; // @synthesize plane=_plane;
- (id)initOnPlane:(unsigned long long)arg1 withValue:(double)arg2;

@end

