//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV19MLModelFormatEditor37CoreML_Specification_ModelDescriptionP33_5A2836906837F19FFC245DCC19FBFF3113_StorageClass : _TtCs12_SwiftObject
{
    MISSING_TYPE *_input;
    MISSING_TYPE *_output;
    MISSING_TYPE *_predictedFeatureName;
    MISSING_TYPE *_predictedProbabilitiesName;
    MISSING_TYPE *_metadata;
}

@end

