//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV19MLModelFormatEditor48CoreML_Specification_KNearestNeighborsClassifierP33_A1E503B14E00A46BEF017E94E83D922313_StorageClass : _TtCs12_SwiftObject
{
    MISSING_TYPE *_nearestNeighborsIndex;
    MISSING_TYPE *_numberOfNeighbors;
    MISSING_TYPE *_classLabels;
    MISSING_TYPE *_defaultClassLabel;
    MISSING_TYPE *_weightingScheme;
}

@end

