//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV19MLModelFormatEditor27CoreML_Specification_KernelP33_D3D893416E082CE8CA8EB70EF140C2DD13_StorageClass : _TtCs12_SwiftObject
{
    MISSING_TYPE *_kernel;
}

@end

