//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCV19MLModelFormatEditor48CoreML_Specification_KNearestNeighborsClassifierP33_05E077BDFF5CB418767CCEC107663E7A13_StorageClass : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _dimensionality
    // Error parsing type: , name: _floatSamples
    // Error parsing type: , name: _k
    // Error parsing type: , name: _classLabels
}

@end

