//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCV19MLModelFormatEditor34CoreML_Specification_OneHotEncoderP33_5D889462E4676DE0FB2E19C8051A7BC413_StorageClass : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _categoryType
    // Error parsing type: , name: _outputSparse
    // Error parsing type: , name: _handleUnknown
}

@end

