//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTPortal/_TtC9DVTPortal20DeveloperAPIResource.h>

@class MISSING_TYPE;

@interface _TtC9DVTPortal30DeveloperAPIBundleIDCapability : _TtC9DVTPortal20DeveloperAPIResource
{
    MISSING_TYPE *enabled;
    MISSING_TYPE *capability;
    MISSING_TYPE *parentBundleID;
}

- (void).cxx_destruct;

@end

