//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTPortal/DVTLegacyPortalService.h>

@interface DVTPortalJoinTeamService : DVTLegacyPortalService
{
}

+ (id)joinServiceForTeam:(id)arg1 clientName:(id)arg2 clientHardwareUUID:(id)arg3 certificateSigningRequest:(id)arg4;

@end

