//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTPortalServerCertificate;

@interface DVTPortalServerCSR : NSObject
{
    DVTPortalServerCertificate *_certificate;
}

@property(readonly, copy, nonatomic) DVTPortalServerCertificate *certificate; // @synthesize certificate=_certificate;
- (void).cxx_destruct;

@end

