//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTSigningCertificate.h>

@class DVTPortalCertificateType;

@interface DVTSigningCertificate (DVTPortalAdditions)
@property(readonly, nonatomic) DVTPortalCertificateType *portalCertificateType;
@end

