//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTPlistModel, DVTPlistNode, DVTPlistStructureDefinition;

@protocol DVTPlistDocumentProtocol
@property(retain) DVTPlistStructureDefinition *plistStructureDefinition;
- (BOOL)isReadOnly;
- (void)revealNode:(DVTPlistNode *)arg1;
- (void)propertyListChanged:(DVTPlistNode *)arg1;
- (DVTPlistModel *)model;
- (DVTPlistNode *)plist;
@end

