//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DevToolsCore/PBXAppleScriptBuildPhase.h>

@interface PBXAppleScriptBuildPhase (Xcode3BuildPhaseAdditions)
- (id)_xcode3_fileTypeForDisplay;
@end

