//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Xcode3UI/Xcode3FileBuildPhaseViewController.h>

@class DVTPopUpButtonCell, Xcode3AddFrameworksController;

@interface Xcode3FrameworksBuildPhaseViewController : Xcode3FileBuildPhaseViewController
{
    DVTPopUpButtonCell *_roleCell;
    Xcode3AddFrameworksController *_addFrameworksController;
}

- (void).cxx_destruct;
- (id)_filterPredicate;
- (id)footerLabel;
- (BOOL)_displayFullPath;
- (void)configureAddFrameworksController:(id)arg1;
- (void)addItems:(id)arg1;
- (BOOL)_acceptDrop:(id)arg1 onGroup:(id)arg2 proposedRow:(unsigned long long)arg3;
- (BOOL)supportsMacCatalyst;
- (BOOL)_addItems:(id)arg1 atRow:(unsigned long long)arg2;
- (void)_setFrameworkRole:(id)arg1;
- (id)_objectValueForRoleColumnOfBuildFile:(id)arg1;
- (id)_dataCellForRoleOfBuildFile:(id)arg1;
- (id)_titleOfRoleColumn;
- (BOOL)_canSetRole;
- (void)viewDidInstall;
- (void)primitiveInvalidate;

@end

