//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Xcode3UI/Xcode3InfoEditorProjectItemNameProvider.h>

@class IDEContainerQuery;

@interface Xcode3InfoEditorIconNameProvider : Xcode3InfoEditorProjectItemNameProvider
{
    IDEContainerQuery *_assetCatalogQuery;
}

+ (id)keyPathsForValuesAffectingListContents;
- (void).cxx_destruct;
@property(readonly) IDEContainerQuery *assetCatalogQuery; // @synthesize assetCatalogQuery=_assetCatalogQuery;
- (id)listContents;
- (void)primitiveInvalidate;
- (id)initWithBlueprint:(id)arg1 workspace:(id)arg2;

@end

