//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTSourceControl/DVTSourceControlVisualLogItem.h>

@interface _DVTSourceControlUnversionedVisualLogItem : DVTSourceControlVisualLogItem
{
}

- (BOOL)isEqual:(id)arg1;
- (BOOL)isComplete;
- (BOOL)isUnversionedLogItem;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)_init;
- (id)init;

@end

