//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTSourceControl/DVTSourceControlXPCResultType.h>

@class DVTSourceControlRevision, MISSING_TYPE;

@interface DVTSourceControlConflictResultType : DVTSourceControlXPCResultType
{
    MISSING_TYPE *localRevision;
    MISSING_TYPE *upstreamRevision;
    MISSING_TYPE *ancestorRevision;
}

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(void *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithLocalRevision:(id)arg1 upstreamRevision:(id)arg2 ancestorRevision:(id)arg3 error:(id)arg4;
- (id)initWithError:(id)arg1;
@property(nonatomic, readonly) DVTSourceControlRevision *ancestorRevision; // @synthesize ancestorRevision;
@property(nonatomic, readonly) DVTSourceControlRevision *upstreamRevision; // @synthesize upstreamRevision;
@property(nonatomic, readonly) DVTSourceControlRevision *localRevision; // @synthesize localRevision;

@end

