//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray;

@protocol DVTSourceControlWorkingCopyScannerProtocol
- (void)scanFolderPaths:(NSArray *)arg1 traversingUp:(BOOL)arg2 ignoringFolders:(NSArray *)arg3 completionBlock:(void (^)(DVTSourceControlURLsResultType *))arg4;
@end

