//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GLToolsExpert/DYGLExpertFinding.h>

@interface DYGLExpertFindingPercentOfFrame : DYGLExpertFinding
{
    float _percentOfFrame;
    unsigned int _whichSlowest;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) unsigned int whichSlowest; // @synthesize whichSlowest=_whichSlowest;
@property(nonatomic) float percentOfFrame; // @synthesize percentOfFrame=_percentOfFrame;
- (unsigned int)urgency;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

