//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDESourceControlUI/SMSourceBufferProvider-Protocol.h>

@class MISSING_TYPE;

@interface _TtC18IDESourceControlUI25ActivityHighlighterBuffer : NSObject <SMSourceBufferProvider>
{
    MISSING_TYPE *lang;
    MISSING_TYPE *contents;
}

- (void).cxx_destruct;
- (id)init;
- (void)scheduleLazyInvalidationForRange:(struct _NSRange)arg1;
- (unsigned long long)leadingWhitespacePositionsForLine:(unsigned long long)arg1;
- (struct _NSRange)lineRangeForCharacterRange:(struct _NSRange)arg1;
- (struct _NSRange)characterRangeForLineRange:(struct _NSRange)arg1;
- (unsigned long long)length;
- (id)string;
- (id)language;

@end

