//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC18IDESourceControlUI19FileMergeDataSource : NSObject
{
    MISSING_TYPE *workingCopy;
    MISSING_TYPE *primaryURL;
    MISSING_TYPE *secondaryURL;
    MISSING_TYPE *ancestorURL;
    MISSING_TYPE *mergeURL;
}

- (void).cxx_destruct;
- (id)init;
- (id)documentForAncestorDocumentLocation:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)documentForSecondaryDocumentLocation:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)documentForPrimaryDocumentLocation:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;

@end

