//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class DVTBorderedView, DVTGradientImageButton, DVTTableView, IDEControlGroup, MISSING_TYPE, NSButton, NSString, NSTextField;

@interface _TtC18IDESourceControlUI38SourceControlPrefsSystemPaneController : IDEViewController
{
    MISSING_TYPE *authorNameField;
    MISSING_TYPE *authorEmailField;
    MISSING_TYPE *authorNameLabel;
    MISSING_TYPE *authorEmailLabel;
    MISSING_TYPE *ignoredFilesBorderedView;
    MISSING_TYPE *ignoredFilesTable;
    MISSING_TYPE *ignoredFilesControlGroup;
    MISSING_TYPE *ignoredFilesControlGroupBorderedView;
    MISSING_TYPE *ignoredFilesAddButton;
    MISSING_TYPE *ignoredFilesRemoveButton;
    MISSING_TYPE *optionsLabel;
    MISSING_TYPE *rebaseOptionButton;
    MISSING_TYPE *displayMergeOptionButton;
    MISSING_TYPE *doneLoadingAuthor;
    MISSING_TYPE *doneLoadingIgnoredFiles;
    MISSING_TYPE *doneLoadingRebaseState;
    MISSING_TYPE *system;
    MISSING_TYPE *ignoredFiles;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) BOOL showMergeCommits;
- (void)updateRebaseState:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)updateObjectValue:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)removeFile:(id)arg1;
- (void)addFile:(id)arg1;
- (void)updateAuthor:(id)arg1;
- (void)loadView;
@property(nonatomic, readonly) NSString *nibName;
@property(nonatomic) __weak NSButton *displayMergeOptionButton; // @synthesize displayMergeOptionButton;
@property(nonatomic) __weak NSButton *rebaseOptionButton; // @synthesize rebaseOptionButton;
@property(nonatomic) __weak NSTextField *optionsLabel; // @synthesize optionsLabel;
@property(nonatomic) __weak DVTGradientImageButton *ignoredFilesRemoveButton; // @synthesize ignoredFilesRemoveButton;
@property(nonatomic) __weak DVTGradientImageButton *ignoredFilesAddButton; // @synthesize ignoredFilesAddButton;
@property(nonatomic) __weak DVTBorderedView *ignoredFilesControlGroupBorderedView; // @synthesize ignoredFilesControlGroupBorderedView;
@property(nonatomic) __weak IDEControlGroup *ignoredFilesControlGroup; // @synthesize ignoredFilesControlGroup;
@property(nonatomic) __weak DVTTableView *ignoredFilesTable; // @synthesize ignoredFilesTable;
@property(nonatomic) __weak DVTBorderedView *ignoredFilesBorderedView; // @synthesize ignoredFilesBorderedView;
@property(nonatomic) __weak NSTextField *authorEmailLabel; // @synthesize authorEmailLabel;
@property(nonatomic) __weak NSTextField *authorNameLabel; // @synthesize authorNameLabel;
@property(nonatomic) __weak NSTextField *authorEmailField; // @synthesize authorEmailField;
@property(nonatomic) __weak NSTextField *authorNameField; // @synthesize authorNameField;

@end

