//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTViewControllerKit/DVTViewController.h>

@class DVTSourceControlWorkingCopy, NSArray, NSPopUpButton, NSString;
@protocol IDEOperationViewDelegate;

@interface _TtC18IDESourceControlUI56IDESourceControlSingleWorkingCopyOperationViewController : DVTViewController
{
    // Error parsing type: , name: workQueue
    // Error parsing type: , name: workingCopies
    // Error parsing type: , name: workingCopy
    // Error parsing type: , name: delegate
    // Error parsing type: , name: operation
    // Error parsing type: , name: workingCopyButton
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (void)willBeginSheet;
- (void)selectWorkingCopy:(id)arg1;
@property(nonatomic) __weak NSPopUpButton *workingCopyButton; // @synthesize workingCopyButton;
@property(nonatomic) __weak id <IDEOperationViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic, retain) DVTSourceControlWorkingCopy *workingCopy; // @synthesize workingCopy;
@property(nonatomic, copy) NSArray *workingCopies;
@property(nonatomic, copy) id context;
@property(nonatomic, readonly) double preferredViewHeight;
@property(nonatomic, readonly) NSString *nibName;

@end

