//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC18IDESourceControlUI24ApplyAutostashController : NSObject
{
    MISSING_TYPE *workingCopy;
    MISSING_TYPE *stash;
    MISSING_TYPE *completion;
    MISSING_TYPE *applyOperationOperation;
    MISSING_TYPE *deleteOperationOperation;
}

- (void).cxx_destruct;
- (id)init;

@end

