//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s15DVTSourceEditor0aB4ViewCN.h"

#import <IDESourceControlUI/_TtP18IDESourceControlUI35ActivitySourceEditorViewKeyBindings_-Protocol.h>

@class MISSING_TYPE;

@interface _TtC18IDESourceControlUI24ActivitySourceEditorView : _$s15DVTSourceEditor0aB4ViewCN <_TtP18IDESourceControlUI35ActivitySourceEditorViewKeyBindings_>
{
    MISSING_TYPE *imageTokenDisplay;
    MISSING_TYPE *desiredLineHeight;
    MISSING_TYPE *imageMarkdownRegExPattern;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

