//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDESourceControlUI/_TtC18IDESourceControlUI17WorkingCopyEditor.h>

#import <IDESourceControlUI/NSTouchBarDelegate-Protocol.h>

@interface _TtC18IDESourceControlUI17WorkingCopyEditor (IDESourceControlUI1) <NSTouchBarDelegate>
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (id)makeTouchBar;
@end

