//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class MISSING_TYPE, NSString, NSTableView, NSTextField, NSTextView;

@interface _TtC18IDESourceControlUI47IDESourceControlNetworkDebuggerWindowController : NSWindowController
{
    MISSING_TYPE *willCloseCallback;
    MISSING_TYPE *requestsTableView;
    MISSING_TYPE *requestURLField;
    MISSING_TYPE *requestHeaderField;
    MISSING_TYPE *requestBodyField;
    MISSING_TYPE *responseBodyField;
    MISSING_TYPE *logEntries;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)exportLog:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)resetLogState:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
@property(nonatomic, readonly) NSString *windowNibName;
@property(nonatomic, retain) NSTextView *responseBodyField; // @synthesize responseBodyField;
@property(nonatomic, retain) NSTextView *requestBodyField; // @synthesize requestBodyField;
@property(nonatomic, retain) NSTextView *requestHeaderField; // @synthesize requestHeaderField;
@property(nonatomic) __weak NSTextField *requestURLField; // @synthesize requestURLField;
@property(nonatomic) __weak NSTableView *requestsTableView; // @synthesize requestsTableView;
@property(nonatomic, copy) CDUnknownBlockType willCloseCallback;

@end

