//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE;

@interface _TtC18IDESourceControlUI31BannerBuildStatusViewController : NSViewController
{
    MISSING_TYPE *$__lazy_storage_$_overlayButton;
    MISSING_TYPE *$__lazy_storage_$_labelField;
    MISSING_TYPE *$__lazy_storage_$_statusImageView;
    MISSING_TYPE *size;
    MISSING_TYPE *containerView;
    MISSING_TYPE *pullRequest;
    MISSING_TYPE *operation;
    MISSING_TYPE *statusAnnotations;
    MISSING_TYPE *statusPopover;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showStatus:(id)arg1;
- (void)viewWillLayout;
- (void)loadView;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

