//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC18IDESourceControlUI9WebBridge : NSObject
{
    MISSING_TYPE *contentController;
    MISSING_TYPE *handler;
    MISSING_TYPE *receiverMap;
    MISSING_TYPE *domReady;
    MISSING_TYPE *deferredInvocations;
    MISSING_TYPE *webView;
}

- (void).cxx_destruct;
- (id)init;

@end

