//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, NSImageView, NSTextField;

@interface _TtC18IDESourceControlUI59PullRequestCurrentBranchNavigationPopoverItemViewController : NSViewController
{
    MISSING_TYPE *titleString;
    MISSING_TYPE *titleField;
    MISSING_TYPE *imageView;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) __weak NSImageView *imageView; // @synthesize imageView;
@property(nonatomic) __weak NSTextField *titleField; // @synthesize titleField;

@end

