//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC18IDESourceControlUI16ActivityTemplate : _TtCs12_SwiftObject
{
    MISSING_TYPE *name;
    MISSING_TYPE *rawTemplate;
    MISSING_TYPE *templater;
    MISSING_TYPE *ast;
}

@end

