//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTViewControllerKit/DVTViewController.h>

#import <IDESourceControlUI/IDEOperationViewController-Protocol.h>
#import <IDESourceControlUI/IDESourceControlMultipleOperationViewController-Protocol.h>

@class NSArray, NSPopUpButton, NSString;
@protocol IDEOperationViewDelegate;

@interface _TtC18IDESourceControlUI64IDESourceControlCreatePullCreateWorkingCopyChooserViewController : DVTViewController <IDESourceControlMultipleOperationViewController, IDEOperationViewController>
{
    // Error parsing type: , name: popUpButton
    // Error parsing type: , name: workspace
    // Error parsing type: , name: workingCopies
    // Error parsing type: , name: workQueue
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)primaryAction;
- (void)tearDownAction;
@property(nonatomic, retain) id <IDEOperationViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic, readonly) double preferredViewHeight;
@property(nonatomic, readonly) NSString *windowSubtitle;
@property(nonatomic, readonly) NSString *windowTitle;
@property(nonatomic, readonly) NSString *primaryButtonTitle;
@property(nonatomic, copy) NSArray *workingCopies;
@property(nonatomic) __weak NSPopUpButton *popUpButton; // @synthesize popUpButton;

@end

