//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC18IDESourceControlUI29SourceControlExplorableSource : NSObject
{
    // Error parsing type: , name: branchTrees
    // Error parsing type: , name: tagTrees
    // Error parsing type: , name: remoteTrees
    // Error parsing type: , name: synchronizationQueue
    // Error parsing type: , name: rootIdentifier
    // Error parsing type: , name: broadcaster
    // Error parsing type: , name: sourceControlWorkspace
    // Error parsing type: , name: workspace
    // Error parsing type: , name: didScanToken
    // Error parsing type: , name: cachedChildren
}

- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

