//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDESourceControlUI/NSObject-Protocol.h>

@class NSEvent;

@protocol _TtP18IDESourceControlUI45IDESourceControlRepositoriesTableViewDelegate_ <NSObject>
- (BOOL)handleMoveUpInTableView;
- (void)tableViewKeyDown:(NSEvent *)arg1;
- (void)doubleAction:(id)arg1;
@end

