//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDESourceControlUI/NSObject-Protocol.h>

@class DVTDocumentLocation, IDEComparisonEditor, IDEReviewFilesViewController;

@protocol IDEReviewFilesViewControllerDelegate <NSObject>

@optional
- (BOOL)shouldUpdateEditorHistory;
- (void)reviewFilesViewController:(IDEReviewFilesViewController *)arg1 didInstallComparisonEditor:(IDEComparisonEditor *)arg2;
- (void)willOpenDocumentLocation:(DVTDocumentLocation *)arg1 completionBlock:(void (^)(IDEEditorOpenSpecifier *, NSError *))arg2;
- (BOOL)enableDiffToggles;
@end

