//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEModelEditor/IDEDMModelObject-Protocol.h>

@protocol IDEDMSourceObject;

@protocol IDEDMModelRootObject <IDEDMModelObject>
- (void)removeTopLevelObject:(id <IDEDMSourceObject>)arg1;
@end

