//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEModelEditor/XDFillStyle.h>

@interface XDCompartmentGraphicFillStyle : XDFillStyle
{
}

+ (void)initialize;
- (void)drawGraphic:(id)arg1 inView:(id)arg2 usingFillType:(int)arg3;

@end

