//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class XDDiagramView;

@interface XDGraphicAuxiliaryStorage : NSObject
{
    id _graphic;
    XDDiagramView *_diagramView;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)diagramView;
- (void)_setDiagramView:(id)arg1;
- (id)graphic;
- (void)_setGraphic:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithGraphic:(id)arg1 diagramView:(id)arg2;

@end

