//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTDocumentLocation.h>

#import <IDEQuickLookEditor/NSSecureCoding-Protocol.h>

@class IDEQuickLookPage;

@interface IDEQuickLookDocumentLocation : DVTDocumentLocation <NSSecureCoding>
{
    IDEQuickLookPage *_page;
}

+ (BOOL)supportsSecureCoding;
+ (Class)classForKeyedUnarchiver;
- (void).cxx_destruct;
@property(readonly) IDEQuickLookPage *page; // @synthesize page=_page;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)initWithDocumentURL:(id)arg1 page:(id)arg2;
- (Class)classForKeyedArchiver;

@end

