//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DTTimelineInspectionDecorationContainer;
@protocol OS_dispatch_group;

__attribute__((visibility("hidden")))
@interface DTTimelineTileDrawingContent : NSObject
{
    struct CGImage *_renderedImage;
    DTTimelineInspectionDecorationContainer *_summary;
    NSObject<OS_dispatch_group> *_summaryGenerationGroup;
    shared_ptr_1f7ca383 _containerPtr;
}

@property(retain, nonatomic) NSObject<OS_dispatch_group> *summaryGenerationGroup; // @synthesize summaryGenerationGroup=_summaryGenerationGroup;
@property(retain, nonatomic) DTTimelineInspectionDecorationContainer *summary; // @synthesize summary=_summary;
@property(nonatomic) shared_ptr_1f7ca383 containerPtr; // @synthesize containerPtr=_containerPtr;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) struct CGImage *renderedImage;

@end

