//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DTTimelinePlaneLabelAreaResizingConfiguration : NSObject
{
    double _breakdownPosition;
    double _furtherIncreasePosition;
    double _furtherIncreaseRatio;
}

@property(nonatomic) double furtherIncreaseRatio; // @synthesize furtherIncreaseRatio=_furtherIncreaseRatio;
@property(nonatomic) double furtherIncreasePosition; // @synthesize furtherIncreasePosition=_furtherIncreasePosition;
@property(nonatomic) double breakdownPosition; // @synthesize breakdownPosition=_breakdownPosition;
- (BOOL)isEqual:(id)arg1;
- (id)initWithBreakdownPosition:(double)arg1 furtherIncreasePosition:(double)arg2 furtherIncreaseRatio:(double)arg3;

@end

