//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DTGraphKit/CALayoutManager-Protocol.h>

@class DTTimelineGroupPlane, NSString;

__attribute__((visibility("hidden")))
@interface DTTimelineGroupPlaneLayoutManager : NSObject <CALayoutManager>
{
    DTTimelineGroupPlane *_groupPlane;
}

- (void).cxx_destruct;
- (int)updateSubplaneLayoutAndMap:(unordered_map_b8b4eb21 *)arg1 offsetFromTop:(double)arg2;
- (struct CGRect)_frameForZOrderedPlane:(id)arg1 yOffet:(double)arg2;
- (id)planesUnderPoint:(struct CGPoint)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)initWithGroupPlane:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

