//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (UVObjCAdditions)
+ (id)uv_errorWithFormat:(id)arg1;
+ (id)uv_errorWithDescription:(id)arg1;
+ (id)uv_errorWithUserInfo:(id)arg1;
@end

