//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBAutolayoutPropertyInspectorProperty.h>

@class IBTouchBarItemPriorityEditingController;

@interface IBTouchBarItemPriorityInspectorProperty : IBAutolayoutPropertyInspectorProperty
{
}

- (void)setupRefreshTriggersAndConfigure;
- (id)makeEditingController;

// Remaining properties
@property(readonly, nonatomic) IBTouchBarItemPriorityEditingController *editingController; // @dynamic editingController;

@end

