//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC12SourceEditor13FoldingRibbon : _TtCs12_SwiftObject
{
    MISSING_TYPE *foldingController;
    MISSING_TYPE *marginWidth;
    MISSING_TYPE *backgroundView;
    MISSING_TYPE *ribbonContentView;
    MISSING_TYPE *expandedLayer;
    MISSING_TYPE *cachedLayers;
    MISSING_TYPE *consumerPriority;
    MISSING_TYPE *interaction;
}

@end

