//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class _TtC12SourceEditor25SourceEditorTextFindPanel;

@protocol _TtP12SourceEditor34SourceEditorTextFindPanelFieldType_
@property(nonatomic) struct NSEdgeInsets insets;
@property(nonatomic, copy) id textFindValue;
@property(nonatomic, retain) _TtC12SourceEditor25SourceEditorTextFindPanel *panel;
@end

