//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTAnalyticsClient/_TtC18DVTAnalyticsClient29AnalyticsMetricsAppIdentifier.h>

#import <DVTAnalyticsClient/DVTAnalyticsServiceURLComponentProviding-Protocol.h>

@class NSArray, NSDictionary;

@interface _TtC18DVTAnalyticsClient29AnalyticsMetricsAppIdentifier (DVTAnalyticsClient2) <DVTAnalyticsServiceURLComponentProviding>
@property(nonatomic, readonly) NSDictionary *parameters;
@property(nonatomic, readonly) NSArray *pathComponents;
@end

