//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTAnalyticsClient/DVTAnalyticsData.h>

@class MISSING_TYPE, NSArray;

@interface _TtC18DVTAnalyticsClient48AnalyticsDiskWritePointLogMetaStackFrameDataRoot : DVTAnalyticsData
{
    MISSING_TYPE *root;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSArray *root;

@end

