//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTAnalyticsClient/DVTAnalyticsServiceOption.h>

@interface DVTAnalyticsPointOSDistributionOption : DVTAnalyticsServiceOption
{
}

+ (id)distributionWithOSVersions:(id)arg1;

@end

