//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC17CoreDocumentation4LMDB11Transaction : _TtCs12_SwiftObject
{
    MISSING_TYPE *queue;
    MISSING_TYPE *opaquePointer;
    MISSING_TYPE *environment;
    MISSING_TYPE *parent;
    MISSING_TYPE *readOnly;
    MISSING_TYPE *_completed;
}

@end

