//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreDocumentation/_TtC17CoreDocumentation8Semantic.h>

@interface _TtC17CoreDocumentation5Learn : _TtC17CoreDocumentation8Semantic
{
    // Error parsing type: , name: originalMarkup
    // Error parsing type: , name: technology
    // Error parsing type: , name: hero
    // Error parsing type: , name: learningPaths
    // Error parsing type: , name: callToActionImage
}

@end

