//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreDocumentation/_TtC17CoreDocumentation6Markup.h>

@interface _TtC17CoreDocumentation12CustomInline : _TtC17CoreDocumentation6Markup
{
}

@end

