//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDESourceEditor/_TtC15IDESourceEditor16SourceCodeEditor.h>

@interface _TtC15IDESourceEditor16SourceCodeEditor (IDESourceEditor2)
- (void)disableAllEditorOptions;
- (void)toggleMinimapShown:(id)arg1;
@end

