//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC15IDESourceEditor10InlineDiff : _TtCs12_SwiftObject
{
    MISSING_TYPE *sourceEditorView;
    MISSING_TYPE *diffCoordinator;
    MISSING_TYPE *changeBar;
    MISSING_TYPE *diffSession;
    MISSING_TYPE *layersByIndex;
    MISSING_TYPE *viewsByIndex;
    MISSING_TYPE *changedViews;
    MISSING_TYPE *enqueuedDiffDescriptor;
    MISSING_TYPE *layoutInvalidated;
    MISSING_TYPE *contextInvalidated;
    MISSING_TYPE *originalLines;
    MISSING_TYPE *animatingDiffDescriptorIndex;
    MISSING_TYPE *scrollCompensationEnabled;
    MISSING_TYPE *isScrolling;
    MISSING_TYPE *registeredObservers;
    MISSING_TYPE *auxViewPreviouslyUntoggled;
    MISSING_TYPE *toggledLineIdentifiers;
    MISSING_TYPE *isInstalled;
    MISSING_TYPE *scrollViewOrigin;
    MISSING_TYPE *previousMargins;
    MISSING_TYPE *deferredScrollCompensationEnabled;
}

- (void)selectionDidChange;
- (void)textWasDeletedWithNotification:(id)arg1;
- (void)textWasInsertedWithNotification:(id)arg1;

@end

