//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDESourceEditor/CALayerDelegate-Protocol.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC15IDESourceEditor31StaticAnalyzerStepVisualization : NSObject <CALayerDelegate>
{
    MISSING_TYPE *visualization;
    MISSING_TYPE *stepLayers;
    MISSING_TYPE *hitTestViews;
}

- (void).cxx_destruct;
- (id)init;

@end

