//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SourceModel/SMLanguageSpecification.h>

@interface SMLanguageSpecification (SourceCodeGenerationAdditions)
- (id)alternateSpecifications;
- (id)generalNameForSourceModelName:(id)arg1;
@end

