//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCBTaskConstruction/_TtC19XCBTaskConstruction20StandardTaskProducer.h>

@interface _TtC19XCBTaskConstruction32CreateBuildDirectoryTaskProducer : _TtC19XCBTaskConstruction20StandardTaskProducer
{
}

@end

