//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCBTaskConstruction/_TtC19XCBTaskConstruction18PhasedTaskProducer.h>

@class MISSING_TYPE;

@interface _TtC19XCBTaskConstruction36FilesBasedBuildPhaseTaskProducerBase : _TtC19XCBTaskConstruction18PhasedTaskProducer
{
    MISSING_TYPE *buildPhase;
    MISSING_TYPE *usedTools;
    MISSING_TYPE *outputsProducedByArchNeutralToolSpec;
}

@end

