//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9CoreAssetP33_02C1A0C8390F8D4B78DD2F41EEADBA7B13BoundBoxCache : _TtCs12_SwiftObject
{
    MISSING_TYPE *queue;
    MISSING_TYPE *meta;
    MISSING_TYPE *table;
}

@end

