//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreAsset/_TtC9CoreAsset11CommonChart.h>

@interface _TtC9CoreAsset12BarChartCore : _TtC9CoreAsset11CommonChart
{
    // Error parsing type: , name: showNames
    // Error parsing type: , name: showValues
    // Error parsing type: , name: format
    // Error parsing type: , name: decimals
    // Error parsing type: , name: size
    // Error parsing type: , name: smallSize
    // Error parsing type: , name: textFloat
    // Error parsing type: , name: textDepth
    // Error parsing type: , name: gap
    // Error parsing type: , name: fnum
    // Error parsing type: , name: length
    // Error parsing type: , name: valueScale
    // Error parsing type: , name: tic
    // Error parsing type: , name: baseTic
    // Error parsing type: , name: maxTic
    // Error parsing type: , name: globalXfo
}

@end

