//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor;

@interface DVTAnalyticsPointChartScaffoldView : NSView
{
    NSColor *_debugColor;
}

- (void).cxx_destruct;
@property(copy) NSColor *debugColor; // @synthesize debugColor=_debugColor;
- (void)drawRect:(struct CGRect)arg1;

@end

