//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

#import <IDEAnalyticsKit/DVTReplacementViewDelegate-Protocol.h>

@class DVTAnalyticsLogRecord, DVTAnalyticsPointAbstractClass, DVTReplacementView, IDEAnalyticsPointDetailViewController, NSString;

@interface IDEAnalyticsPointLogContainerViewController : IDEViewController <DVTReplacementViewDelegate>
{
    DVTAnalyticsLogRecord *_analyticsLogRecord;
    DVTAnalyticsPointAbstractClass *_analyticsPoint;
    IDEAnalyticsPointDetailViewController *_analyticsPointDetailViewController;
    DVTReplacementView *_replacementView;
}

- (void).cxx_destruct;
@property __weak DVTReplacementView *replacementView; // @synthesize replacementView=_replacementView;
@property(nonatomic) __weak IDEAnalyticsPointDetailViewController *analyticsPointDetailViewController; // @synthesize analyticsPointDetailViewController=_analyticsPointDetailViewController;
@property(retain, nonatomic) DVTAnalyticsPointAbstractClass *analyticsPoint; // @synthesize analyticsPoint=_analyticsPoint;
@property(retain, nonatomic) DVTAnalyticsLogRecord *analyticsLogRecord; // @synthesize analyticsLogRecord=_analyticsLogRecord;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)updateInstalledViewController;
@property(readonly) BOOL isLogViewVisible;
@property(readonly) BOOL supportsLowSampleCountFrameCompression;
- (void)toggleLowSampleCountFrameCompression;
@property(readonly) BOOL compressLowSampleCountFrames;
- (void)toggleLibraryFrameCompression;
@property(readonly) BOOL compressLibraryFrames;
- (id)logViewController;
- (void)updateLogView;
- (void)loadView;
- (void)primitiveInvalidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

