//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12RCFoundation7Library : _TtCs12_SwiftObject
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: onItemsChangeEventSource
    // Error parsing type: , name: items
    // Error parsing type: , name: categorizedItems
}

@end

