//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <RCFoundation/_TtC12RCFoundation18ExtensionPointBase.h>

@class MISSING_TYPE;

@interface _TtC12RCFoundationP33_DDF2D0B0E5A56DC955E0DE379010064518WeakExtensionPoint : _TtC12RCFoundation18ExtensionPointBase
{
    MISSING_TYPE *infoData;
}

@end

