//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12RCFoundation10ShadowNode : _TtCs12_SwiftObject
{
    // Error parsing type: , name: scope
    // Error parsing type: , name: optionalInstance
    // Error parsing type: , name: isInstanceValid
    // Error parsing type: , name: generationCallbackState
    // Error parsing type: , name: generationState
    // Error parsing type: , name: generationError
    // Error parsing type: , name: name
    // Error parsing type: , name: $__lazy_storage_$_instanceRx
    // Error parsing type: , name: rxStorage
    // Error parsing type: , name: expandedChildren
    // Error parsing type: , name: engineInterface
    // Error parsing type: , name: eventSourceArgumentValueDidChange
    // Error parsing type: , name: eventSourceRuntimeAttributesDidChange
    // Error parsing type: , name: eventSourceArgumentListDidChange
    // Error parsing type: , name: eventSourceRulersDidChange
    // Error parsing type: , name: eventSourceDidAddChild
    // Error parsing type: , name: eventSourceDidRemoveChild
    // Error parsing type: , name: eventSourceEntityWasReplaced
    // Error parsing type: , name: eventSourceGenerationStateChange
    // Error parsing type: , name: eventSourceRootNodeDidAddDescendent
    // Error parsing type: , name: eventSourceRootNodeWillRemoveDescendent
    // Error parsing type: , name: eventSourceRootNodeDidRemoveDescendent
    // Error parsing type: , name: eventSourceRootNodeDescendentDidChange
    // Error parsing type: , name: children
    // Error parsing type: , name: parent
    // Error parsing type: , name: orphanedNodes
    // Error parsing type: , name: simulationEntity
}

@end

