//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$s9CoreAsset20BaseInstanceObserverCN.h"

@interface _TtCFV12RCFoundation20RealityAssetExporterP33_E3BB5070E2571A96C81C2BA0D9B4901E39buildSceneEntityTreeWithCollisionShapesFzT10identifierSS15fromEngineQueueSb_C10RealityKit6EntityL_8Observer : _$s9CoreAsset20BaseInstanceObserverCN
{
    // Error parsing type: , name: fromEngineQueue
    // Error parsing type: , name: dispatchGroup
    // Error parsing type: , name: errors
}

@end

