//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12RCFoundation18AFPreviewGenerator : _TtCs12_SwiftObject
{
    // Error parsing type: , name: visualCue
    // Error parsing type: , name: scope
    // Error parsing type: , name: currentGenerationNode
    // Error parsing type: , name: isGenerating
    // Error parsing type: , name: onGenerationEventSource
}

@end

