//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSImageView;

@interface _DVTScrollViewShadowView : NSView
{
    NSImageView *_shadowImageView;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

