//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTUserInterfaceKit/_TtC19DVTUserInterfaceKit28DVTIconPreviewViewController.h>

@class OS_dispatch_queue;

@interface _TtC19DVTUserInterfaceKit28DVTIconPreviewViewController (DVTUserInterfaceKit)
- (void)filterSessionDidEnd:(id)arg1;
- (void)filterWithFilterSession:(id)arg1;
@property(nonatomic, readonly) OS_dispatch_queue *filteringQueue;
@end

