//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class DVTColorSwatchView, NSColor, NSString, NSTextField;

@interface DVTColorSwatchLabel : NSView
{
    NSColor *_color;
    BOOL _shouldUseSingleLine;
    DVTColorSwatchView *_colorSwatch;
    NSTextField *_labelTextField;
    NSTextField *_valueTextField;
    NSString *_labelString;
}

- (void).cxx_destruct;
@property(copy) NSString *labelString; // @synthesize labelString=_labelString;
@property(nonatomic) BOOL shouldUseSingleLine; // @synthesize shouldUseSingleLine=_shouldUseSingleLine;
@property(readonly) NSTextField *valueTextField; // @synthesize valueTextField=_valueTextField;
@property(readonly) NSTextField *labelTextField; // @synthesize labelTextField=_labelTextField;
@property(readonly) DVTColorSwatchView *colorSwatch; // @synthesize colorSwatch=_colorSwatch;
- (id)_createColorSwatchImageView;
- (id)_createLabel:(id)arg1;
- (id)_createValueTextField;
- (id)_createLabelTextField;
- (void)_buildViewWithoutValueTextField;
- (void)_buildViewWithValueTextField;
- (id)initWithColor:(id)arg1 label:(id)arg2 value:(id)arg3 attributedValue:(id)arg4 valueFormatter:(id)arg5 shouldUseSingleLine:(BOOL)arg6;
- (id)initWithColor:(id)arg1 label:(id)arg2 value:(id)arg3 valueFormatter:(id)arg4;
- (id)initWithColor:(id)arg1 label:(id)arg2 value:(id)arg3;
- (id)initWithColor:(id)arg1 label:(id)arg2;

@end

