//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class DVTDraggedImageState;

@interface DVTDraggedImageStateTransitionView : NSView
{
    float _progress;
    DVTDraggedImageState *_fromState;
    DVTDraggedImageState *_toState;
}

@property(readonly) DVTDraggedImageState *toState; // @synthesize toState=_toState;
@property(readonly) DVTDraggedImageState *fromState; // @synthesize fromState=_fromState;
@property float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
@property(readonly) double duration;
@property(readonly) struct CGPoint anchorPoint;
- (id)initWithFromState:(id)arg1 toState:(id)arg2;

@end

