//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@protocol DVTLinkViewDelegate;

@interface DVTLinkView : NSView
{
    id <DVTLinkViewDelegate> _delegate;
    NSView *_contentView;
}

@property(nonatomic) NSView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <DVTLinkViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)mouseUp:(id)arg1;
- (void)resetCursorRects;

@end

