//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class DVTBorderedView, DVTRangeView, NSTextField, NSView;

@interface DVTRangeViewController : NSViewController
{
    DVTBorderedView *_borderedView;
    DVTRangeView *_rangeView;
    NSView *_locationContainerView;
    NSView *_endLocationContainerView;
    NSTextField *_locationTextField;
    NSTextField *_lengthTextField;
    NSTextField *_endLocationTextField;
    struct _NSRange _range;
}

- (void).cxx_destruct;
@property __weak NSTextField *endLocationTextField; // @synthesize endLocationTextField=_endLocationTextField;
@property __weak NSTextField *lengthTextField; // @synthesize lengthTextField=_lengthTextField;
@property __weak NSTextField *locationTextField; // @synthesize locationTextField=_locationTextField;
@property __weak NSView *endLocationContainerView; // @synthesize endLocationContainerView=_endLocationContainerView;
@property __weak NSView *locationContainerView; // @synthesize locationContainerView=_locationContainerView;
@property __weak DVTRangeView *rangeView; // @synthesize rangeView=_rangeView;
@property __weak DVTBorderedView *borderedView; // @synthesize borderedView=_borderedView;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
- (void)_udpateFromRange;
- (void)loadView;
- (id)initWithDefaultNibName;

@end

