//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTCapacityView.h>

@interface DVTVerticalCapacityView : DVTCapacityView
{
}

- (void)drawRect:(struct CGRect)arg1;

@end

