//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUToolsServices/DYDevice.h>

@class DYTransport, NSError, NSMutableDictionary, NSString, NSURL;

@interface DYMobileDevice : DYDevice
{
    unsigned long long _appServiceTransportTimestamp;
    struct _AMDevice *_device;
    struct _AMDevice *_secondaryDevice;
    struct dispatch_queue_s *_queue;
    struct dispatch_queue_s *_requestsQueue;
    struct dispatch_queue_s *_connectedWaitQueue;
    NSMutableDictionary *_attributesCache;
    DYTransport *_appServiceTransport;
    struct dispatch_queue_s *_appServiceTransportQueue;
    unsigned int _appServiceTransportReservations;
    NSURL *_cachedDeveloperDiskImageURL;
    NSURL *_cachedSymbolsDirectoryURL;
    NSError *_gputoolsServiceAvailabilityError;
    BOOL _gputoolsServiceAvailable;
}

+ (id)replayerAppIdentifier;
+ (Class)controlStrategyClass;
+ (Class)deferredLaunchStrategyClass;
+ (Class)launchStrategyClass;
+ (void)initialize;
- (void).cxx_destruct;
- (id)gputoolsServiceAvailabilityError;
- (BOOL)gputoolsServiceAvailable;
- (void)setPlatform:(int)arg1;
- (id)streamArchiveAtURL:(id)arg1 destinationName:(id)arg2;
- (id)iconDataForApplicationIdentifiers:(id)arg1;
- (id)mobileReplayerGuestApp;
- (id)guestAppWithPath:(id)arg1;
- (id)guestAppWithIdentifier:(id)arg1;
- (id)installedApplications;
- (void)_releaseAppServiceTransportReservation;
- (BOOL)_takeAppServiceTransportReservation:(id *)arg1;
- (void)_shutdownAppServiceTransport;
- (id)startService:(id)arg1;
- (void)_performStartService:(id)arg1 future:(id)arg2;
- (id)createTransport;
- (id)mountDeveloperDiskImage;
- (id)attributeForDomain:(struct __CFString *)arg1 key:(struct __CFString *)arg2;
- (void)_getAttributeForDomain:(struct __CFString *)arg1 key:(struct __CFString *)arg2 future:(id)arg3;
- (id)deviceInfo;
@property(readonly, nonatomic) NSString *amdIdentifier;
@property(readonly, nonatomic) BOOL developmentDevice;
- (BOOL)_cachedIsDevelopmentDevice;
- (id)productType;
- (id)build;
- (id)version;
- (id)name;
- (id)symbolsDirectoryURL;
- (id)developerDiskImageURL;
- (id)refreshDeviceProperties;
- (void)_checkGPUToolsServiceAvailability;
- (void)_checkGPUToolsServiceAvailabilityInner;
- (BOOL)_cacheCommonAttributes:(id *)arg1;
- (BOOL)_cacheAttributeWithDomain:(struct __CFString *)arg1 key:(struct __CFString *)arg2;
- (id)_getAttribCacheKeyForDomain:(struct __CFString *)arg1 key:(struct __CFString *)arg2;
- (BOOL)_runInSession:(CDUnknownBlockType)arg1;
- (BOOL)_startSession:(id *)arg1;
- (void)_stopSession;
- (id)connectedFuture;
- (void)waitUntilConnected;
- (id)unlocked;
@property(readonly, nonatomic) BOOL connected;
- (void)setSecondaryAppleMobileDevice:(struct _AMDevice *)arg1;
- (void)setAppleMobileDevice:(struct _AMDevice *)arg1;
- (struct _AMDevice *)secondaryAppleMobileDevice;
- (struct _AMDevice *)appleMobileDevice;
- (id)description;
- (void)dealloc;
- (id)initWithAMDIdentifier:(id)arg1;
- (id)init;

@end

