//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/NSObject-Protocol.h>

@class NSString;
@protocol PBXScannerItem;

@protocol PBXScannerItem <NSObject>
- (long long)compareWithScannerItem:(id <PBXScannerItem>)arg1;
- (int)type;
- (NSString *)nameWithIndent;
- (NSString *)name;
@end

