//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC18DVTAppStoreConnect8DVTActor : NSObject
{
    MISSING_TYPE *developerTeamIdMap;
}

- (void).cxx_destruct;
- (id)init;
- (id)userVisibleRolesForDeveloperTeamId:(id)arg1;

@end

