//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEWorkspaceTabController.h>

@interface IDEWorkspaceTabController (PlaygroundAdditions)
- (void)performPlaygroundTaskOnScheme:(id)arg1 forSchemeOperationParameters:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
@end

