//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTTextDocumentLocation, NSArray, NSDictionary;

@protocol DVTSourceLanguagePrimaryCompletionStrategy
- (NSArray *)completionItemsForDocumentLocation:(DVTTextDocumentLocation *)arg1 context:(NSDictionary *)arg2 highlyLikelyCompletionItems:(id *)arg3 areDefinitive:(char *)arg4;
@end

