//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class IDEActivityLogSection, IDEActivityLogSectionRecorder, IDEBuildResultsOutlineLogic, MISSING_TYPE, NSArray, NSBox, NSURL, NSView, XCBuildResultsOutlineView, XCSIntegration, _TtC13IDEFoundation34IDEActivityLogEventStreamProcessor;

@interface _TtC5XCSUI32XCSUIStreamingLogsViewController : IDEViewController
{
    MISSING_TYPE *owner;
    MISSING_TYPE *chunks;
    MISSING_TYPE *integration;
    MISSING_TYPE *section;
    MISSING_TYPE *recorder;
    MISSING_TYPE *eventStreamProcessor;
    MISSING_TYPE *outlineView;
    MISSING_TYPE *activeViewHolder;
    MISSING_TYPE *outlineLogic;
    MISSING_TYPE *enclosingView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)readChangesFromTestFile;
- (void)listenForIntegrationChanges;
- (void)primitiveInvalidate;
- (void)viewWillUninstall;
@property(nonatomic, readonly) NSURL *debugChunksUrl;
- (void)configureOutline;
- (id)configureOutlineView:(id)arg1;
- (void)viewDidInstall;
@property(nonatomic, retain) NSView *enclosingView; // @synthesize enclosingView;
@property(nonatomic, retain) IDEBuildResultsOutlineLogic *outlineLogic; // @synthesize outlineLogic;
@property(nonatomic, retain) NSBox *activeViewHolder; // @synthesize activeViewHolder;
@property(nonatomic, retain) XCBuildResultsOutlineView *outlineView; // @synthesize outlineView;
@property(nonatomic, retain) _TtC13IDEFoundation34IDEActivityLogEventStreamProcessor *eventStreamProcessor; // @synthesize eventStreamProcessor;
@property(nonatomic, retain) IDEActivityLogSectionRecorder *recorder; // @synthesize recorder;
@property(nonatomic, retain) IDEActivityLogSection *section; // @synthesize section;
@property(nonatomic, retain) XCSIntegration *integration; // @synthesize integration;
@property(nonatomic, copy) NSArray *chunks;
@property(nonatomic, retain) id owner; // @synthesize owner;

@end

