//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCSUI/IDETestReport_Base-Protocol.h>
#import <XCSUI/IDETestReport_Common-Protocol.h>

@class NSArray, NSString;

@protocol IDETestReport_Test <IDETestReport_Base, IDETestReport_Common>
@property(readonly, nonatomic) NSArray *ide_testReport_test_allTestRunsAcrossDevices;
@property(readonly, copy, nonatomic) NSString *ide_testReport_test_testClassName;
@property(readonly, copy, nonatomic) NSString *ide_testReport_test_testName;
@property(readonly, copy, nonatomic) NSArray *ide_testReport_test_testRunsByDevice;
@property(readonly, nonatomic) BOOL ide_testReport_test_fetchesTestRunsLazily;

@optional
@property(readonly, nonatomic) BOOL ide_testReport_test_mixedStatus;
- (void)ide_testReport_test_fetchTestsWithCompletionHandler:(void (^)(NSArray *))arg1;
@end

