//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEEditorDocument.h>

@interface XCSLegacyBotEditorDocument : IDEEditorDocument
{
}

+ (BOOL)shouldUnlockFileURLBeforeMakingChanges;
- (id)displayName;
- (int)readOnlyStatus;
- (id)initForURL:(id)arg1 withContentsOfURL:(id)arg2 ofType:(id)arg3 error:(id *)arg4;

@end

