//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCSCore/XCSTestAttachment.h>

#import <XCSUI/IDETestReport_RemoteAsset-Protocol.h>
#import <XCSUI/IDETestReport_TestAttachment-Protocol.h>

@class NSDate, NSNumber, NSString, NSURL, NSURLRequest;
@protocol IDETestReport_Base;

@interface XCSTestAttachment (IDETestReport_TestAttachment) <IDETestReport_TestAttachment, IDETestReport_RemoteAsset>
@property(readonly, copy, nonatomic) NSNumber *ide_test_attachment_payloadSize;
@property(readonly, copy, nonatomic) NSString *ide_test_attachment_payload_filePath;
@property(readonly, copy, nonatomic) NSString *ide_test_activity_UTI;
@property(readonly, copy, nonatomic) NSString *ide_test_activity_attachment_base_title;
@property(readonly, copy, nonatomic) NSDate *sortingTimestamp;
@property(readonly, nonatomic) unsigned long long ide_testReport_remoteAsset_size;
@property(readonly, copy, nonatomic) NSURL *ide_testReport_remoteAsset_downloadURL;
@property(readonly, copy, nonatomic) NSString *ide_testReport_remoteAsset_fileName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *ide_testReport_base_identifier;
@property(nonatomic) __weak id <IDETestReport_Base> ide_testReport_base_parent;
@property(readonly, copy, nonatomic) NSURLRequest *ide_testReport_remoteAsset_downloadURLRequest;
@property(readonly) Class superclass;
@end

