//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEGeniusResultsFinder.h>

@interface XCSUIIntegrationReportGeniusResultsFinder_Tests : IDEGeniusResultsFinder
{
}

+ (Class)editorDocumentClass;
- (void)downloadSchemeActionsRecordForIntegration:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)findGeniusResultsForEditorDocument:(id)arg1 selectedDocumentLocations:(id)arg2;

@end

