//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class XCSBot;

@interface XCSUIBotSummaryStatsFetcher : NSObject
{
    XCSBot *_bot;
    CDUnknownBlockType _statsFetcherCallback;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType statsFetcherCallback; // @synthesize statsFetcherCallback=_statsFetcherCallback;
@property(retain) XCSBot *bot; // @synthesize bot=_bot;
- (void)fetchStatsForTimePeriod:(unsigned long long)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)fetchStatsSinceDate:(id)arg1;

@end

