//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTDeviceKit/DVTDeviceSummaryViewController.h>

@interface DVTiPhoneSummaryViewController : DVTDeviceSummaryViewController
{
}

+ (id)keyPathsForValuesAffectingAdditionalSliceViewControllerClasses;
+ (id)keyPathsForValuesAffectingShowApplicationList;
- (Class)deviceLogsViewControllerClass;
- (id)additionalSliceViewControllerClasses;
- (BOOL)showApplicationList;
- (BOOL)showInstalledRootList;

@end

