//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreSimulator/SimRuntime.h>

@interface SimRuntime (DVTSimulatorCreationViewController)
- (id)dvt_nameForSimCreationMenu;
@end

