//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/NSCopying-Protocol.h>
#import <IDEFoundation/NSMutableCopying-Protocol.h>

@class IDETest, NSArray, NSDate, NSMutableArray, NSMutableSet, NSSet, NSString;

@interface IDETestResult : NSObject <NSCopying, NSMutableCopying>
{
    IDETest *_mutableTest;
    NSString *_mutableIdentifier;
    unsigned long long _mutableStatus;
    NSDate *_mutableDate;
    double _mutableDuration;
    NSMutableSet *_mutableFailureLocations;
    NSMutableArray *_mutablePerformanceMetrics;
    NSMutableArray *_mutableMessages;
}

@property(retain) NSMutableArray *mutableMessages; // @synthesize mutableMessages=_mutableMessages;
@property(retain) NSMutableArray *mutablePerformanceMetrics; // @synthesize mutablePerformanceMetrics=_mutablePerformanceMetrics;
@property(retain) NSMutableSet *mutableFailureLocations; // @synthesize mutableFailureLocations=_mutableFailureLocations;
@property double mutableDuration; // @synthesize mutableDuration=_mutableDuration;
@property(retain) NSDate *mutableDate; // @synthesize mutableDate=_mutableDate;
@property unsigned long long mutableStatus; // @synthesize mutableStatus=_mutableStatus;
@property(retain) NSString *mutableIdentifier; // @synthesize mutableIdentifier=_mutableIdentifier;
@property(retain) IDETest *mutableTest; // @synthesize mutableTest=_mutableTest;
- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) NSArray *performanceMetrics;
@property(readonly) NSArray *messages;
@property(readonly) NSSet *failureLocations;
@property(readonly) double duration;
@property(readonly) NSDate *date;
@property(readonly) unsigned long long status;
@property(readonly) IDETest *test;
@property(readonly) NSString *identifier;
- (id)initWithTest:(id)arg1;
- (id)initWithIdentifier:(id)arg1;
- (id)init;

@end

