//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEAnnotationContext.h>

@class IDESourceCodePlaygroundSection;

@interface IDESourceCodePlaygroundSectionAnnotationContext : IDEAnnotationContext
{
    IDESourceCodePlaygroundSection *_playgroundSection;
}

- (void).cxx_destruct;
@property(retain) IDESourceCodePlaygroundSection *playgroundSection; // @synthesize playgroundSection=_playgroundSection;
- (id)initWithEditor:(id)arg1 document:(id)arg2 fileDataType:(id)arg3 playgroundSection:(id)arg4 workspaceTabController:(id)arg5;

@end

