//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScroller.h>

@interface HFCustomScroller : NSScroller
{
}

- (void)setFrame:(struct CGRect)arg1;

@end

