//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HexFiend/HFPasteboardOwner.h>

@interface HFHexPasteboardOwner : HFPasteboardOwner
{
}

- (unsigned long long)stringLengthForDataLength:(unsigned long long)arg1;
- (void)writeDataInBackgroundToPasteboard:(id)arg1 ofLength:(unsigned long long)arg2 forType:(id)arg3 trackingProgress:(id)arg4;

@end

