//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC27MLRecipeExecutionController15ProgressMonitor : _TtCs12_SwiftObject
{
    MISSING_TYPE *state;
    MISSING_TYPE *observer;
    MISSING_TYPE *domain;
    MISSING_TYPE *spec;
    MISSING_TYPE *store;
    MISSING_TYPE *eventStreamFuture;
    MISSING_TYPE *invalidated;
}

@end

