#!/usr/bin/env ruby


xcode = ARGV[0] || "/Applications/Xcode.app/"

def xcode_folder(xcode_path, relative)
  File.join(xcode_path, 'Contents', relative)
end

def framework_name(path)
  File.basename(path, '.*')
end

folders = [
  xcode_folder(xcode, 'Frameworks'),
  xcode_folder(xcode, 'OtherFrameworks'),
  xcode_folder(xcode, 'SharedFrameworks'),
  xcode_folder(xcode, 'PlugIns')
]

folders.each do |path|
  Dir.each_child(path) do |item|
    name = framework_name(item)
    dir_name = File.expand_path(name, 'Headers')
    Dir.mkdir_p(dir_name)

    system('class-dump', '-H', '-o', dir_name, File.join(path, item))
  end
end