//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (XCSCoreAdditions)
- (id)xcs_arrayByApplyingBlock:(CDUnknownBlockType)arg1;
- (id)toJSONCompactWithError:(id *)arg1;
- (id)toJSONCompact;
- (id)toJSONWithError:(id *)arg1;
- (id)toJSON;
@end

