//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCSCore/XCSTestObjectPlaceholder.h>

@class NSArray;

@interface XCSTestTargetPlaceholder : XCSTestObjectPlaceholder
{
}

- (id)saveRepresentationHumanReadable:(BOOL)arg1;
- (id)description;
- (BOOL)hasPerfTests;
@property(readonly, nonatomic) NSArray *testClasses;
- (void)setTestClasses:(struct NSArray *)arg1;

@end

