//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDESwiftPackageSupport/_TtC22IDESwiftPackageSupport15IDESwiftPackage.h>

#import <IDESwiftPackageSupport/IDESourcePackage-Protocol.h>

@class DVTFilePath, NSArray;

@interface _TtC22IDESwiftPackageSupport15IDESwiftPackage (IDESwiftPackageSupport2) <IDESourcePackage>
@property(nonatomic, readonly) NSArray *packageProducts;
@property(nonatomic, readonly) BOOL isRemotePackage;
@property(nonatomic, readonly) DVTFilePath *packagePath;
@end

