//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEContainerCore.h>

@interface _TtC22IDESwiftPackageSupport19IDESwiftPackageCore : IDEContainerCore
{
}

- (id)initWithFilePath:(id)arg1 extension:(id)arg2 error:(id *)arg3;
- (id)init;

@end

