//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDETemplate.h>

__attribute__((visibility("hidden")))
@interface _TtC22IDESwiftPackageSupport30IDESwiftPackageProjectTemplate : IDETemplate
{
    // Error parsing type: , name: packageType
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithTemplateInfo:(id)arg1 filePath:(id)arg2;

@end

