//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDESwiftPackageSupport/_TtCO18PIFGenerationModel3PIF9Reference.h>

@class MISSING_TYPE;

@interface _TtCO18PIFGenerationModel3PIF5Group : _TtCO18PIFGenerationModel3PIF9Reference
{
    MISSING_TYPE *subitems;
}

@end

