//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV3NIO10ByteBuffer8_Storage : _TtCs12_SwiftObject
{
    MISSING_TYPE *capacity;
    MISSING_TYPE *bytes;
    MISSING_TYPE *allocator;
}

@end

