//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12MinimalBasic18TemporaryDirectory : _TtCs12_SwiftObject
{
    // Error parsing type: , name: prefix
    // Error parsing type: , name: path
    // Error parsing type: , name: shouldRemoveTreeOnDeinit
}

@end

