//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCResultKit/_TtC15XCResultTypesV327ActivityLogMajorSectionHead.h>

@class MISSING_TYPE;

@interface _TtC15XCResultTypesV333ActivityLogTargetBuildSectionHead : _TtC15XCResultTypesV327ActivityLogMajorSectionHead
{
    MISSING_TYPE *productType;
}

@end

