//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12MinimalBasicP33_BC4F6EFF6BD20B8DE9FAE57D199121A715LocalFileSystem : _TtCs12_SwiftObject
{
}

@end

