//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCResultKit/_TtC15XCResultTypesV322ActivityLogSectionHead.h>

@class MISSING_TYPE;

@interface _TtC15XCResultTypesV339ActivityLogCommandInvocationSectionHead : _TtC15XCResultTypesV322ActivityLogSectionHead
{
    MISSING_TYPE *commandDetails;
}

@end

