//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCResultKit/_TtC15XCResultTypesV335ActionTestSummaryIdentifiableObject.h>

@interface _TtC15XCResultTypesV318ActionTestMetadata : _TtC15XCResultTypesV335ActionTestSummaryIdentifiableObject
{
    // Error parsing type: , name: testStatus
    // Error parsing type: , name: duration
    // Error parsing type: , name: summaryRef
    // Error parsing type: , name: performanceMetricsCount
    // Error parsing type: , name: failureSummariesCount
    // Error parsing type: , name: activitySummariesCount
}

@end

