//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC15XCResultStorage18ResultBundleWriter : _TtCs12_SwiftObject
{
    MISSING_TYPE *version;
    MISSING_TYPE *storage;
    MISSING_TYPE *dateCreated;
    MISSING_TYPE *metadataStore;
    MISSING_TYPE *dataStore;
    MISSING_TYPE *converters;
    MISSING_TYPE *log;
    MISSING_TYPE *isOpen;
    MISSING_TYPE *context;
}

@end

