//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GLToolsServices/DYCacheableResource-Protocol.h>
#import <GLToolsServices/NSObject-Protocol.h>

@class NSData;

@protocol DYTextureImageBackingStore <NSObject, DYCacheableResource>
@property(retain, nonatomic) NSData *uncompressedData;
@property(retain, nonatomic) NSData *data;
@end

