//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s11MLSharedKit23DraggableDataSourceViewCN.h"

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC10MLModelKit28ModelExperimentDraggableView : _$s11MLSharedKit23DraggableDataSourceViewCN
{
    MISSING_TYPE *dashWidth;
    MISSING_TYPE *dashColor;
    MISSING_TYPE *dashLength;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

