//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s11MLSharedKit24ObservableViewControllerCN.h"

@class MISSING_TYPE, NSCollectionView, NSSegmentedCell, NSView, _TtC10MLModelKit12ISNoDataView, _TtC10MLModelKit18ISPreviewImageView;

@interface _TtC10MLModelKit27ISPreviewDataViewController : _$s11MLSharedKit24ObservableViewControllerCN
{
    MISSING_TYPE *noDataView;
    MISSING_TYPE *contentView;
    MISSING_TYPE *predictionsCollectionView;
    MISSING_TYPE *previewModeSegmentedControl;
    MISSING_TYPE *inputImagePreviewView;
    MISSING_TYPE *state;
    MISSING_TYPE *recognizedCategories;
    MISSING_TYPE *mlModel;
    MISSING_TYPE *queue;
    MISSING_TYPE *collectionViewItemIdentifier;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)previewModeSegmentedControlValueChanged:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC10MLModelKit18ISPreviewImageView *inputImagePreviewView; // @synthesize inputImagePreviewView;
@property(nonatomic) __weak NSSegmentedCell *previewModeSegmentedControl; // @synthesize previewModeSegmentedControl;
@property(nonatomic) __weak NSCollectionView *predictionsCollectionView; // @synthesize predictionsCollectionView;
@property(nonatomic) __weak NSView *contentView; // @synthesize contentView;
@property(nonatomic) __weak _TtC10MLModelKit12ISNoDataView *noDataView; // @synthesize noDataView;

@end

