//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14XCBBuildSystem14CleanOperation : _TtCs12_SwiftObject
{
    MISSING_TYPE *buildRequest;
    MISSING_TYPE *delegate;
    MISSING_TYPE *dependencyResolverDelegate;
    MISSING_TYPE *diagnosticsEngine;
    MISSING_TYPE *style;
    MISSING_TYPE *workspaceContext;
    MISSING_TYPE *cancelled;
    MISSING_TYPE *uuid;
    MISSING_TYPE *hadErrors;
    MISSING_TYPE *subtaskProgressReporter;
}

@end

