//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (IDEPlistTextFragmentProviderAdditions)
- (void)ide_plistTextProviderPopulateFlatPlist:(id)arg1 index:(long long)arg2;
@end

