//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7MLModel5Model : _TtCs12_SwiftObject
{
    MISSING_TYPE *id;
    MISSING_TYPE *version;
    MISSING_TYPE *createdDate;
    MISSING_TYPE *modifiedDate;
    MISSING_TYPE *title;
    MISSING_TYPE *experimentID;
    MISSING_TYPE *modelURL;
}

@end

