//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEDelta/NSObject-Protocol.h>

@class NSClipView, NSEvent, NSScrollView, NSScroller;

@protocol SourceEditorComparisonScrollViewDelegate <NSObject>
- (void)reflectScrolledClipView:(NSClipView *)arg1;
- (NSScroller *)scrollView:(NSScrollView *)arg1 pointInVisibleScroller:(struct CGPoint)arg2;
- (void)scrollViewDidSetFrameSize:(NSScrollView *)arg1;
- (void)scrollViewDidEndLiveResize:(NSScrollView *)arg1;
- (void)scrollViewWillStartLiveResize:(NSScrollView *)arg1;
- (BOOL)scrollView:(NSScrollView *)arg1 shouldHandleScrollWheelEvent:(NSEvent *)arg2;
@end

