//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GTFWeakCollection;

@interface GTFWeakEntry : NSObject
{
    GTFWeakCollection *_collection;
    unsigned long long _hash;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithObjectHash:(unsigned long long)arg1 inCollection:(id)arg2;

@end

