//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GameToolsFoundation/GTFActionModel.h>

@interface SKActionScaleTo : GTFActionModel
{
}

- (void)reverse;
- (id)getSKAction;
- (id)actionInfoString;
- (id)actionColor;
- (id)actionName;
- (long long)actionType;
- (id)initWithScale:(double)arg1;

@end

