//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEPlaygroundsKit/NSObject-Protocol.h>

@class NSSet, NSString;

@protocol IDEStructureNavigatorMenuItemWhitelistProvider <NSObject>
- (NSSet *)filterMenuWhitelistIdentifiers;
- (NSSet *)contextualMenuWhitelistIdentifiers;
- (NSSet *)fileNewMenuWhitelistIdentifiers;

@optional
- (NSString *)secondaryNewItemOverrideIdentifier;
- (NSString *)primaryNewItemOverrideIdentifier;
@end

