//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MetalKit/MTKView.h>

@class DYRenderingAttributes;
@protocol DYPPostVertexTransformAttribute;

__attribute__((visibility("hidden")))
@interface _TtC21GPUDebuggerMTLSupport31GPUTracePostVertexTransformView : MTKView
{
    // Error parsing type: , name: projectionType
    // Error parsing type: , name: zNearValue
    // Error parsing type: , name: zFarValue
    // Error parsing type: , name: fovValue
    // Error parsing type: , name: projectionZMinValue
    // Error parsing type: , name: showWireframe
    // Error parsing type: , name: showModelVertices
    // Error parsing type: , name: showAttachment
    // Error parsing type: , name: selectedModelPrimitiveIndex
    // Error parsing type: , name: selectedModelPrimitiveVertexIndex
    // Error parsing type: , name: secondarySelectedModelPrimitiveIndex
    // Error parsing type: , name: allowVertexSelection
    // Error parsing type: , name: currentVertexAttribute
    // Error parsing type: , name: cullMode
    // Error parsing type: , name: renderTargetArrayIndex
    // Error parsing type: , name: viewportArrayIndex
    // Error parsing type: , name: camera
    // Error parsing type: , name: commandQueue
    // Error parsing type: , name: defaultLibrary
    // Error parsing type: , name: defaultPipelineState
    // Error parsing type: , name: texturePipelineState
    // Error parsing type: , name: defaultModelPipelineState
    // Error parsing type: , name: userAttributeModelPipelineState
    // Error parsing type: , name: greaterEqualDepthState
    // Error parsing type: , name: greaterEqualNoDepthWriteDepthState
    // Error parsing type: , name: noDepthState
    // Error parsing type: , name: modelVertices
    // Error parsing type: , name: modelViewportArrayIndices
    // Error parsing type: , name: modelRenderTargetArrayIndices
    // Error parsing type: , name: modelVertexBuffer
    // Error parsing type: , name: modelIndexBuffer
    // Error parsing type: , name: modelBoundingBox
    // Error parsing type: , name: bufferAllocator
    // Error parsing type: , name: cubeMesh
    // Error parsing type: , name: texturedQuadMesh
    // Error parsing type: , name: axesMesh
    // Error parsing type: , name: attachmentTextures
    // Error parsing type: , name: framebufferWidth
    // Error parsing type: , name: framebufferHeight
    // Error parsing type: , name: model
    // Error parsing type: , name: geometryInput
    // Error parsing type: , name: positionAttrib
    // Error parsing type: , name: builtinAttribs
    // Error parsing type: , name: userVertexAttributesRenderingAttributes
    // Error parsing type: , name: renderingAttributesObservers
    // Error parsing type: , name: framebufferImages
    // Error parsing type: , name: storage
    // Error parsing type: , name: postVertexTransformItem
    // Error parsing type: , name: viewports
    // Error parsing type: , name: vertexAmplificationViewportOffsets
    // Error parsing type: , name: readyForDisplay
    // Error parsing type: , name: updateModelInverseProjection
    // Error parsing type: , name: updateInitialCameraTarget
    // Error parsing type: , name: invProjMatrices
    // Error parsing type: , name: showViewFrustum
    // Error parsing type: , name: showAxes
    // Error parsing type: , name: showModelBoundingBox
    // Error parsing type: , name: toneMappingDisabled
}

+ (unsigned long long)InvalidModelIndex;
+ (id)SelectedPrimitiveNotificationName;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 device:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)handleMouseClick:(id)arg1;
- (void)saveState;
- (void)makeDefaultSelection;
- (void)focusCameraOnSelectedPrimitive;
- (void)resetView;
- (void)loadViewWithModel:(id)arg1 geometryInput:(id)arg2 builtinAttributes:(id)arg3 userDefinedAttributes:(id)arg4 viewports:(id)arg5 vertexAmplificationViewMappings:(id)arg6 framebufferImages:(id)arg7 storage:(id)arg8 postVertexTransformItem:(id)arg9;
- (id)accessibilityParent;
- (struct CGRect)accessibilityFrame;
- (id)accessibilityLabel;
- (id)accessibilityIdentifier;
- (BOOL)isAccessibilityElement;
- (void)awakeFromNib;
@property(nonatomic, readonly) BOOL acceptsFirstResponder;
@property(nonatomic) unsigned int viewportArrayIndex; // @synthesize viewportArrayIndex;
@property(nonatomic) unsigned int renderTargetArrayIndex; // @synthesize renderTargetArrayIndex;
@property(nonatomic) unsigned long long cullMode; // @synthesize cullMode;
@property(nonatomic, readonly) DYRenderingAttributes *currentRenderingAttributes;
@property(nonatomic, retain) id <DYPPostVertexTransformAttribute> currentVertexAttribute; // @synthesize currentVertexAttribute;
@property(nonatomic, readonly) BOOL hasAttachment;
@property(nonatomic) BOOL allowVertexSelection; // @synthesize allowVertexSelection;
@property(nonatomic) unsigned long long secondarySelectedModelPrimitiveIndex; // @synthesize secondarySelectedModelPrimitiveIndex;
@property(nonatomic) unsigned long long selectedModelPrimitiveVertexIndex; // @synthesize selectedModelPrimitiveVertexIndex;
@property(nonatomic) unsigned long long selectedModelPrimitiveIndex; // @synthesize selectedModelPrimitiveIndex;
@property(nonatomic) BOOL showAttachment; // @synthesize showAttachment;
@property(nonatomic) BOOL showModelVertices; // @synthesize showModelVertices;
@property(nonatomic) BOOL showWireframe; // @synthesize showWireframe;
@property(nonatomic) double projectionZMinValue; // @synthesize projectionZMinValue;
@property(nonatomic) float fovValue; // @synthesize fovValue;
@property(nonatomic) float zFarValue; // @synthesize zFarValue;
@property(nonatomic) float zNearValue; // @synthesize zNearValue;
@property(nonatomic) unsigned long long projectionType; // @synthesize projectionType;

@end

