//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/GPURenderBufferView.h>

@class DYRenderingAttributes;
@protocol DYPMTLTexture;

__attribute__((visibility("hidden")))
@interface GPUMTLTextureQuicklookView : GPURenderBufferView
{
    _Bool _isDepthStencil;
    id <DYPMTLTexture> _texture;
    struct DYInterposeVersion *_interposerVersion;
    DYRenderingAttributes *_renderingAttributes;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) DYRenderingAttributes *renderingAttributes; // @synthesize renderingAttributes=_renderingAttributes;
@property(nonatomic) struct DYInterposeVersion *interposerVersion; // @synthesize interposerVersion=_interposerVersion;
@property(retain, nonatomic) id <DYPMTLTexture> texture; // @synthesize texture=_texture;
- (id)renderedImage;
- (void)setSelectedLayer:(unsigned int)arg1;

@end

