//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/GPURenderJob.h>

@protocol DYPEnumUtils;

__attribute__((visibility("hidden")))
@interface GPUMTLRenderJob : GPURenderJob
{
    id <DYPEnumUtils> _enumUtils;
    unsigned long long _attachmentIndex;
}

@property(readonly, nonatomic) unsigned long long attachmentIndex; // @synthesize attachmentIndex=_attachmentIndex;
- (void).cxx_destruct;
- (id)displayElementName;
- (BOOL)isStencilDisplayElement;
- (BOOL)isDepthDisplayElement;
- (id)initWithItem:(id)arg1 resource:(id)arg2 overlayResources:(id)arg3 modelFactory:(id)arg4 textureImageGroupComponent:(unsigned long long)arg5;
- (id)initWithResource:(id)arg1 overlayResources:(id)arg2 modelFactory:(id)arg3 attachmentIndex:(unsigned long long)arg4 renderTargetArrayIndex:(unsigned long long)arg5 framebuffer:(id)arg6;

@end

