//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol DYPResourceManager;

@protocol GPUStateValueQuicklookProvider
@property(nonatomic) __weak id <DYPResourceManager> resourceManager;
@end

