//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DNTDocumentationSupport/DNTDisplayTreeIndexDelegate-Protocol.h>

@interface _TtC23DNTDocumentationSupport23DisplayTreeIndexManager : NSObject <DNTDisplayTreeIndexDelegate>
{
}

- (id)init;
- (id)entityWithPartialURL:(id)arg1 isGroup:(BOOL)arg2 rawLanguage:(int)arg3 name:(id)arg4 kind:(long long)arg5 platformAvailabilityMask:(unsigned int)arg6 availabilityItemId:(unsigned int)arg7;
- (id)groupMarkerWithParent:(id)arg1 name:(id)arg2;
- (id)collectionWithRawLanguageValue:(int)arg1;
- (id)rootIndexItem;

@end

