//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface DNTDisplayTreeIndexItemState : NSObject
{
    NSArray *_children;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *children; // @synthesize children=_children;
- (id)initWithChildren:(id)arg1;

@end

