//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDETabbedWindow.h>

#import <IDEDocViewer/_TtP6IDEKit22IDEDocumentationWindow_-Protocol.h>

@class NSString;

@interface IDEDocWindow : IDETabbedWindow <_TtP6IDEKit22IDEDocumentationWindow_>
{
    BOOL _firstResponderLocked;
}

@property BOOL firstResponderLocked; // @synthesize firstResponderLocked=_firstResponderLocked;
- (BOOL)makeFirstResponder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

