//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@class IDEDocSearchResultItem;

@interface IDEDocSearchResultTableRowView : NSTableRowView
{
    BOOL _mouseInside;
    IDEDocSearchResultItem *_resultItem;
}

+ (id)keyPathsForValuesAffectingSeparator;
+ (id)keyPathsForValuesAffectingHeader;
+ (id)keyPathsForValuesAffectingSelectable;
- (void).cxx_destruct;
@property(nonatomic) BOOL mouseInside; // @synthesize mouseInside=_mouseInside;
@property(retain) IDEDocSearchResultItem *resultItem; // @synthesize resultItem=_resultItem;
- (long long)selectionHighlightStyle;
@property(readonly, getter=isSeparator) BOOL separator;
- (BOOL)isHeader;
@property(readonly, getter=isSelectable) BOOL header;

// Remaining properties
@property(readonly, getter=isSelectable) BOOL selectable;

@end

