//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTFilePath, DVTPlatform, DVTPortalAppIDFeatures, DVTPortalProfilePurpose, DVTSDK, IDEProvisionableEntitlements, IDEProvisioningEntitlementsExpansion, NSString;
@protocol IDEProvisioningBasicTeam;

@interface _IDEProvisionableConfigurationSnapshot : NSObject
{
    BOOL _allowSigningWithoutTeamSelection;
    BOOL _signingRequiresTeam;
    BOOL _supportsIOSMac;
    NSString *_name;
    long long _provisioningStyle;
    id <IDEProvisioningBasicTeam> _team;
    long long _profileSupport;
    DVTPlatform *_platform;
    DVTSDK *_sdk;
    NSString *_sdkVariant;
    NSString *_bundleIdentifier;
    NSString *_profileSpecifier;
    NSString *_certificateIdentifier;
    DVTFilePath *_entitlementsFilePath;
    IDEProvisionableEntitlements *_baseEntitlements;
    IDEProvisioningEntitlementsExpansion *_entitlementsExpansion;
    unsigned long long _entitlementsDestination;
    DVTPortalAppIDFeatures *_appIDFeatures;
    DVTPortalProfilePurpose *_provisioningPurpose;
}

+ (id)snapshotWithConfigurationName:(id)arg1 provisioningStyle:(long long)arg2 team:(id)arg3 profileSupport:(long long)arg4 platform:(id)arg5 sdk:(id)arg6 sdkVariant:(id)arg7 bundleIdentifier:(id)arg8 profileSpecifier:(id)arg9 certificateIdentifier:(id)arg10 entitlementsFilePath:(id)arg11 baseEntitlements:(id)arg12 entitlementsExpansion:(id)arg13 entitlementsDestination:(unsigned long long)arg14 allowSigningWithoutTeamSelection:(BOOL)arg15 signingRequiresTeam:(BOOL)arg16 appIDFeatures:(id)arg17 provisioningPurpose:(id)arg18 supportsIOSMac:(BOOL)arg19;
@property(readonly, nonatomic) BOOL supportsIOSMac; // @synthesize supportsIOSMac=_supportsIOSMac;
@property(readonly, nonatomic) DVTPortalProfilePurpose *provisioningPurpose; // @synthesize provisioningPurpose=_provisioningPurpose;
@property(readonly, nonatomic) DVTPortalAppIDFeatures *appIDFeatures; // @synthesize appIDFeatures=_appIDFeatures;
@property(readonly, nonatomic) BOOL signingRequiresTeam; // @synthesize signingRequiresTeam=_signingRequiresTeam;
@property(readonly, nonatomic) BOOL allowSigningWithoutTeamSelection; // @synthesize allowSigningWithoutTeamSelection=_allowSigningWithoutTeamSelection;
@property(readonly, nonatomic) unsigned long long entitlementsDestination; // @synthesize entitlementsDestination=_entitlementsDestination;
@property(readonly, nonatomic) IDEProvisioningEntitlementsExpansion *entitlementsExpansion; // @synthesize entitlementsExpansion=_entitlementsExpansion;
@property(readonly, nonatomic) IDEProvisionableEntitlements *baseEntitlements; // @synthesize baseEntitlements=_baseEntitlements;
@property(readonly, nonatomic) DVTFilePath *entitlementsFilePath; // @synthesize entitlementsFilePath=_entitlementsFilePath;
@property(readonly, nonatomic) NSString *certificateIdentifier; // @synthesize certificateIdentifier=_certificateIdentifier;
@property(readonly, nonatomic) NSString *profileSpecifier; // @synthesize profileSpecifier=_profileSpecifier;
@property(readonly, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(readonly, nonatomic) NSString *sdkVariant; // @synthesize sdkVariant=_sdkVariant;
@property(readonly, nonatomic) DVTSDK *sdk; // @synthesize sdk=_sdk;
@property(readonly, nonatomic) DVTPlatform *platform; // @synthesize platform=_platform;
@property(readonly, nonatomic) long long profileSupport; // @synthesize profileSupport=_profileSupport;
@property(readonly, nonatomic) id <IDEProvisioningBasicTeam> team; // @synthesize team=_team;
@property(readonly, nonatomic) long long provisioningStyle; // @synthesize provisioningStyle=_provisioningStyle;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;

@end

