//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC13IDEFoundation37BroadcastTestSummariesBuilderDelegate : NSObject
{
    // Error parsing type: , name: subdelegates
}

- (void).cxx_destruct;
- (id)init;
- (void)builder:(id)arg1 didFinishTestSuiteWithSummary:(id)arg2;
- (void)builder:(id)arg1 didStartTestSuiteWithSummary:(id)arg2;
- (void)builder:(id)arg1 didFinishTestWithSummary:(id)arg2;
- (void)builder:(id)arg1 didStartTestWithName:(id)arg2 identifier:(id)arg3;
- (id)initWithSubdelegates:(id)arg1;

@end

