//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDESigningEditorAssetSelectionDataSourceProvider-Protocol.h>

@class MISSING_TYPE, NSArray, _TtC13IDEFoundation26SigningEditorConfiguration;
@protocol IDEProvisioningAssetSelectionDataSourceProvider;

@interface _TtC13IDEFoundation33SigningEditorProvisionableManager : NSObject <IDESigningEditorAssetSelectionDataSourceProvider>
{
    MISSING_TYPE *manager;
    MISSING_TYPE *dataSources;
    MISSING_TYPE *observation;
    MISSING_TYPE *delayedInvocation;
    MISSING_TYPE *dataSourceProviderSubscription;
    MISSING_TYPE *configuration;
    MISSING_TYPE *signingEditorProvisionableToMatchingProvisionables;
    MISSING_TYPE *signingEditorProvisionables;
}

- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (id)initWithProvisionableManager:(id)arg1 configuration:(id)arg2;
@property(nonatomic, retain) _TtC13IDEFoundation26SigningEditorConfiguration *configuration; // @synthesize configuration;
@property(nonatomic, copy) NSArray *dataSources;
@property(nonatomic, retain) id <IDEProvisioningAssetSelectionDataSourceProvider> manager; // @synthesize manager;

@end

