//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC13IDEFoundation53SigningEditorCapabilityItemLibraryAssetManagerContext : NSObject
{
    MISSING_TYPE *target;
    MISSING_TYPE *configuration;
    MISSING_TYPE *platform;
    MISSING_TYPE *isMacCatalystTarget;
    MISSING_TYPE *productType;
    MISSING_TYPE *isXPCTarget;
    MISSING_TYPE *appExtensionPointIdentifier;
    MISSING_TYPE *team;
    MISSING_TYPE *supportsCapabilities;
    MISSING_TYPE *enabledCapabilityItemIdentifiers;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;

@end

