//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSSet;
@protocol IDETestPlanResolvedOptions, IDETestable;

@interface _TtC13IDEFoundation27IDEConcreteTestingSpecifier : NSObject
{
    MISSING_TYPE *_testable;
    MISSING_TYPE *options;
    MISSING_TYPE *skippedTests;
    MISSING_TYPE *selectedTests;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) id <IDETestable> testable;
- (id)initWithTestable:(id)arg1 options:(id)arg2 skippedTests:(id)arg3 selectedTests:(id)arg4;
@property(nonatomic, readonly) NSSet *selectedTests;
@property(nonatomic, readonly) NSSet *skippedTests;
@property(nonatomic, readonly) id <IDETestPlanResolvedOptions> options; // @synthesize options;

@end

