//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEProfileQualification, MISSING_TYPE, NSArray, NSOrderedSet, NSString, _TtC13IDEFoundation26SigningEditorConfiguration, _TtC13IDEFoundation33SigningEditorProvisionableManager, _TtC13IDEFoundation46SigningEditorCapsuleViewStateRestorationRecord;
@protocol IDEProvisioningAssetSelectionDataSource, IDEProvisioningBasicProfile, IDEProvisioningBasicSigningIdentity, IDEProvisioningBasicTeam, IDESigningEditorConfigurationDataSourceDelegate, IDESigningEditorIOSMacAssetSelectionDataSource><NSObject;

@interface _TtC13IDEFoundation26SigningEditorProvisionable : NSObject
{
    MISSING_TYPE *configurationDataSourceDelegate;
    MISSING_TYPE *dataSource;
    MISSING_TYPE *manager;
    MISSING_TYPE *$__lazy_storage_$_iOSMacDataSource;
    MISSING_TYPE *observedReadOnlyKeyPaths;
    MISSING_TYPE *delegate;
    MISSING_TYPE *configuration;
    MISSING_TYPE *teams;
}

+ (id)keyPathsForValuesAffectingErrors;
+ (id)keyPathsForValuesAffectingRepairBusyReason;
+ (id)keyPathsForValuesAffectingIsRepairBusy;
+ (id)keyPathsForValuesAffectingProvisioningStyle;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) NSArray *errors;
@property(nonatomic, readonly) NSString *repairBusyReason;
@property(nonatomic, readonly) BOOL wantsTeamSelectionRegardlessOfSigningStyle;
@property(nonatomic, readonly) long long signingStyle;
@property(nonatomic, retain) id <IDEProvisioningBasicSigningIdentity> signingIdentity;
@property(nonatomic, readonly) NSOrderedSet *signingIdentities;
@property(nonatomic, readonly) BOOL isSigningIdentityChangeable;
- (id)provisioningProfileDownloaderContextWithError:(id *)arg1;
- (void)locateEligibleProfiles:(id *)arg1 ineligibleProfiles:(id *)arg2;
@property(nonatomic, readonly) BOOL showEmptyProfileSelectionPlaceholder;
@property(nonatomic, readonly) IDEProfileQualification *profileQualification;
@property(nonatomic, retain) id <IDEProvisioningBasicProfile> provisioningProfile;
@property(nonatomic, readonly) long long profileSupport;
- (BOOL)isProfileChangeable;
- (BOOL)isRepairBusy;
@property(nonatomic, retain) id <IDEProvisioningBasicTeam> team;
@property(nonatomic, readonly) BOOL isTeamSelectionRequired;
@property(nonatomic, retain) NSOrderedSet *teams; // @synthesize teams;
@property(nonatomic, copy) NSString *bundleIdentifier;
@property(nonatomic, readonly) BOOL wantsBundleIdentifierEditing;
@property(nonatomic, readonly) BOOL isBundleIdentifierReadOnly;
@property(nonatomic) long long provisioningStyle;
@property(nonatomic, readonly) _TtC13IDEFoundation26SigningEditorConfiguration *configuration; // @synthesize configuration;
@property(nonatomic, readonly) NSString *title;
@property(nonatomic, readonly) NSArray *configurationNames;
@property(nonatomic, readonly) _TtC13IDEFoundation46SigningEditorCapsuleViewStateRestorationRecord *restorationRecord;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
@property(nonatomic, retain) id <IDESigningEditorIOSMacAssetSelectionDataSource><NSObject> iOSMacDataSource;
@property(nonatomic) __weak _TtC13IDEFoundation33SigningEditorProvisionableManager *manager; // @synthesize manager;
@property(nonatomic, readonly) id <IDEProvisioningAssetSelectionDataSource> dataSource; // @synthesize dataSource;
@property(nonatomic) __weak id <IDESigningEditorConfigurationDataSourceDelegate> configurationDataSourceDelegate; // @synthesize configurationDataSourceDelegate;

// Remaining properties
@property(nonatomic, readonly) BOOL profileChangeable;
@property(nonatomic, readonly) BOOL repairBusy;

@end

