//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation11IDETestPlan.h>

#import <IDEFoundation/IDECodeCoverageProviding-Protocol.h>

@interface _TtC13IDEFoundation11IDETestPlan (IDEFoundation) <IDECodeCoverageProviding>
- (BOOL)isCodeCoverageEnabled;

// Remaining properties
@property(nonatomic, readonly) BOOL codeCoverageEnabled;
@end

