//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation23IDEDocumentationManager.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC13IDEFoundation34_IDEDocumentationManagerStandalone : _TtC13IDEFoundation23IDEDocumentationManager
{
    MISSING_TYPE *indexingProgress;
}

- (void).cxx_destruct;

@end

