//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/_TtC13IDEFoundation20IDEXCTestRunCoder_V2.h>

#import <IDEFoundation/IDEXCTestRunEncoder-Protocol.h>

@interface _TtC13IDEFoundation20IDEXCTestRunCoder_V2 (IDEFoundation1) <IDEXCTestRunEncoder>
- (id)dictionaryRepresentationWithTestPlanInfo:(id)arg1 testRunSpecificationGroups:(id)arg2 codeCoverageBuildableInfos:(id)arg3 testRootPathPlaceholder:(id)arg4 derivedDataPathPlaceholder:(id)arg5;
@end

