//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTInvalidation_NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtCC13IDEFoundation22IDEBuildNoticeProvider16BuildLogObserver : DVTInvalidation_NSObject
{
    MISSING_TYPE *workspace;
    MISSING_TYPE *latestBuildLogDidChangeIdentityObservation;
    MISSING_TYPE *activeSession;
    MISSING_TYPE *observer;
    MISSING_TYPE *buildInProgress;
}

- (void).cxx_destruct;
- (id)init;
- (void)primitiveInvalidate;

@end

