//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC15XCSourceControl30XCSourceControlNetworkLogEntry;

@protocol _TtP15XCSourceControl29XCSourceControlNetworkLogging_
- (void)logNetworkRequest:(_TtC15XCSourceControl30XCSourceControlNetworkLogEntry *)arg1;
@end

