//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTPlatform.h>

@class IDEExtendedPlatformInfo;

@interface DVTPlatform (IDEProvisioningPlatformAndSDKAdditions)
+ (id)allDeploymentTargetSettingNames;
- (id)entitlementsFilePath;
- (BOOL)supportsParallelTestingForTestHostStyle:(long long)arg1 isUITestBundle:(BOOL)arg2 isiOSMac:(BOOL)arg3;
@property(readonly) IDEExtendedPlatformInfo *ide_extendedInfo;
@end

