//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEActivityLogSectionRecorder.h>

@class IDEActivityLogCommandInvocationSection;

@interface IDEActivityLogCommandInvocationSectionRecorder : IDEActivityLogSectionRecorder
{
}

- (void)stopRecordingWithResult:(long long)arg1;
@property(readonly) IDEActivityLogCommandInvocationSection *section;

@end

