//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEBatchFindAbstractPathComponentPredicate.h>

@interface IDEBatchFindFileNamePredicate : IDEBatchFindAbstractPathComponentPredicate
{
}

+ (id)propertyListIdentifier;
- (id)extractComponent:(id)arg1;

@end

