//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTXMLUnarchiving-Protocol.h>

@class IDEBuildSchemeAction, IDESchemeBuildableReference, NSArray, NSString, _TtC13IDEFoundation26IDESchemeTestPlanReference;

@interface IDEBuildActionEntry : NSObject <DVTXMLUnarchiving>
{
    BOOL _isExplicitEntry;
    BOOL _shouldBuildForRunning;
    BOOL _mustBuildForRunning;
    BOOL _shouldBuildForTesting;
    BOOL _mustBuildForTesting;
    BOOL _shouldBuildForProfiling;
    BOOL _mustBuildForProfiling;
    BOOL _shouldBuildForPreviewing;
    BOOL _mustBuildForPreviewing;
    BOOL _shouldBuildForArchiving;
    BOOL _shouldBuildForAnalyzing;
    BOOL _shouldHideIssues;
    IDESchemeBuildableReference *_primaryBuildableReference;
    _TtC13IDEFoundation26IDESchemeTestPlanReference *_testPlanReference;
    IDEBuildSchemeAction *_buildAction;
}

+ (id)keyPathsForValuesAffectingCanRemoveEntry;
+ (id)keyPathsForValuesAffectingShouldBuildForPreviewing;
+ (id)keyPathsForValuesAffectingShouldBuildForProfiling;
+ (id)keyPathsForValuesAffectingShouldBuildForTesting;
+ (id)keyPathsForValuesAffectingShouldBuildForRunning;
- (void).cxx_destruct;
@property(retain) IDEBuildSchemeAction *buildAction; // @synthesize buildAction=_buildAction;
@property(readonly) _TtC13IDEFoundation26IDESchemeTestPlanReference *testPlanReference; // @synthesize testPlanReference=_testPlanReference;
@property(readonly) IDESchemeBuildableReference *primaryBuildableReference; // @synthesize primaryBuildableReference=_primaryBuildableReference;
@property(nonatomic) BOOL mustBuildForPreviewing; // @synthesize mustBuildForPreviewing=_mustBuildForPreviewing;
@property(nonatomic) BOOL mustBuildForProfiling; // @synthesize mustBuildForProfiling=_mustBuildForProfiling;
@property(nonatomic) BOOL mustBuildForTesting; // @synthesize mustBuildForTesting=_mustBuildForTesting;
@property(nonatomic) BOOL mustBuildForRunning; // @synthesize mustBuildForRunning=_mustBuildForRunning;
@property(readonly) BOOL isExplicitEntry; // @synthesize isExplicitEntry=_isExplicitEntry;
- (void)addTestPlanReference:(id)arg1 fromXMLUnarchiver:(id)arg2;
- (void)addBuildableReference:(id)arg1 fromXMLUnarchiver:(id)arg2;
- (void)setHideIssuesFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;
- (void)setBuildForAnalyzingFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;
- (void)setBuildForArchivingFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;
- (void)setBuildForPreviewingFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;
- (void)setBuildForProfilingFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;
- (void)setBuildForTestingFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;
- (void)setBuildForRunningFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)arg1 version:(id)arg2;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1 version:(id)arg2;
- (void)enableBuildEntry;
- (void)disableBuildEntry;
@property(readonly) BOOL canRemoveEntry;
@property BOOL shouldHideIssues;
@property BOOL shouldBuildForAnalyzing;
@property BOOL shouldBuildForArchiving;
@property BOOL shouldBuildForPreviewing;
@property BOOL shouldBuildForProfiling;
@property BOOL shouldBuildForTesting;
@property BOOL shouldBuildForRunning;
- (void)_makeExplicit;
@property(readonly) NSString *name;
@property(readonly) IDESchemeBuildableReference *buildableReference;
- (BOOL)containsBuildableReferenceMatchingReference:(id)arg1;
@property(readonly) NSArray *buildableReferences;
- (void)dvt_awakeFromXMLUnarchiver:(id)arg1;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
- (id)initWithPrimaryBuildableReference:(id)arg1 testPlanReference:(id)arg2 buildAction:(id)arg3 explicityManaged:(BOOL)arg4;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

