//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IDENoticeCollator, NSArray;
@protocol DVTCancellable, DVTInvalidation, IDEBuildNoticeLogSection, IDEBuildNoticeLogStore;

@protocol IDEBuildNoticeWorkspace
- (id <IDEBuildNoticeLogStore>)makeLogStoreForNoticeLogs;
- (id <DVTInvalidation>)observeActiveBlueprintLogSectionIDs:(void (^)(void))arg1;
- (id <DVTCancellable>)observeLatestBuildLogIdentityDidChange:(void (^)(void))arg1;
- (NSArray *)activeBlueprintLogSectionIDs;
@property(nonatomic, readonly) id <IDEBuildNoticeLogSection> latestBuildLogForBuildNoticeProvider;
@property(nonatomic, readonly) IDENoticeCollator *noticeCollator;
@end

