//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDECodeCoverageProviding-Protocol.h>

@class IDESchemeBuildableReference, NSArray;

@protocol IDECodeCoverageMutating <IDECodeCoverageProviding>
@property(readonly, nonatomic) NSArray *codeCoverageTargets;
@property(nonatomic) BOOL onlyGenerateCoverageForSpecifiedTargets;
@property(nonatomic, getter=isCodeCoverageEnabled) BOOL codeCoverageEnabled;
- (void)removeCodeCoverageTarget:(IDESchemeBuildableReference *)arg1;
- (void)addCodeCoverageTarget:(IDESchemeBuildableReference *)arg1;
@end

