//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDEDistributionManifest : NSObject
{
    NSString *_name;
    NSString *_bundleIdentifier;
    NSString *_platformIdentifier;
    NSString *_bundleVersion;
    NSString *_appURL;
    NSString *_displayImageURL;
    NSString *_fullSizeImageURL;
    NSString *_assetPackManifestURL;
}

+ (id)variantDescriptorsForDistributionCoalescedThinningVariant:(id)arg1 includeDescriptorsForLegacyPlatforms:(BOOL)arg2;
+ (id)minimumDeploymentTargetDistributionCoalescedThinningVariantToDeviceIdentifierSet:(id)arg1;
- (void).cxx_destruct;
@property(copy) NSString *assetPackManifestURL; // @synthesize assetPackManifestURL=_assetPackManifestURL;
@property(copy) NSString *fullSizeImageURL; // @synthesize fullSizeImageURL=_fullSizeImageURL;
@property(copy) NSString *displayImageURL; // @synthesize displayImageURL=_displayImageURL;
@property(copy) NSString *appURL; // @synthesize appURL=_appURL;
@property(copy) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(copy) NSString *platformIdentifier; // @synthesize platformIdentifier=_platformIdentifier;
@property(copy) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(copy) NSString *name; // @synthesize name=_name;
- (id)dictionaryRepresentationForDistributionCoalescedThinningVariants:(id)arg1 processedTopLevelDistributionItems:(id)arg2 error:(id *)arg3;
- (BOOL)isValidManifest;
- (BOOL)validateAssetPackManifestURL:(id *)arg1 error:(id *)arg2;
- (BOOL)validateFullSizeImageURL:(id *)arg1 error:(id *)arg2;
- (BOOL)validateDisplayImageURL:(id *)arg1 error:(id *)arg2;
- (BOOL)validateAppURL:(id *)arg1 error:(id *)arg2;
- (BOOL)_validateURL:(id)arg1 propertyName:(id)arg2 error:(id *)arg3;

@end

