//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEDistributionStep.h>

@class NSString;

@interface IDEDistributionProcessingStep : IDEDistributionStep
{
}

+ (_Bool)runsPerThinningVariant;
+ (_Bool)runsPerDistributionItem;
+ (_Bool)supportsDryRun;
+ (id)providedOutputContextPropertyNames;
+ (id)requiredInputContextPropertyNames;
@property(readonly) NSString *name;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;
- (_Bool)runWithError:(id *)arg1;
- (_Bool)shouldSkip;

@end

