//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class DVTFilePath, NSString;
@protocol IDEDistributableContent, IDEDistributableEventRecording;

@protocol IDEDistributable
@property(readonly) DVTFilePath *dSYMDirectoryPath;
@property(readonly) DVTFilePath *productDefinitionPlistPath;
@property(readonly) id <IDEDistributableEventRecording> recorder;
@property(readonly) id <IDEDistributableContent> content;
@property(readonly) DVTFilePath *productsDirectoryPath;
@property(readonly) DVTFilePath *path;
@property(readonly, copy) NSString *name;
@end

