//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTDefaultPolicyCacheDeleteExtension.h>

@class DVTFilePath;

@interface IDEDeviceSupportCacheDeleteExtension : DVTDefaultPolicyCacheDeleteExtension
{
    DVTFilePath *_userLibraryXcodeLocation;
}

+ (long long)maximumCacheAgeAllowedInDays;
+ (BOOL)enableDeviceSupportCacheCleanup;
+ (void)_setupUserDefaults;
- (void).cxx_destruct;
@property(readonly) DVTFilePath *userLibraryXcodeLocation; // @synthesize userLibraryXcodeLocation=_userLibraryXcodeLocation;
- (id)itemsWithError:(id *)arg1;
- (id)_directoriesToDelete;
- (id)_userDeviceSupportDirectories;
- (id)init;
- (id)initWithUserXcodeLocation:(id)arg1;

@end

