//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEDistributionOption.h>

@interface IDEDistributionOptionStripSwiftSymbols : IDEDistributionOption
{
}

+ (BOOL)isApplicableForContext:(id)arg1;
+ (id)propertyListForContext:(id)arg1;
+ (id)availableOptionsForPropertyList;
- (BOOL)loadFromExportOptions:(id)arg1 error:(id *)arg2;
- (id)initWithIdentifier:(id)arg1 context:(id)arg2;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;

@end

