//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEDistributionProcessingPackagingStep.h>

@interface IDEDistributionCreatePKGStep : IDEDistributionProcessingPackagingStep
{
}

+ (id)packagePathExtension;
+ (_Bool)supportsDryRun;
+ (BOOL)wantsPayloadDir;
- (_Bool)runWithError:(id *)arg1;
- (id)name;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;

@end

