//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/NSObject-Protocol.h>

@protocol IDEPortalInfoDelegate, IDEProjectItem;

@protocol IDEFlightCheckingContext <NSObject>
- (id)initWithPortalInfoDelegate:(id <IDEPortalInfoDelegate>)arg1 item:(id <IDEProjectItem>)arg2;
@end

