//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDEIndexCompileCrashNotification : NSObject
{
    NSString *_toolID;
}

@property(retain) NSString *toolID; // @synthesize toolID=_toolID;
- (void).cxx_destruct;
- (id)initWithToolID:(id)arg1;

@end

