//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTDeveloperAccount, IDEITunesConnectConfigurationResponse;

@interface IDEITunesAccountStoreConfigurationResult : NSObject
{
    DVTDeveloperAccount *_account;
    IDEITunesConnectConfigurationResponse *_configurationResponse;
}

@property(readonly) IDEITunesConnectConfigurationResponse *configurationResponse; // @synthesize configurationResponse=_configurationResponse;
@property(readonly) DVTDeveloperAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)initWithDeveloperAccount:(id)arg1 appStoreSubmissionConfiguration:(id)arg2;

@end

