//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDELaunchTestSchemeActionOptions.h>

#import <IDEFoundation/IDELaunchTestSchemeActionResolvedOptions-Protocol.h>

@interface IDELaunchTestSchemeActionOptions (IDEFoundation1) <IDELaunchTestSchemeActionResolvedOptions>
@end

