//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTMemoryFootprintMonitor-Protocol.h>

@class NSTimer;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface IDEMemoryFootprintMonitor : NSObject <DVTMemoryFootprintMonitor>
{
    int _pid;
    NSObject<OS_dispatch_queue> *_physFootprintMonitorQueue;
    NSObject<OS_dispatch_source> *_timer;
    unsigned long long _thresholdInGB;
    NSTimer *_testMemoryTimer;
}

+ (id)sharedFootprintMonitor;
+ (void)initialize;
- (void).cxx_destruct;
- (void)_startMonitorWithInterval:(unsigned long long)arg1 thresholdInGB:(unsigned long long)arg2 consecutiveSampleThreshold:(unsigned long long)arg3;
- (void)_disableMallocStackLogging;
- (BOOL)_enableMallocStackLoggingLite;
- (void)startMonitorWithThresholdInGB:(unsigned long long)arg1;
- (void)startMonitor;
- (BOOL)_isTestingEnabled;
- (id)_leaksFilePath;
- (id)_memoryGraphCollector;
- (void)showAlertWithCurrentUsage:(id)arg1;
- (void)showAlertForAbandonedObjectAfterDuration:(double)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)useMemoryForTesting;
- (id)_initForCurrentProcess;

@end

