//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTInvalidation-Protocol.h>
#import <IDEFoundation/NSCopying-Protocol.h>

@class DVTStackBacktrace, IDEWorkspace, NSArray, NSMutableArray, NSString;

@interface IDEMigrationContext : NSObject <DVTInvalidation, NSCopying>
{
    IDEWorkspace *_workspace;
    NSMutableArray *_targets;
    NSMutableArray *_selectedTargets;
    NSMutableArray *_targetsToApplyMigrationSettingsTo;
}

+ (id)buildablesIncludingImplicitDependenciesForWorkspace:(id)arg1 scheme:(id)arg2;
+ (id)buildablesIncludingImplicitDependenciesForWorkspace:(id)arg1 scheme:(id)arg2 includingPackages:(BOOL)arg3;
+ (BOOL)buildableProducesWatchApp:(id)arg1;
+ (Class)migrationTargetSublass;
+ (void)initialize;
- (void).cxx_destruct;
@property(retain) NSMutableArray *selectedTargets; // @synthesize selectedTargets=_selectedTargets;
@property(readonly) NSArray *targetsToApplyMigrationSettingsTo; // @synthesize targetsToApplyMigrationSettingsTo=_targetsToApplyMigrationSettingsTo;
@property(readonly) NSArray *targets; // @synthesize targets=_targets;
- (void)selectDefaultTargets;
@property(retain) IDEWorkspace *workspace;
- (void)primitiveInvalidate;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

