//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEProvisioningRepairStepGenerator.h>

@interface IDEProvisioningRepairStepGenerator_Manual : IDEProvisioningRepairStepGenerator
{
}

- (id)_evaluateProfilesWithSession:(id)arg1 context:(id)arg2 userAction:(id *)arg3 error:(id *)arg4;
- (id)stepsWithSession:(id)arg1 context:(id)arg2 userAction:(id *)arg3 error:(id *)arg4;

@end

