//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString;

@protocol IDEProvisioningBundleIdentifierDataSource
@property(nonatomic, readonly) BOOL isBundleIdentifierReadOnly;
@property(nonatomic, copy) NSString *bundleIdentifier;
@property(nonatomic, readonly) BOOL wantsBundleIdentifierEditing;
@end

