//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEPlaygroundContextSerializerCommon : NSObject
{
}

+ (id)stringAttributeForValue:(id)arg1 name:(id)arg2 allowEmptyValue:(BOOL)arg3 error:(id *)arg4;
+ (id)filename;
+ (id)rootXMLElementFromContext:(id)arg1 error:(id *)arg2;
+ (id)fileWrapperForContext:(id)arg1 error:(id *)arg2;

@end

