//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEProvisionableSnapshot, NSSet, _TtC13IDEFoundation32IDEProvisioningDeviceRequirement;
@protocol IDEProvisioningErrorProvider;

@interface IDEProvisionableStatusEvalutorInputs : NSObject
{
    IDEProvisionableSnapshot *_provisionableSnapshot;
    NSSet *_provisioningProfiles;
    NSSet *_signingCertificates;
    _TtC13IDEFoundation32IDEProvisioningDeviceRequirement *_deviceRequirement;
    long long _automaticLocationStyle;
    id <IDEProvisioningErrorProvider> _errorProvider;
}

+ (id)_processedDeviceRequirement:(id)arg1 usingProvisionableSnapshot:(id)arg2;
+ (id)evaluatorInputsWithProvisionableSnapshot:(id)arg1 provisioningProfiles:(id)arg2 signingCertificates:(id)arg3 deviceRequirement:(id)arg4 automaticLocationStyle:(long long)arg5 errorProvider:(id)arg6;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <IDEProvisioningErrorProvider> errorProvider; // @synthesize errorProvider=_errorProvider;
@property(readonly, nonatomic) long long automaticLocationStyle; // @synthesize automaticLocationStyle=_automaticLocationStyle;
@property(readonly, nonatomic) _TtC13IDEFoundation32IDEProvisioningDeviceRequirement *deviceRequirement; // @synthesize deviceRequirement=_deviceRequirement;
@property(readonly, nonatomic) NSSet *signingCertificates; // @synthesize signingCertificates=_signingCertificates;
@property(readonly, nonatomic) NSSet *provisioningProfiles; // @synthesize provisioningProfiles=_provisioningProfiles;
@property(retain, nonatomic) IDEProvisionableSnapshot *provisionableSnapshot; // @synthesize provisionableSnapshot=_provisionableSnapshot;
- (id)description;

@end

