//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDEProvisioningBasicTeam-Protocol.h>

@class NSString;

@interface IDEProvisioningBasicTeam : NSObject <IDEProvisioningBasicTeam>
{
    BOOL _freeProvisioningTeam;
    NSString *_teamID;
    NSString *_teamName;
}

+ (id)basicTeamWithID:(id)arg1 name:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic, getter=isFreeProvisioningTeam) BOOL freeProvisioningTeam; // @synthesize freeProvisioningTeam=_freeProvisioningTeam;
@property(readonly, nonatomic) NSString *teamName; // @synthesize teamName=_teamName;
@property(readonly, nonatomic) NSString *teamID; // @synthesize teamID=_teamID;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithTeamID:(id)arg1 teamName:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

