//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDERefactoringKeyValueAccessorMethodDescriptor : NSObject
{
    NSString *_methodName;
    int _keyStyle;
    unsigned long long _indexOfKey;
}

- (void).cxx_destruct;
@property(readonly) unsigned long long indexOfKey; // @synthesize indexOfKey=_indexOfKey;
@property(readonly) int keyStyle; // @synthesize keyStyle=_keyStyle;
@property(readonly) NSString *methodName; // @synthesize methodName=_methodName;
- (id)description;
- (id)initWithMethodName:(const char *)arg1 keyStyle:(int)arg2 indexOfKey:(unsigned long long)arg3;

@end

