//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, _TtC13IDEFoundation26SigningEditorConfiguration;
@protocol IDEProvisioningAssetSelectionDataSourceProvider;

@protocol IDESigningEditorAssetSelectionDataSourceProvider
@property(nonatomic, readonly) NSArray *dataSources;
@property(nonatomic, retain) _TtC13IDEFoundation26SigningEditorConfiguration *configuration;
@property(nonatomic, readonly) id <IDEProvisioningAssetSelectionDataSourceProvider> manager;
@end

