//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDESourceKitRequestDictionaryWrapper-Protocol.h>

@class IDESourceKitRequestDictionary;

@interface IDESourceKitRequestToolchainInfo : NSObject <IDESourceKitRequestDictionaryWrapper>
{
    IDESourceKitRequestDictionary *_dict;
}

- (void).cxx_destruct;
- (id)internalDictionary;
- (id)initWithUIDSet:(id)arg1 identifier:(id)arg2 name:(id)arg3 filePath:(id)arg4 isDefault:(BOOL)arg5 disableClientResponseHandling:(id)arg6;

@end

