//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDESourceKitVariantDictionaryWrapper.h>

@class IDESourceKitResponseStringArray;

@interface IDESourceKitResponseAllSymbolNames : IDESourceKitVariantDictionaryWrapper
{
}

@property(readonly) IDESourceKitResponseStringArray *results;

@end

