//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDESourceKitResponse;

@interface IDESourceKitVariantWrapper : NSObject
{
    CDStruct_4c46f3f5 _obj;
    IDESourceKitResponse *_response;
}

- (void).cxx_destruct;
- (id)description;
- (id)response;
- (id)initWithSourceKitObject:(CDStruct_4c46f3f5)arg1 response:(id)arg2;

@end

