//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDELaunchSession.h>

@class NSString;

@interface IDESyntheticLaunchSession : IDELaunchSession
{
    NSString *_debuggingAdditionIdentifier;
}

@property(copy) NSString *debuggingAdditionIdentifier; // @synthesize debuggingAdditionIdentifier=_debuggingAdditionIdentifier;
- (void).cxx_destruct;
- (void)_didStart;
- (BOOL)supportsDebugSession;

@end

