//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTPlatform, NSArray, NSMutableDictionary, NSString;

@interface IDETemplateSection : NSObject
{
    NSMutableDictionary *_templateCategoriesByName;
    NSString *_explicitName;
    BOOL _showsCategoriesAsChildren;
    NSArray *_categories;
    DVTPlatform *_platform;
}

+ (id)crossPlatformSectionName;
@property BOOL showsCategoriesAsChildren; // @synthesize showsCategoriesAsChildren=_showsCategoriesAsChildren;
@property(retain) DVTPlatform *platform; // @synthesize platform=_platform;
- (void).cxx_destruct;
@property(readonly) NSArray *templates;
@property(readonly) NSArray *categories; // @synthesize categories=_categories;
- (void)sortAllCategories;
- (void)addTemplate:(id)arg1;
- (id)categoryWithName:(id)arg1;
@property(readonly) NSString *sectionIdentifier;
@property(readonly) NSString *name;
- (id)init;
- (id)initWithName:(id)arg1;
- (id)initWithPlatform:(id)arg1;

@end

