//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEPlaygroundResult.h>

@class NSDate;

@interface IDETimestampedPlaygroundResult : IDEPlaygroundResult
{
    NSDate *_date;
}

@property(readonly) NSDate *date; // @synthesize date=_date;
- (void).cxx_destruct;
- (id)initWithChannelIdentifier:(id)arg1 subjectIdentifier:(id)arg2 resultDate:(id)arg3;

@end

