//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDETestApplicationDependencyMapper : NSObject
{
}

+ (id)_dependencySearchErrorFromFileManagerError:(id)arg1 forDirectory:(id)arg2;
+ (id)_bundleIDReadErrorForURL:(id)arg1 domain:(id)arg2 code:(long long)arg3 reason:(id)arg4;
+ (id)_deduceInfoDictionaryReadFailureForApplicationAtURL:(id)arg1;
+ (id)bundleIdentifierForApplicationAtURL:(id)arg1 error:(id *)arg2;
+ (id)_bundleIdentifierMapForApplicationsAtURLs:(id)arg1 areAllApplicationsRequired:(BOOL)arg2 error:(id *)arg3;
+ (id)_applicationsInDirectories:(id)arg1 error:(id *)arg2;
+ (id)bundleIdentifierMapWithDependentProductPaths:(id)arg1 searchDirectories:(id)arg2 error:(id *)arg3;

@end

