//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDELaunchTestSchemeActionResolvedOptions-Protocol.h>
#import <IDEFoundation/IDETestPlanOptions-Protocol.h>

@protocol IDETestPlanResolvedOptions <IDELaunchTestSchemeActionResolvedOptions, IDETestPlanOptions>
@end

