//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface IDEXCTestRunFileSerialization : NSObject
{
    NSArray *_testRunSpecificationGroups;
    NSArray *_codeCoverageBuildableInfos;
    long long _version;
}

+ (id)fileNameForTestRunFileWithSchemeName:(id)arg1 testPlanName:(id)arg2 runDestinationIdentifier:(id)arg3;
+ (id)testRunFileWithContentsOfURL:(id)arg1 derivedDataPath:(id)arg2 error:(id *)arg3;
+ (id)testRunFileWithDictionaryRepresentation:(id)arg1 removingPathPlaceholdersForTestRootPath:(id)arg2 derivedDataPath:(id)arg3 error:(id *)arg4;
@property(readonly) long long version; // @synthesize version=_version;
@property(readonly, copy) NSArray *codeCoverageBuildableInfos; // @synthesize codeCoverageBuildableInfos=_codeCoverageBuildableInfos;
@property(readonly, copy) NSArray *testRunSpecificationGroups; // @synthesize testRunSpecificationGroups=_testRunSpecificationGroups;
- (void).cxx_destruct;
- (BOOL)writeToURL:(id)arg1 derivedDataPath:(id)arg2 error:(id *)arg3;
- (id)dictionaryRepresentationWithPlaceholdersForTestRootPath:(id)arg1 derivedDataPath:(id)arg2;
- (id)initWithTestRunSpecificationGroups:(id)arg1 codeCoverageBuildableInfos:(id)arg2 version:(long long)arg3;

@end

