//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface IPAToolDevice : NSObject
{
    MISSING_TYPE *identifier;
    MISSING_TYPE *displayName;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
- (id)initWithIdentifier:(id)arg1 displayName:(id)arg2;
@property(nonatomic, readonly) NSString *displayName;
@property(nonatomic, readonly) NSString *identifier;

@end

