//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _TtCV5UVKit19DiagnosticsPullDown10MenuTarget : NSObject
{
    // Error parsing type: , name: fileRadarCallback
    // Error parsing type: , name: revealInFinderCallback
}

- (void).cxx_destruct;
- (id)init;
- (void)revealInFinder:(id)arg1;
- (void)fileRadar:(id)arg1;

@end

