//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC5UVKit21DragDestinationNSView : NSView
{
    MISSING_TYPE *_interactionResolver;
    MISSING_TYPE *_interactions;
    MISSING_TYPE *_isActivelyDragging;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) BOOL flipped;
- (BOOL)isFlipped;

@end

