//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEInspectorCategoryController.h>

__attribute__((visibility("hidden")))
@interface _TtC5UVKit27InspectorCategoryController : IDEInspectorCategoryController
{
}

- (id)init;
- (id)initWithCategoryExtension:(id)arg1;
- (id)extensionMatchedInspectorsForInspectedNavigables:(id)arg1 withWorkspaceDocument:(id)arg2;

@end

