//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UVKit/NSObject-Protocol.h>

@class DVTProcessInformation, NSError;

@protocol IDEAttachToProcessErrorHandler <NSObject>

@optional
- (void)showAlertForNonAttachableArchitecture:(DVTProcessInformation *)arg1;
- (void)handleAttachToProcessError:(NSError *)arg1;
@end

