//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UVKit/NSObject-Protocol.h>

@class NSMenu, NSPopUpButtonCell;

@protocol UVPopUpButtonCellDelegate <NSObject>
- (void)popUpButtonCell:(NSPopUpButtonCell *)arg1 willShowMenu:(NSMenu *)arg2;
@end

