//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCSAdministration/XCSInitializationOperation.h>

@class NSString;

@interface XCSCreateDirectoriesOperation : XCSInitializationOperation
{
    NSString *_sharedDataPath;
}

@property(retain, nonatomic) NSString *sharedDataPath; // @synthesize sharedDataPath=_sharedDataPath;
- (void).cxx_destruct;
- (void)undo;
- (id)undoStatusDescription;
- (void)run;
- (BOOL)sharedDataSymlinkNeeded;
- (BOOL)dataExistsAtPreviousLocation;
- (id)statusDescription;

@end

