//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface XCSDesignDocument : NSObject
{
    NSDictionary *_JSON;
}

+ (id)designDocumentsInDirectory:(id)arg1;
- (void).cxx_destruct;
@property(readonly) NSDictionary *JSON; // @synthesize JSON=_JSON;
- (id)designDocumentWithRevision:(id)arg1;
@property(readonly) NSString *anyViewName;
@property(readonly) NSString *JSONString;
@property(readonly) NSString *name;
- (id)initWithJSON:(id)arg1;
- (id)initWithContentsOfDirectory:(id)arg1;

@end

