//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <XCSAdministration/XCSInitializationOperation.h>

@class NSString;

@interface XCSMoveDataOperation : XCSInitializationOperation
{
    NSString *_destinationDataPath;
}

@property(retain, nonatomic) NSString *destinationDataPath; // @synthesize destinationDataPath=_destinationDataPath;
- (void).cxx_destruct;
- (void)run;
- (id)statusDescription;

@end

