//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface _TtC15DVTSourceEditor23DVTSourceEditorLandmark : NSObject
{
    // Error parsing type: , name: landmark
    // Error parsing type: , name: _children
    // Error parsing type: , name: parent
    // Error parsing type: , name: owner
}

- (void).cxx_destruct;
- (id)init;
- (void)invalidate;
- (void)primitiveInvalidate;
@property(nonatomic, retain) NSMutableArray *_children; // @synthesize _children;

@end

