//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s12SourceEditor0aB4ViewCN.h"

@class MISSING_TYPE;

@interface _TtC15DVTSourceEditor19DVTSourceEditorView : _$s12SourceEditor0aB4ViewCN
{
    MISSING_TYPE *featureControllers;
    MISSING_TYPE *defaultFeatureControllerClasses;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;

@end

