//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s12SourceEditor0aB29NotificationFeatureControllerCN.h"

@interface _TtC15DVTSourceEditorP33_40599006F707B10BAB24F064EF5E006635DVTLineNumbersFontFeatureController : _$s12SourceEditor0aB29NotificationFeatureControllerCN
{
}

@end

