//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUToolsServices/DependencyViewerGraphObject.h>

@class NSMutableArray;
@protocol GPUAbstractTraceGroupItem;

@interface DependencyViewerCluster : DependencyViewerGraphObject
{
    NSMutableArray *_ownedVertices;
    NSMutableArray *_vertices;
    NSMutableArray *_clusters;
    DependencyViewerCluster *_parent;
    id <GPUAbstractTraceGroupItem> _outlineItem;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) __weak id <GPUAbstractTraceGroupItem> outlineItem; // @synthesize outlineItem=_outlineItem;
@property(readonly, nonatomic) __weak DependencyViewerCluster *parent; // @synthesize parent=_parent;
- (BOOL)isEqual:(id)arg1;
- (id)title;
- (id)clusters;
- (id)ownedVertices;
- (id)root;
- (void)addCluster:(id)arg1;
- (void)addVertex:(id)arg1 owned:(BOOL)arg2;
- (id)initWithID:(unsigned long long)arg1 graph:(id)arg2 data:(id)arg3 outlineItem:(id)arg4 parent:(id)arg5;

@end

