//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUToolsServices/DYInvestigatorRecommendationItem.h>

@class NSAttributedString;

@interface DYInvestigatorRecommendationItemText : DYInvestigatorRecommendationItem
{
    NSAttributedString *value;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSAttributedString *value; // @synthesize value;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithString:(id)arg1;
- (id)initWithAttributedString:(id)arg1;

@end

