//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUToolsServices/DYLocalLaunchStrategy.h>

__attribute__((visibility("hidden")))
@interface DYNSWorkspaceLaunchStrategy : DYLocalLaunchStrategy
{
}

- (id)urlForBundleIdentifier:(id)arg1;
- (int)launchURL:(id)arg1 launchDictionary:(id)arg2 error:(id *)arg3;

@end

