//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError;
@protocol NSObject;

@interface _TtC13DVTFoundation15OpaqueJobResult : NSObject
{
    // Error parsing type: , name: error
    // Error parsing type: , name: result
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithResult:(id)arg1;
- (id)initWithError:(id)arg1;
@property(nonatomic, readonly) id <NSObject> result; // @synthesize result;
@property(nonatomic, readonly) NSError *error;

@end

