//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC13DVTFoundation9OpaqueJob : NSObject
{
    // Error parsing type: , name: job
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithKey:(id)arg1 work:(CDUnknownBlockType)arg2;

@end

