//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTDiffDataSource;

@protocol DVTDiffHashing
- (unsigned long long)dvt_diffHashForDataSource:(DVTDiffDataSource *)arg1;
@end

