//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTFoundation/NSCopying-Protocol.h>

@interface DVTDiffFNVHashCache : NSObject <NSCopying>
{
    long long *_modifiedFNVHash;
    long long _modifiedFNVHashLength;
    long long *_originalFNVHash;
    long long _originalFNVHashLength;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setOriginalFNVHashLength:(long long)arg1;
- (long long)originalFNVHashLength;
- (void)setOriginalFNVHash:(long long *)arg1;
- (long long *)originalFNVHash;
- (void)setModifiedFNVHashLength:(long long)arg1;
- (long long)modifiedFNVHashLength;
- (void)setModifiedFNVHash:(long long *)arg1;
- (long long *)modifiedFNVHash;
- (id)init;
- (void)dealloc;

@end

