//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTWeakInterposer.h>

@interface DVTWeakInterposer_RuntimeWeakReference : DVTWeakInterposer
{
    id _representedObject;
}

@property __weak id representedObject; // @synthesize representedObject=_representedObject;
- (void).cxx_destruct;

@end

