//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEiOSSupportCore/IDERuniPhoneSimulatorService.h>

@interface IDEDebugiPhoneSimulatorService : IDERuniPhoneSimulatorService
{
}

+ (id)serviceIdentifierKey;
- (id)capabilitySequenceForLaunchSession:(id)arg1;

@end

