//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class MISSING_TYPE, NSTextField, _TtC11GPUDebugger49GPUTraceShaderProfilerAnnotationTooltipLegendView;

__attribute__((visibility("hidden")))
@interface _TtC11GPUDebugger36GPUTraceShaderProfilerLegendCellView : NSTableCellView
{
    MISSING_TYPE *legendView;
    MISSING_TYPE *legendTitle;
    MISSING_TYPE *legendValue;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *legendValue; // @synthesize legendValue;
@property(nonatomic, retain) NSTextField *legendTitle; // @synthesize legendTitle;
@property(nonatomic, retain) _TtC11GPUDebugger49GPUTraceShaderProfilerAnnotationTooltipLegendView *legendView; // @synthesize legendView;

@end

