//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/_TtC11GPUDebugger36GPULandingPageTimelineCollectionView.h>

@interface _TtC11GPUDebugger36GPULandingPageTimelineCollectionView (GPUDebugger)
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)updateTrackingAreas;
@end

