//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUDebugger/_TtC11GPUDebugger24GPUMemoryReportSubEditor.h>

#import <GPUDebugger/NSSplitViewDelegate-Protocol.h>

@interface _TtC11GPUDebugger24GPUMemoryReportSubEditor (GPUDebugger2) <NSSplitViewDelegate>
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (BOOL)splitView:(id)arg1 shouldAdjustSizeOfSubview:(id)arg2;
- (void)splitViewDidResizeSubviews:(id)arg1;
@end

