//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/_TtC11GPUDebugger26GPUShaderDebuggerImageView.h>

#import <GPUDebugger/NSAccessibilityGroup-Protocol.h>

@interface _TtC11GPUDebugger26GPUShaderDebuggerImageView (GPUDebugger) <NSAccessibilityGroup>
- (id)accessibilitySelectedChildren;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityLabel;
@property(nonatomic, readonly) id accessibilityFocusedUIElement;
- (id)accessibilityChildren;
- (id)accessibilityVisibleChildren;
@end

