//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/_TtC11GPUDebugger23GPUTraceSourceSubEditor.h>

#import <GPUDebugger/GPUTraceShaderDataProviderDelegate-Protocol.h>

@interface _TtC11GPUDebugger23GPUTraceSourceSubEditor (GPUDebugger1) <GPUTraceShaderDataProviderDelegate>
- (void)workspaceIndexDidUpdate;
- (void)compilerAnnotationDidUpdate;
- (void)annotationDidUpdate;
- (void)sourceDidUpdate;
@end

