//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/_TtC11GPUDebugger26GPUResourcesViewController.h>

#import <GPUDebugger/NSMenuItemValidation-Protocol.h>

@interface _TtC11GPUDebugger26GPUResourcesViewController (GPUDebugger4) <NSMenuItemValidation>
- (void)columnMenu_toggleColumn:(id)arg1;
- (void)contextMenu_selectTag:(id)arg1;
- (void)contextMenu_sortBy:(id)arg1;
- (void)contextMenu_groupBy:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
@end

