//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/NSObject-Protocol.h>

@class NSArray, NSString;
@protocol DYPMemoryCommandBuffer;

@protocol DYPMemoryCommandEncoder <NSObject>
@property(nonatomic, readonly) NSArray *boundResources;
@property(nonatomic, readonly) NSArray *usedResources;
@property(nonatomic, readonly) id <DYPMemoryCommandBuffer> commandBuffer;
@property(nonatomic, readonly) NSString *label;
@property(nonatomic, readonly) unsigned long long encoderType;
@property(nonatomic, readonly) int functionIndexEnd;
@property(nonatomic, readonly) int functionIndexBegin;
@property(nonatomic, readonly) unsigned long long objectID;
@end

