//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/NSObject-Protocol.h>

@class NSMutableArray;

@protocol DYPResourceGroup <NSObject>
@property(retain, nonatomic) NSMutableArray *children;
@property(readonly, nonatomic) struct Function *decodedFunction;
@end

