//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/DYPShaderDebuggerThread-Protocol.h>

@protocol DYPShaderDebuggerThreadKernel <DYPShaderDebuggerThread>
@property(nonatomic, readonly) unsigned long long threadPositionZ;
@property(nonatomic, readonly) unsigned long long threadPositionY;
@property(nonatomic, readonly) unsigned long long threadPositionX;
@end

