//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol GPUAbstractTraceDisplayableItem
- (void)cancelNotifyOnDependencyGraphSortedThumbnailForSender:(id)arg1;
- (void)cancelNotifyOnDependencyGraphThumbnailForSender:(id)arg1;
- (void)notifyWithSender:(id)arg1 onDependencyGraphSortedThumbnail:(void (^)(NSArray *))arg2;
- (void)notifyWithSender:(id)arg1 onDependencyGraphThumbnail:(void (^)(NSDictionary *))arg2;
@end

