//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <GPUDebugger/NSAccessibilityStaticText-Protocol.h>

@class GPUDependencyAccessibilityItem, NSString;

__attribute__((visibility("hidden")))
@interface GPUDependencyAccessibilityTitleItem : NSObject <NSAccessibilityStaticText>
{
    GPUDependencyAccessibilityItem *_parent;
}

- (void).cxx_destruct;
- (id)accessibilityValue;
- (BOOL)isAccessibilitySelected;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityLabel;
- (id)accessibilityParent;
- (struct CGRect)accessibilityFrame;
- (id)accessibilityTitle;
- (id)accessibilityIdentifier;
- (id)initWithParent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

