//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class GPUTraceCounterGraphTabView;

@protocol GPUTraceCounterGraphTabViewDelegate
- (void)tabView:(GPUTraceCounterGraphTabView *)arg1 renameButtonClicked:(unsigned long long)arg2 newName:(void (^)(NSString *))arg3;
- (BOOL)tabView:(GPUTraceCounterGraphTabView *)arg1 canRenameButton:(unsigned long long)arg2;
- (unsigned long long)tabView:(GPUTraceCounterGraphTabView *)arg1 removeButtonClicked:(unsigned long long)arg2;
- (BOOL)tabView:(GPUTraceCounterGraphTabView *)arg1 canRemoveButton:(unsigned long long)arg2;
- (void)tabView:(GPUTraceCounterGraphTabView *)arg1 buttonClicked:(unsigned long long)arg2;
@end

