//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/NSObject-Protocol.h>

@class NSArray;

@protocol GPUTraceCounterGraphTableViewDataSourceDelegate <NSObject>
- (void)sortingFinished;
- (void)sortingStarted:(unsigned long long)arg1;
- (BOOL)requestColumns:(NSArray *)arg1;
@end

