//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpriteKit/SKNode.h>

@class DependencyViewerSKTextureCache, NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface GPUTraceStatBox : SKNode
{
    NSMutableArray *_lines;
    unsigned long long _anchor;
    DependencyViewerSKTextureCache *_textureCache;
    SKNode *_issueBtn;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SKNode *issueBtn; // @synthesize issueBtn=_issueBtn;
- (unsigned long long)numberOfLines;
- (void)highlight:(BOOL)arg1;
- (void)addBadgeLine:(id)arg1;
- (id)addStatWithTitle:(id)arg1 andLabel:(id)arg2;
- (double)height;
@property(readonly, nonatomic) NSArray *statLines;
- (id)initWithAnchor:(unsigned long long)arg1 textureCache:(id)arg2;

@end

