//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GPUDebugger/GPUTraceOutlineItem.h>

@class GPUTraceResourceItem;

@interface GPUTraceDependencyResourceItem : GPUTraceOutlineItem
{
    GPUTraceResourceItem *_wrappedResource;
}

- (void).cxx_destruct;
@property(nonatomic) __weak GPUTraceResourceItem *wrappedResource; // @synthesize wrappedResource=_wrappedResource;
- (id)APIItem;
- (id)label;
- (id)initWithResourceItem:(id)arg1 withParent:(id)arg2;

@end

