//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class DYJSScriptingContext, GPUTraceCounterGraphDataItem, NSArray, NSDictionary, NSString;

@protocol GPUTraceCounterGraphSampleProvider
@property(readonly, nonatomic) NSDictionary *vendorAnalysisConfigurationVariables;
@property(readonly, nonatomic) NSDictionary *vendorAnalysisFunctions;
@property(readonly, nonatomic) NSString *vendorAnalysisScript;
- (void)exportScriptingContext:(DYJSScriptingContext *)arg1 dataItem:(GPUTraceCounterGraphDataItem *)arg2;
- (NSArray *)computeMaskIndices;
- (NSArray *)collectToolsCounters:(GPUTraceCounterGraphDataItem *)arg1;
- (NSArray *)samplesForAnalysis;
- (NSArray *)samplesBase;
- (NSArray *)samples;
@end

