//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class GPUTracePipelineStatisticsDrawcallGraphView;

__attribute__((visibility("hidden")))
@interface GPUTracePipelineStatisticsDrawcallGraphCell : NSTableCellView
{
    GPUTracePipelineStatisticsDrawcallGraphView *_graph;
}

@property __weak GPUTracePipelineStatisticsDrawcallGraphView *graph; // @synthesize graph=_graph;
- (void).cxx_destruct;

@end

