//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class MISSING_TYPE;

@interface NSView (SKEAdditions)
- (MISSING_TYPE *)ske_simdConvertPointFromWindow:(struct CGPoint)arg1;
- (struct CGPoint)ske_convertPointFromWindow:(struct CGPoint)arg1;
- (struct CGPoint)ske_convertPointToWindow:(struct CGPoint)arg1;
@end

