//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEEditorDocument.h>

@class NSArray, SKEAssetCatalog;

@interface SKEAssetCatalogDocument : IDEEditorDocument
{
    SKEAssetCatalog *_assetCatalog;
    NSArray *_scenes;
}

@property(retain) NSArray *scenes; // @synthesize scenes=_scenes;
- (void).cxx_destruct;
- (void)makeCurrent;
@property BOOL preferCompressedTextures;
@property BOOL forceYUp;
- (BOOL)writeSettings;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

