//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDESceneKitEditor/SKEDocumentEdition.h>

@class NSMutableArray;

@interface SKEDocumentRemoveMembersFromDocumentEdition : SKEDocumentEdition
{
    NSMutableArray *_subEditions;
}

- (void).cxx_destruct;
- (BOOL)revert;
- (BOOL)apply;
- (id)initWithDocument:(id)arg1 members:(id)arg2;

@end

