//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDESceneKitEditor/NSKeyedArchiverDelegate-Protocol.h>

@class NSKeyedArchiver, NSString;

@interface SKESceneCustomClassKeyedArchiver : NSObject <NSKeyedArchiverDelegate>
{
    NSKeyedArchiver *_archiver;
}

- (void).cxx_destruct;
- (void)archiver:(id)arg1 didEncodeObject:(id)arg2;
- (id)archiver:(id)arg1 willEncodeObject:(id)arg2;
- (void)finishEncoding;
- (void)encodeObject:(id)arg1 forKey:(id)arg2;
- (void)encodeRootObject:(id)arg1;
- (id)initForWritingWithMutableData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

