//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface SKESceneViewNestView : NSView
{
    NSView *sceneView;
    double _aspectRatio;
}

@property(nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
- (void).cxx_destruct;
- (void)layout;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

