//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEProjectItemModel.h>

@class NSArray, NSString;

@interface Xcode3SafariKeychainItemModel : IDEProjectItemModel
{
    NSArray *_domains;
}

+ (id)coalescableReadOnlyKeyPaths;
@property(copy, nonatomic) NSArray *domains; // @synthesize domains=_domains;
- (void).cxx_destruct;
- (id)coalescableWriteableKeyPathToDataSource;
- (BOOL)isEnabledUsingEducatedGuess;
- (id)flightChecks;
- (id)instantiateEntitlementsFlightCheck;
- (id)defaultDomains;
@property(readonly) NSString *defaultDomain;
- (void)targetCoordinatorsChanged:(id)arg1;
- (void)readValuesFromEntitlements;
- (id)initWithCapabilitiesContext:(id)arg1 item:(id)arg2;

@end

