//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC5Helix10SplitCache : _TtCs12_SwiftObject
{
    MISSING_TYPE *pool;
    MISSING_TYPE *tol;
    MISSING_TYPE *_invalid;
    MISSING_TYPE *_edgeEdge;
    MISSING_TYPE *_facePlunge;
    MISSING_TYPE *_edgeCut;
}

@end

