//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC5Helix13BaseAttribute : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _version
    // Error parsing type: , name: _name
    // Error parsing type: , name: _count
    // Error parsing type: , name: _mainContainerRef
    // Error parsing type: , name: _otherContainerRefs
}

@end

