//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC5Helix24ThickenSkeletonOperation : _TtCs12_SwiftObject
{
    // Error parsing type: , name: flat
    // Error parsing type: , name: defaultNormal
    // Error parsing type: , name: commonOffsets
    // Error parsing type: , name: bevelOffset
    // Error parsing type: , name: _offsets
    // Error parsing type: , name: _edgeOffsets
    // Error parsing type: , name: _newOffsets
    // Error parsing type: , name: _tol
    // Error parsing type: , name: _edges
    // Error parsing type: , name: _indexEdges
    // Error parsing type: , name: _lastMark
    // Error parsing type: , name: _newEdges
}

@end

