//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC5Helix11PolygonMeshP33_4102794486A15CFD329ED01260E0751017MeshRaycastResult : _TtCs12_SwiftObject
{
    MISSING_TYPE *_queryCache;
    MISSING_TYPE *_ray;
    MISSING_TYPE *_doubleSided;
    MISSING_TYPE *_location;
    MISSING_TYPE *_alternateLocation;
    MISSING_TYPE *_alternateLocationDistance;
    MISSING_TYPE *_locationSorter;
    MISSING_TYPE *_tempTrianglesBuffer;
    MISSING_TYPE *_floatPositionBuffer;
    MISSING_TYPE *_doublePositionBuffer;
    MISSING_TYPE *_tol;
    MISSING_TYPE *_tolAsEuclidianDistance;
}

@end

