//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC5Helix11PolygonMeshP33_4102794486A15CFD329ED01260E0751017MeshClosestResult : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _queryCache
    // Error parsing type: , name: _position
    // Error parsing type: , name: _scaling
    // Error parsing type: , name: _hasScaling
    // Error parsing type: , name: _location
    // Error parsing type: , name: _tol
    // Error parsing type: , name: _floatPositionBuffer
    // Error parsing type: , name: _doublePositionBuffer
}

@end

