//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Helix/_TtCC5Helix12BaseGeometry9BBoxCache.h>

@class MISSING_TYPE;

@interface _TtCC5Helix6Points15PointsBBoxCache : _TtCC5Helix12BaseGeometry9BBoxCache
{
    MISSING_TYPE *sizeAttrState;
    MISSING_TYPE *prevDefaultSize;
}

@end

