//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC5Helix9MeshEdits : _TtCs12_SwiftObject
{
    MISSING_TYPE *mesh;
    MISSING_TYPE *polDeleted;
    MISSING_TYPE *polAdd;
    MISSING_TYPE *polReplace;
    MISSING_TYPE *pool;
    MISSING_TYPE *tol;
}

@end

