//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC5Helix16MeshAssetDecoder : _TtCs12_SwiftObject
{
    MISSING_TYPE *mesh;
    MISSING_TYPE *attrNames;
    MISSING_TYPE *bufStride;
    MISSING_TYPE *curmap;
    MISSING_TYPE *vecdata;
    MISSING_TYPE *base;
    MISSING_TYPE *step;
    MISSING_TYPE *floatSize;
}

@end

