//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, NSProgressIndicator;

@interface _TtC8RCShared28ExportProgressViewController : NSViewController
{
    MISSING_TYPE *progressIndicator;
    MISSING_TYPE *progressObserver;
    MISSING_TYPE *progress;
    MISSING_TYPE *cancelExport;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (void)cancel:(id)arg1;
@property(nonatomic) __weak NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;

@end

