//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTabViewController.h>

@class MISSING_TYPE;

@interface _TtC8RCShared22DefaultsBaseController : NSTabViewController
{
    MISSING_TYPE *configuration;
    MISSING_TYPE *defaultsGroups;
}

- (void).cxx_destruct;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

