//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCCC8RCShared29GetScreenShotAutomationAction14ImageRetrieverP33_D3B9A58DC203F97AAD7407C029B6E4E322ImageProcessingContext : _TtCs12_SwiftObject
{
    MISSING_TYPE *windowsToProcess;
    MISSING_TYPE *windowsSuccessful;
    MISSING_TYPE *windowsFailed;
    MISSING_TYPE *processedImages;
}

@end

