//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RCShared/_TtC8RCShared30InspectableEditorCellFromClass.h>

__attribute__((visibility("hidden")))
@interface _TtC8RCShared36CheckmarkToggleInspectableEditorCell : _TtC8RCShared30InspectableEditorCellFromClass
{
    // Error parsing type: , name: labelButton
    // Error parsing type: , name: iconView
    // Error parsing type: , name: checkmarkIcon
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)prepareForReuse;
- (id)init;

@end

