//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <RCShared/_TtC8RCShared12RCScrollView.h>

@interface _TtC8RCShared12RCScrollView (RCShared)
@property(nonatomic) struct CGSize contentSize;
@end

