//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <RCShared/_TtC8RCShared6Action.h>

@class MISSING_TYPE;

@interface _TtC8RCShared9CutAction : _TtC8RCShared6Action
{
    MISSING_TYPE *deleteAction;
    MISSING_TYPE *copyAction;
}

- (void).cxx_destruct;
- (void)performAction;

@end

