//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtC8RCShared20CircularProgressView : NSView
{
    // Error parsing type: , name: ghostRingLayer
    // Error parsing type: , name: indeterminateProgressRingLayer
    // Error parsing type: , name: determinateProgressRingLayer
    // Error parsing type: , name: observeFractionCompleted
    // Error parsing type: , name: observeIsIndeterminate
    // Error parsing type: , name: progress
    // Error parsing type: , name: graduallyIncreasingProgress
    // Error parsing type: , name: observedProgress
    // Error parsing type: , name: activeStrokeColor
    // Error parsing type: , name: inactiveStrokeColor
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layout;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

