//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC8RCShared20TagInspectableEditor : NSObject
{
    MISSING_TYPE *addTagsLabel;
    MISSING_TYPE *editorContextCreator;
    MISSING_TYPE *inspectable;
    MISSING_TYPE *controllerResolver;
    MISSING_TYPE *tagEditor;
    MISSING_TYPE *$__lazy_storage_$_templateCell;
}

- (void).cxx_destruct;
- (id)init;

@end

