//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtC8RCShared21ScenePickerHeaderView : NSView
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: addButton
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: addSceneEventSource
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)applyLayoutAttributes:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

