//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC8RCShared13RCManipulator : NSObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *rootView;
    MISSING_TYPE *gestureView;
    MISSING_TYPE *currentSelection;
    MISSING_TYPE *editingEnabled;
    MISSING_TYPE *cameraControlsEnabled;
    MISSING_TYPE *camera;
    MISSING_TYPE *lastValidCameraPose;
    MISSING_TYPE *_lastSelectionPivot;
    MISSING_TYPE *lastFrameContentPivot;
    MISSING_TYPE *workingPlane;
    MISSING_TYPE *currentManipulationSpace;
    MISSING_TYPE *lockedManipulationSpace;
    MISSING_TYPE *interactionManipulationSpace;
    MISSING_TYPE *manipulationMode;
    MISSING_TYPE *transformMode;
    MISSING_TYPE *commandController;
    MISSING_TYPE *animationManager;
    MISSING_TYPE *hitTester;
    MISSING_TYPE *visualCueManager;
    MISSING_TYPE *resourceManager;
    MISSING_TYPE *lastTapDownTime;
    MISSING_TYPE *cameraAnimationID;
    MISSING_TYPE *_gestureRecognizers;
    MISSING_TYPE *atLeastOneGestureBegan;
    MISSING_TYPE *interactor;
    MISSING_TYPE *hitTestMode;
}

- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

