//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8RCSharedP33_AC88D2CC3172ACAAA1C107938C1DA50A12ActionTarget : NSObject
{
    // Error parsing type: , name: retainCancellable
    // Error parsing type: , name: trigger
    // Error parsing type: , name: control
}

- (void).cxx_destruct;
- (id)init;
- (void)handleAction:(id)arg1;

@end

