//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionViewLayoutInvalidationContext.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtCC8RCShared18BehaviorFlowLayout19InvalidationContext : NSCollectionViewLayoutInvalidationContext
{
    MISSING_TYPE *invalidateDropDecoration;
    MISSING_TYPE *invalidateSections;
    MISSING_TYPE *invalidateCards;
}

- (id)init;

@end

