//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RCShared/_TtC8RCShared30InspectableEditorCellFromClass.h>

__attribute__((visibility("hidden")))
@interface _TtC8RCShared27StringInspectableEditorCell : _TtC8RCShared30InspectableEditorCellFromClass
{
    // Error parsing type: , name: rxStorage
    // Error parsing type: , name: label
    // Error parsing type: , name: valueField
    // Error parsing type: , name: stackView
    // Error parsing type: , name: isEditing
    // Error parsing type: , name: value
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)applyLayoutAttributes:(id)arg1;
- (id)init;

@end

