//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <RCShared/_TtC8RCShared7RCLabel.h>

__attribute__((visibility("hidden")))
@interface _TtC8RCShared14RoundedTextBox : _TtC8RCShared7RCLabel
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

