//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

__attribute__((visibility("hidden")))
@interface _TtC8RCShared20TagColorSelectorCell : NSCollectionViewItem
{
    // Error parsing type: , name: colorView
    // Error parsing type: , name: color
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) BOOL selected;
- (BOOL)isSelected;
- (id)initWithCoder:(id)arg1;

@end

