//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC8RCShared16MultipeerSession : NSObject
{
    MISSING_TYPE *sessionStartTimestamp;
    MISSING_TYPE *rxStorage;
    MISSING_TYPE *mcSession;
    MISSING_TYPE *localPeer;
    MISSING_TYPE *controllers;
    MISSING_TYPE *onSessionWillDisconnectEventSource;
    MISSING_TYPE *onClientDeclineEventSource;
    MISSING_TYPE *peers;
}

- (void).cxx_destruct;
- (id)init;

@end

