//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RCShared/WorkspaceViewControllerShared.h>

@interface WorkspaceViewControllerShared (RCShared)
- (void)toggleBehaviorEditor:(id)arg1;
- (void)showAudioLibrary:(id)arg1;
- (void)showImageLibrary:(id)arg1;
- (void)showModelLibrary:(id)arg1;
- (void)handleAudioLibrary:(id)arg1;
- (void)handleModelLibrary:(id)arg1;
- (void)toggleStyleSettings:(id)arg1;
- (void)toggleBehaviors:(id)arg1;
- (void)toggleScenePicker:(id)arg1;
- (void)toggleManipulatorMode:(id)arg1;
@end

