//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE, _TtC8RCShared11OverlayView;

@interface WorkspaceViewControllerShared : NSViewController
{
    MISSING_TYPE *simulation;
    MISSING_TYPE *scenes;
    MISSING_TYPE *$__lazy_storage_$_infoHubViewController;
    MISSING_TYPE *inspectorStateController;
    MISSING_TYPE *document;
    MISSING_TYPE *currentSelection;
    MISSING_TYPE *isReloading;
    MISSING_TYPE *lastCDNManifestRequest;
    MISSING_TYPE *$__lazy_storage_$_previewManager;
    MISSING_TYPE *$__lazy_storage_$_visualCueManager;
    MISSING_TYPE *sceneScope;
    MISSING_TYPE *onCurrentSceneChange;
    MISSING_TYPE *currentScene;
    MISSING_TYPE *unitSystem;
    MISSING_TYPE *generationCancellableMap;
    MISSING_TYPE *fontScope;
    MISSING_TYPE *onEditingEnabledChange;
    MISSING_TYPE *editingEnabled;
    MISSING_TYPE *visualizationMode;
    MISSING_TYPE *overlayContainerView;
    MISSING_TYPE *assetViewController;
    MISSING_TYPE *actionManager;
    MISSING_TYPE *progress;
    MISSING_TYPE *$__lazy_storage_$_operationQueue;
    MISSING_TYPE *exportScope;
    MISSING_TYPE *sceneGenerationInProgress;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)toggleSettings:(id)arg1;
- (void)toggleProperties:(id)arg1;
- (void)export:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak _TtC8RCShared11OverlayView *overlayContainerView; // @synthesize overlayContainerView;
- (void)togglePlay:(id)arg1;

@end

