//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MLCoreKit/_TtC9MLCoreKit19ComposerOutlineView.h>

@class MISSING_TYPE;

@interface _TtC9MLCoreKit17EditorOutlineView : _TtC9MLCoreKit19ComposerOutlineView
{
    MISSING_TYPE *hideDisclosure;
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layout;
- (struct CGRect)frameOfCellAtColumn:(long long)arg1 row:(long long)arg2;
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1;
- (void)viewWillDraw;

@end

