//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13UVIntegration26LocalMacDestinationManager : _TtCs12_SwiftObject
{
    MISSING_TYPE *destinationStore;
    MISSING_TYPE *queue;
}

@end

