//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UVIntegration/DTXAllowedRPC-Protocol.h>

@class NSNumber, NSString;

@protocol DTProcessControlObserver <DTXAllowedRPC>
- (void)outputReceived:(NSString *)arg1 fromProcess:(int)arg2 atTime:(unsigned long long)arg3;
- (void)pidDiedCallback:(NSNumber *)arg1;
@end

