//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderCocoaIntegration/IBNSCustomView.h>

@interface IBFlippedView : IBNSCustomView
{
}

- (id)ibRuntimeClassName;
- (id)ibTypeNameForDefaultLabel;
- (BOOL)isFlipped;

@end

