//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSliderCell.h>

@interface IBNSViewPrioritySliderCell : NSSliderCell
{
    BOOL _isStartingTracking;
    BOOL _showMultipleValues;
}

@property BOOL showMultipleValues; // @synthesize showMultipleValues=_showMultipleValues;
- (void)stopTracking:(struct CGPoint)arg1 at:(struct CGPoint)arg2 inView:(id)arg3 mouseIsUp:(BOOL)arg4;
- (BOOL)continueTracking:(struct CGPoint)arg1 at:(struct CGPoint)arg2 inView:(id)arg3;
- (BOOL)startTrackingAt:(struct CGPoint)arg1 inView:(id)arg2;
- (id)prioritySlider;

@end

