//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEInterfaceBuilderKit/IBAttributePlaceholder.h>

@class NSString;

@interface IBToolTipAttribute : IBAttributePlaceholder
{
    NSString *_toolTip;
}

+ (void)addToolTipAccessorsToClass:(Class)arg1;
@property(retain) NSString *toolTip; // @synthesize toolTip=_toolTip;
- (void).cxx_destruct;
- (id)archiveConnection;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithObject:(id)arg1 andToolTip:(id)arg2;

@end

