//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSArrayController.h>

#import <IDEInterfaceBuilderCocoaIntegration/IBDocumentArchiving-Protocol.h>

@class NSString;

@interface NSArrayController (IBNSArrayControllerIntegration) <IBDocumentArchiving>
+ (id)ibDynamicShadowedKeyPathsToTypes;
- (id)ibResolvedTypeNameForControllerKey:(id)arg1;
- (id)ibLocalAttributeKeyPaths;
- (void)unarchiveWithDocumentUnarchiver:(id)arg1;
- (void)archiveWithDocumentArchiver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property BOOL ibShadowedAlwaysUsesMultipleValuesMarker; // @dynamic ibShadowedAlwaysUsesMultipleValuesMarker;
@property BOOL ibShadowedAutomaticallyRearrangesObjects; // @dynamic ibShadowedAutomaticallyRearrangesObjects;
@property BOOL ibShadowedAvoidsEmptySelection; // @dynamic ibShadowedAvoidsEmptySelection;
@property BOOL ibShadowedClearsFilterPredicateOnInsertion; // @dynamic ibShadowedClearsFilterPredicateOnInsertion;
@property BOOL ibShadowedPreservesSelection; // @dynamic ibShadowedPreservesSelection;
@property BOOL ibShadowedSelectsInsertedObjects; // @dynamic ibShadowedSelectsInsertedObjects;
@property(readonly) Class superclass;
@end

