//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDETestPlanEditor/_TtC17IDETestPlanEditor27TestPlanTestsViewController.h>

#import <IDETestPlanEditor/IDETestTargetsOutlineViewControllerDataSource-Protocol.h>

@interface _TtC17IDETestPlanEditor27TestPlanTestsViewController (IDETestPlanEditor1) <IDETestTargetsOutlineViewControllerDataSource>
- (id)testableReferencesForTestTargetsViewController:(id)arg1;
@end

