//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDETestPlanEditor/_TtC17IDETestPlanEditor36TestPlanConfigurationsViewController.h>

#import <IDETestPlanEditor/NSSplitViewDelegate-Protocol.h>

@interface _TtC17IDETestPlanEditor36TestPlanConfigurationsViewController (IDETestPlanEditor) <NSSplitViewDelegate>
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
@end

