//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class DVTBorderedView, DVTSearchField, DVTTableView, NSButton;

__attribute__((visibility("hidden")))
@interface _TtC17IDETestPlanEditor46TestPlanConfigurationsSourceListViewController : IDEViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: testPlanEditor
    // Error parsing type: , name: tableView
    // Error parsing type: , name: removeConfigurationsButton
    // Error parsing type: , name: bottomBar
    // Error parsing type: , name: addConfigurationsButton
    // Error parsing type: , name: filterField
    // Error parsing type: , name: activeConfigurationEntries
    // Error parsing type: , name: filterString
    // Error parsing type: , name: configurationsObserver
    // Error parsing type: , name: validityIssuesObserver
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)removeSelectedConfigurations:(id)arg1;
- (void)addConfiguration:(id)arg1;
- (void)filterFieldDidChange:(id)arg1;
- (void)viewDidInstall;
- (void)viewDidLoad;
- (void)primitiveInvalidate;
@property(nonatomic, retain) DVTSearchField *filterField; // @synthesize filterField;
@property(nonatomic, retain) NSButton *addConfigurationsButton; // @synthesize addConfigurationsButton;
@property(nonatomic, retain) DVTBorderedView *bottomBar; // @synthesize bottomBar;
@property(nonatomic, retain) NSButton *removeConfigurationsButton; // @synthesize removeConfigurationsButton;
@property(nonatomic, retain) DVTTableView *tableView; // @synthesize tableView;

@end

