//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEEditor.h>

@class DVTBorderedView, MISSING_TYPE, NSLayoutConstraint, NSScrollView, NSStackView, NSView;

@interface _TtC17IDETestPlanEditor36IDETestReportCallStackCodeRollEditor : IDEEditor
{
    MISSING_TYPE *scrollView;
    MISSING_TYPE *stackView;
    MISSING_TYPE *stackViewContainer;
    MISSING_TYPE *topBarBorderedView;
    MISSING_TYPE *topBarLayoutConstraint;
    MISSING_TYPE *callStackFrameViewControllers;
}

+ (id)defaultViewNibName;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;
- (void)primitiveInvalidate;
- (void)viewDidInstall;
@property(nonatomic, retain) NSLayoutConstraint *topBarLayoutConstraint; // @synthesize topBarLayoutConstraint;
@property(nonatomic) __weak DVTBorderedView *topBarBorderedView; // @synthesize topBarBorderedView;
@property(nonatomic) __weak NSView *stackViewContainer; // @synthesize stackViewContainer;
@property(nonatomic) __weak NSStackView *stackView; // @synthesize stackView;
@property(nonatomic) __weak NSScrollView *scrollView; // @synthesize scrollView;

@end

