//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDETestPlanEditor/NSObject-Protocol.h>
#import <IDETestPlanEditor/NSUserInterfaceValidations-Protocol.h>

@protocol IDECommandHandler <NSObject, NSUserInterfaceValidations>
@end

