//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SKScanFileInfo;

__attribute__((visibility("hidden")))
@interface _SKUnitTestScanDataForFile : NSObject
{
    SKScanFileInfo *_scanInfo;
}

- (void).cxx_destruct;
- (BOOL)update:(id)arg1;
- (BOOL)hasSymbols;

@end

