//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SKIndex/IDEIndexContainerSymbol.h>

__attribute__((visibility("hidden")))
@interface IDEIndexProtocolSymbol : IDEIndexContainerSymbol
{
}

- (id)implementingClasses;

@end

