//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SKIndex/NSObject-Protocol.h>

@class NSDictionary, SKScanIndex;

@protocol SKScannedFilesDelegate <NSObject>
- (void)scannedSymbols:(NSDictionary *)arg1 scanIndex:(SKScanIndex *)arg2;
@end

