//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SKIndex/SKSourceScanner-Protocol.h>

@class NSString, SKToolchainService;

__attribute__((visibility("hidden")))
@interface SKSwiftSourceScanner : NSObject <SKSourceScanner>
{
    SKToolchainService *_toolchain;
}

- (void).cxx_destruct;
- (shared_ptr_fa216b61)scanFile:(id)arg1 error:(id *)arg2;
- (id)initWithToolchain:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

