//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _DVTDefaultSourceLanguageServiceFormatOptions : NSObject
{
    BOOL _useTabs;
    long long _indentWidth;
    long long _tabWidth;
}

@property long long tabWidth; // @synthesize tabWidth=_tabWidth;
@property long long indentWidth; // @synthesize indentWidth=_indentWidth;
@property BOOL useTabs; // @synthesize useTabs=_useTabs;

@end

