//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DebugHierarchyFoundation/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol DebugHierarchyEntryPoint_Fallback <NSObject>
+ (NSArray *)fallback_debugHierarchyObjectsInGroupWithID:(NSString *)arg1 outOptions:(id *)arg2;
+ (NSArray *)fallback_debugHierarchyGroupingIDs;
@end

