//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7Protein16ActionsEvaluator : _TtCs12_SwiftObject
{
    MISSING_TYPE *additionalActionsToCheck;
    MISSING_TYPE *additionalDataObjectsToCheck;
    MISSING_TYPE *actionsToEvaluateCollector;
    MISSING_TYPE *cannotEvaluateActionsSet;
    MISSING_TYPE *canEvaluateActionsPriorityQueue;
    MISSING_TYPE *context;
}

@end

