//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7Protein16Curve3dObjectImp : _TtCs12_SwiftObject
{
    MISSING_TYPE *_owner;
    MISSING_TYPE *_curveData;
}

@end

