//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Protein/_TtC7Protein15GeometricObject.h>

@class MISSING_TYPE;

@interface _TtC7Protein11SmartObject : _TtC7Protein15GeometricObject
{
    MISSING_TYPE *asAction;
    MISSING_TYPE *ownedDataObjects;
    MISSING_TYPE *ownedActions;
    MISSING_TYPE *ownedActionsToEvaluate;
    MISSING_TYPE *attachers;
    MISSING_TYPE *exposedConnectableAliases;
    MISSING_TYPE *exposedConnectorAliases;
    MISSING_TYPE *placeholderDataObjects;
}

@end

