//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Protein/_TtC7Protein6Action.h>

@interface _TtC7Protein18ExtrudedMeshAction : _TtC7Protein6Action
{
}

@end

