//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/DVTInvalidation-Protocol.h>
#import <DevToolsCore/NSObject-Protocol.h>

@class DVTFilePath, NSString;

@protocol IDEInfoPlistCoordination <NSObject, DVTInvalidation>
@property(readonly, nonatomic) BOOL infoPlistFileExists;
@property(readonly, nonatomic) DVTFilePath *infoPlistFilePath;
- (void)removeRequiredCapabilityWithKey:(NSString *)arg1;
- (BOOL)requiredCapabilitiesStateForKey:(NSString *)arg1;
- (void)removePlistSetting:(NSString *)arg1;
- (void)removeValue:(id)arg1 fromArrayForPlistSetting:(NSString *)arg2;
- (void)addRequiredCapabilityWithKey:(NSString *)arg1;
- (void)addValue:(id)arg1 toArrayForPlistSetting:(NSString *)arg2;
- (void)setValue:(id)arg1 forPlistSetting:(NSString *)arg2;
- (id)valueForPlistSetting:(NSString *)arg1 ofType:(Class)arg2;
- (id)valueForPlistSetting:(NSString *)arg1;
@end

