//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (PBXPListASCIIDescription)
- (void)_appendPListDescriptionToUTF8Data:(id)arg1 withIndentLevel:(unsigned long long)arg2;
- (void)_appendPListDescriptionToString:(id)arg1 withIndentLevel:(unsigned long long)arg2;
@end

