//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTDerivedFileSystemContentGenerator.h>

@class NSArray, NSString;

@interface PBXProjectAutoregenerator : DVTDerivedFileSystemContentGenerator
{
    NSArray *_commandLine;
    NSString *_launchDirPath;
}

- (void).cxx_destruct;
- (void)generateContents;
- (id)searchPathForCommandLineExecutable;
- (id)archivableInfoDictionary;
- (id)initWithInfoDictionary:(id)arg1 projectDirectory:(id)arg2 error:(id *)arg3;
- (id)initWithSourcePath:(id)arg1 commandLine:(id)arg2 launchDirPath:(id)arg3;

@end

