//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DevToolsCore/XCDependencyCommand.h>

@class NSArray, XCDependencyNode;

@interface XCAssetPackManifestInfoPlistCreationCommand : XCDependencyCommand
{
    XCDependencyNode *_assetPackManifestNode;
    NSArray *_assetPackInfoDicts;
}

@property(copy) NSArray *assetPackInfoDicts; // @synthesize assetPackInfoDicts=_assetPackInfoDicts;
@property(retain) XCDependencyNode *assetPackManifestNode; // @synthesize assetPackManifestNode=_assetPackManifestNode;
- (void).cxx_destruct;
- (BOOL)shouldUniqueOnOutputFiles;
- (id)workingDirectoryNode;
- (id)environmentAssignments;
- (id)commandLineArguments;
- (id)descriptionForWorkQueueLog;
- (id)executionDescription;
- (id)detailedExecutionDescription;
- (id)messageFormatForFailingCommandWithNoErrors;
- (CDUnknownBlockType)processDependencyInfoFileIfNecessaryWithCommandInvocationSucceeded:(BOOL)arg1;
- (id)instantiatedCommandResultsPostprocessor;
- (id)createStartedCommandInvocationWithParameters:(id)arg1;
- (BOOL)needsToRun;

@end

