//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DevToolsCore/XCBuildProductStructureElementCreator.h>

@class NSString;

@interface XCBuildProductStructureElementCreator_Directory : XCBuildProductStructureElementCreator
{
    NSString *_path;
    NSString *_commandStringRepresentation;
}

- (void).cxx_destruct;
- (BOOL)createElementIfNecessaryWithBuildLogRecorderBlock:(CDUnknownBlockType)arg1;
- (id)commandStringRepresentation;
- (id)initWithDirectoryAtPath:(id)arg1;

@end

