//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface XCPropertyMacroExpression : NSObject
{
}

+ (id)propertyMacroExpressionFromString:(id)arg1 error:(id *)arg2;
- (id)description;
- (BOOL)evaluateAsBooleanWithMacroExpansionScope:(id)arg1;
- (id)evaluateWithMacroExpansionScope:(id)arg1;

@end

