//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DevToolsCore/PBXFrameworkProductType.h>

@interface XCStaticFrameworkProductType : PBXFrameworkProductType
{
}

- (id)createUniversalBinaryFromThinBinaries:(id)arg1 withMacroExpansionScope:(id)arg2;

@end

