//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTPlatform, NSString;

@interface XCTargetSnapshot : NSObject
{
    NSString *_name;
    NSString *_projectName;
    NSString *_projectPath;
    NSString *_productType;
    DVTPlatform *_platform;
}

- (void).cxx_destruct;
@property(readonly) DVTPlatform *platform; // @synthesize platform=_platform;
@property(readonly) NSString *productType; // @synthesize productType=_productType;
@property(readonly) NSString *projectPath; // @synthesize projectPath=_projectPath;
@property(readonly) NSString *projectName; // @synthesize projectName=_projectName;
@property(readonly) NSString *name; // @synthesize name=_name;
@property(readonly) BOOL productIsApp;
- (id)initWithInformationFromTarget:(id)arg1;

@end

