//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DevToolsCore/XCWorkQueueCommandBuiltinInvocation.h>

@interface XCWorkQueueCommandBuiltinInvocation_infoPlistUtility : XCWorkQueueCommandBuiltinInvocation
{
}

- (id)mergeUIRequiredDeviceCapabilitiesValue:(id)arg1 fromFileAtPath:(id)arg2 intoOldValue:(id)arg3 fromFileAtPath:(id)arg4;
- (id)propertyListForFileAtPath:(id)arg1 returningInputPlistFormat:(unsigned long long *)arg2 returningExitCode:(int *)arg3;
- (int)runTaskWithArguments:(id)arg1 environment:(id)arg2 workingDirectoryPath:(id)arg3 infd:(int)arg4 outerrfd:(int)arg5;

@end

