//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Localization/LOCProperty.h>

@class NSDictionary, NSMutableDictionary, NSString;

@interface LOCPropertyStringsdictFile : LOCProperty
{
    NSDictionary *_stringsdict;
    NSDictionary *_complementedStringsdict;
    NSDictionary *_configDictionary;
    NSString *_locale;
    NSString *_transformationLocale;
    NSMutableDictionary *_referenceToAnotherFormatDictionary;
    NSMutableDictionary *_stringsKeyForReferencedDictionary;
}

+ (id)defaultConfigFilePath;
+ (id)transUnitIDForPluralRuleWithStringKey:(id)arg1 variableName:(id)arg2 pluralKey:(id)arg3;
+ (id)transUnitIDForPluralRuleNSStringLocalizedFormatKeyWithStringKey:(id)arg1;
+ (id)transUnitIDForDeviceSpecificRuleWithStringKey:(id)arg1 deviceKey:(id)arg2;
+ (id)transUnitIDForSizeRuleWithStringKey:(id)arg1 sizeKey:(id)arg2;
@property(retain) NSMutableDictionary *stringsKeyForReferencedDictionary; // @synthesize stringsKeyForReferencedDictionary=_stringsKeyForReferencedDictionary;
@property(retain) NSMutableDictionary *referenceToAnotherFormatDictionary; // @synthesize referenceToAnotherFormatDictionary=_referenceToAnotherFormatDictionary;
@property(retain) NSString *transformationLocale; // @synthesize transformationLocale=_transformationLocale;
@property(retain) NSString *locale; // @synthesize locale=_locale;
@property(retain) NSDictionary *configDictionary; // @synthesize configDictionary=_configDictionary;
@property(retain) NSDictionary *complementedStringsdict; // @synthesize complementedStringsdict=_complementedStringsdict;
@property(retain) NSDictionary *stringsdict; // @synthesize stringsdict=_stringsdict;
- (void).cxx_destruct;
- (id)allLocalizablePluralRulePropertyArray;
- (id)createInternalGlossaryWithOptions:(unsigned long long)arg1 relativeTo:(id)arg2 error:(id *)arg3;
- (id)createInternalGlossaryWithOptions:(unsigned long long)arg1 error:(id *)arg2;
- (id)createInternalGlossaryRelativeTo:(id)arg1 withError:(id *)arg2;
- (id)createInternalGlossaryWithError:(id *)arg1;
- (id)updateStringsdict:(id)arg1 withOverrideKeys:(id)arg2 fromGlossary:(id)arg3 error:(id *)arg4;
- (BOOL)addZeroCasesToMatchTranslations:(id)arg1 translationsFromTargetFile:(BOOL)arg2 error:(id *)arg3;
- (BOOL)adjustWidthsToMatchTranslations:(id)arg1 translationsFromTargetFile:(BOOL)arg2 error:(id *)arg3;
- (id)complementedPluralRuleProperties;
- (BOOL)writeTo:(id)arg1 withTranslation:(id)arg2 options:(unsigned long long)arg3 error:(id *)arg4;
- (id)localizedStrings;
- (id)localizedStringsWithMetaInfo:(id)arg1 valueTypeInfo:(id)arg2;
- (id)complementedStringsdictWith:(id)arg1;
- (id)initWithTransUnits:(id)arg1 fromInternalGlossary:(id)arg2 asIfAtPath:(id)arg3 configFile:(id)arg4 error:(id *)arg5;
- (id)initWithContentsOfFile:(id)arg1 configFile:(id)arg2 locale:(id)arg3 transformationLocale:(id)arg4 error:(id *)arg5;

// Remaining properties
@property(retain) NSString *filePath;

@end

