//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DebuggerUI/NSObject-Protocol.h>

@class DBGBacktraceInspectorFrameViewController, IDEStackFrame;

@protocol DBGBacktraceInspectorFrameViewControllerDelegate <NSObject>
- (void)frameViewController:(DBGBacktraceInspectorFrameViewController *)arg1 displaySourceForStackFrame:(IDEStackFrame *)arg2;
@end

