//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DebuggerUI/DBGSceneViewControllerDataSourceProtocol-Protocol.h>

@class DBGViewDebuggerAdditionUIController, DBGViewInstance, NSMutableDictionary;

@interface DBGSceneViewControllerDataSource : NSObject <DBGSceneViewControllerDataSourceProtocol>
{
    DBGViewDebuggerAdditionUIController *_debuggerUIController;
    NSMutableDictionary *_renderablesDictionary;
    DBGViewInstance *_rootView;
    unsigned long long _globalRenderingOrderCounter;
}

- (void).cxx_destruct;
@property unsigned long long globalRenderingOrderCounter; // @synthesize globalRenderingOrderCounter=_globalRenderingOrderCounter;
@property(retain) DBGViewInstance *rootView; // @synthesize rootView=_rootView;
@property(retain) NSMutableDictionary *renderablesDictionary; // @synthesize renderablesDictionary=_renderablesDictionary;
@property(retain) DBGViewDebuggerAdditionUIController *debuggerUIController; // @synthesize debuggerUIController=_debuggerUIController;
- (id)allRenderables;
- (id)viewInstanceWithIdentifier:(id)arg1;
- (id)renderableWithIdentifier:(id)arg1;
- (id)rootViewForHierarchyToDisplay;
- (void)updateViewRenderingOrderWithRootViewInstance:(id)arg1;
- (void)updateChildInstancesForInstance:(id)arg1;
- (void)prepareDataWithRootViewSurface:(id)arg1 debuggerUIController:(id)arg2;

@end

