//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DBGViewDebuggerAdditionUIController, DBGViewInstance, DBGViewSurface, NSArray, NSString;
@protocol DBGCanvasRenderable;

@protocol DBGSceneViewControllerDataSourceProtocol
- (NSArray *)allRenderables;
- (DBGViewInstance *)viewInstanceWithIdentifier:(NSString *)arg1;
- (id <DBGCanvasRenderable>)renderableWithIdentifier:(NSString *)arg1;
- (DBGViewInstance *)rootViewForHierarchyToDisplay;
- (void)prepareDataWithRootViewSurface:(DBGViewSurface *)arg1 debuggerUIController:(DBGViewDebuggerAdditionUIController *)arg2;
@end

