//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEInspectorProperty.h>

@class IDEInspectorKeyPath, NSDictionary, NSString, NSTextField;

@interface DBGStaticEnumerationInspectorProperty : IDEInspectorProperty
{
    IDEInspectorKeyPath *_valueKeyPath;
    NSString *_staticText;
    NSDictionary *_titleByValue;
    BOOL _hasBitMask;
    NSTextField *_textField;
    long long _bitMask;
}

- (void).cxx_destruct;
@property long long bitMask; // @synthesize bitMask=_bitMask;
@property BOOL hasBitMask; // @synthesize hasBitMask=_hasBitMask;
@property __weak NSTextField *textField; // @synthesize textField=_textField;
- (void)_configureEnumeratedOptions;
- (void)_extractOptionGroupsFromElement:(id)arg1 intoDictionary:(id)arg2;
- (void)_extractOptionsFromElement:(id)arg1 intoDictionary:(id)arg2;
- (void)setupRefreshTriggersAndConfigure;
- (double)baseline;
- (void)refresh;

@end

