//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DebuggerUI/DBGViewSurfaceHierarchyItem.h>

@class DBGViewLayer;

@interface DBGViewLayerHierarchyItem : DBGViewSurfaceHierarchyItem
{
}

- (BOOL)supportsCALayerInspectorProperties;
@property(readonly) DBGViewLayer *proxiedLayer;

@end

