//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DebuggerUI/DBGViewDebuggerAssetQuery-Protocol.h>

@class NSSet, NSString;

@interface DBGVisualRepresentationQuery : NSObject <DBGViewDebuggerAssetQuery>
{
    unsigned long long _type;
    NSSet *_affectedIdentifiers;
}

+ (id)queryExcludingChildrenWithIdentifier:(id)arg1;
+ (id)queryIncludingChildrenWithIdentifier:(id)arg1;
+ (id)queryExcludingChildren;
+ (id)queryIncludingChildren;
- (void).cxx_destruct;
@property(readonly) NSSet *affectedIdentifiers; // @synthesize affectedIdentifiers=_affectedIdentifiers;
@property(readonly) unsigned long long type; // @synthesize type=_type;
@property(readonly) NSString *assetQueryIdentifier;
- (id)initWithType:(unsigned long long)arg1 affectedIdentifiers:(id)arg2;

@end

