//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEBreakpointBucket.h>

@class NSImage;

@interface IDEBreakpointBucket (IDEBreakpointNavigatorSupport)
+ (id)keyPathsForValuesAffectingDisplayImage;
@property(readonly) NSImage *displayImage;
@end

