//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTTextDocumentLocation, IDEBreakpointActionRowView;

@protocol IDEBreakpointActionRowDelegate
@property(retain) DVTTextDocumentLocation *breakpointLocation;
- (void)removeRowRequestedByRow:(IDEBreakpointActionRowView *)arg1;
- (void)addRowRequestedByRow:(IDEBreakpointActionRowView *)arg1;
@end

