//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTPopoverContentViewController.h>

#import <DebuggerUI/IDEAppearanceDelegationViewDelegate-Protocol.h>

@class NSStackView, NSView;
@protocol DBGKitDebuggingAddition;

@interface IDEDebugOverridesPopoverContentViewController : DVTPopoverContentViewController <IDEAppearanceDelegationViewDelegate>
{
    NSView *_contentContainerView;
    NSStackView *_categoriesStackView;
    id <DBGKitDebuggingAddition> _kitDebuggingAddition;
}

@property(retain) id <DBGKitDebuggingAddition> kitDebuggingAddition; // @synthesize kitDebuggingAddition=_kitDebuggingAddition;
@property __weak NSStackView *categoriesStackView; // @synthesize categoriesStackView=_categoriesStackView;
@property __weak NSView *contentContainerView; // @synthesize contentContainerView=_contentContainerView;
- (void).cxx_destruct;
- (void)appearanceDelegationViewDidUpdateEffectiveAppearance:(id)arg1;
- (void)primitiveInvalidate;
- (void)_didChangeAppearance;
- (void)_setupAppearanceDelegation;
- (id)debugOverrides;
- (id)_viewControllerForCategoryWithOverrides:(id)arg1;
- (void)_addViewForCategoryWithOverrides:(id)arg1;
- (void)_setupOverridesUI;
- (void)viewDidLoad;
- (id)initWithKitDebuggingAddition:(id)arg1;

@end

