//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class IDEExceptionBreakpoint;

@interface IDEExceptionBreakpointEditorView : NSViewController
{
    IDEExceptionBreakpoint *_breakpoint;
}

+ (id)keyPathsForValuesAffectingExceptionNameHidden;
- (void).cxx_destruct;
@property(retain) IDEExceptionBreakpoint *breakpoint; // @synthesize breakpoint=_breakpoint;
@property(readonly) BOOL exceptionNameHidden;
- (void)loadView;
- (id)initWithBreakpoint:(id)arg1;

@end

