//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class DVTBorderedView, IDEAnalyticsPointLogViewController, MISSING_TYPE, NSOutlineView, NSTextField, _TtC12DVTAnalytics17ProcessorUsageLog, _TtC12DVTAnalytics19ProcessorUsagePoint, _TtC13IDEProductsUI22SynchronizedScrollView;

@interface _TtC13IDEProductsUI31ProcessorUsageLogViewController : IDEViewController
{
    MISSING_TYPE *processorUsagePoint;
    MISSING_TYPE *analyticsPointLogViewController;
    MISSING_TYPE *logAspect;
    MISSING_TYPE *outlineView;
    MISSING_TYPE *scrollView;
    MISSING_TYPE *floatingColumnsScrollView;
    MISSING_TYPE *floatingColumnsOutlineView;
    MISSING_TYPE *borderedView;
    MISSING_TYPE *emptyContentTitle;
    MISSING_TYPE *emptyContentSubtitle;
    MISSING_TYPE *jumpToArrowWidth;
    MISSING_TYPE *restoringOutlineViewCollapsedItems;
    MISSING_TYPE *collapsedItemStateRestorationCache;
    MISSING_TYPE *scrollPositionStateRestorationCache;
    MISSING_TYPE *mouseInsideTreeNodeStackFrame;
    MISSING_TYPE *processorUsageLog;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, retain) _TtC12DVTAnalytics17ProcessorUsageLog *processorUsageLog; // @synthesize processorUsageLog;
- (void)showAnalyticsLogInFinder:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)viewWillDisappear;
- (void)viewDidLoad;
@property(nonatomic) __weak NSTextField *emptyContentSubtitle; // @synthesize emptyContentSubtitle;
@property(nonatomic) __weak NSTextField *emptyContentTitle; // @synthesize emptyContentTitle;
@property(nonatomic) __weak DVTBorderedView *borderedView; // @synthesize borderedView;
@property(nonatomic) __weak NSOutlineView *floatingColumnsOutlineView; // @synthesize floatingColumnsOutlineView;
@property(nonatomic) __weak _TtC13IDEProductsUI22SynchronizedScrollView *floatingColumnsScrollView; // @synthesize floatingColumnsScrollView;
@property(nonatomic) __weak _TtC13IDEProductsUI22SynchronizedScrollView *scrollView; // @synthesize scrollView;
@property(nonatomic) __weak NSOutlineView *outlineView; // @synthesize outlineView;
@property(nonatomic) __weak IDEAnalyticsPointLogViewController *analyticsPointLogViewController; // @synthesize analyticsPointLogViewController;
@property(nonatomic, retain) _TtC12DVTAnalytics19ProcessorUsagePoint *processorUsagePoint; // @synthesize processorUsagePoint;

@end

