//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEProductsUI/_TtC13IDEProductsUI31ProcessorUsageLogViewController.h>

@interface _TtC13IDEProductsUI31ProcessorUsageLogViewController (IDEProductsUI3)
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
@end

