//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

#import <IDEProductsUI/DVTReplacementViewDelegate-Protocol.h>
#import <IDEProductsUI/IDEProductManagerDelegate-Protocol.h>
#import <IDEProductsUI/IDEProductSectionProgressProvider-Protocol.h>
#import <IDEProductsUI/IDEProductsWindowToolbarItemProvider-Protocol.h>
#import <IDEProductsUI/NSTableViewDelegate-Protocol.h>
#import <IDEProductsUI/_TtP11IDEProducts24ProductSelectionDelegate_-Protocol.h>

@class DVTNotificationToken, DVTObservingToken, DVTStackBacktrace, IDEProductManager, IDEProductSectionViewController, IDEProductsUtilityViewController, IDEProductsViewSplitViewController, NSArray, NSMutableDictionary, NSString, _TtC11IDEProducts16ProductSelection, _TtC13IDEProductsUI23ProductSectionSelection, _TtC13IDEProductsUI35ProductSectionContentViewController, _TtC13IDEProductsUI38ProductSectionSourceListViewController;
@protocol DVTInvalidation, IDEProductSectionViewControllerDelegate, IDEProductsWindowToolbarManagerProtocol;

@interface IDEProductsViewController : IDEViewController <_TtP11IDEProducts24ProductSelectionDelegate_, IDEProductManagerDelegate, NSTableViewDelegate, DVTReplacementViewDelegate, IDEProductSectionProgressProvider, IDEProductsWindowToolbarItemProvider>
{
    BOOL _programmaticallyManipulatingProductsSourceListSplitPosition;
    BOOL _displayedLogInErrors;
    BOOL _hasCompletedInitialLoading;
    id <IDEProductsWindowToolbarManagerProtocol> toolbarManager;
    _TtC11IDEProducts16ProductSelection *_productSelection;
    IDEProductSectionViewController *_currentSectionViewController;
    IDEProductsViewSplitViewController *_splitViewController;
    _TtC13IDEProductsUI35ProductSectionContentViewController *_contentViewController;
    _TtC13IDEProductsUI23ProductSectionSelection *_productSectionSelection;
    _TtC13IDEProductsUI38ProductSectionSourceListViewController *_productSectionSourceListViewController;
    id <DVTInvalidation> _productSectionSelectionSubscription;
    id <IDEProductSectionViewControllerDelegate> _delegate;
    IDEProductsUtilityViewController *_utilityViewController;
    NSMutableDictionary *_sourcesToErrorsMap;
    CDUnknownBlockType _showProductAfterInitialLoading;
    DVTObservingToken *_inspectableObserver;
    DVTObservingToken *_busyObserver;
    DVTNotificationToken *_splitViewResizeObserver;
    DVTObservingToken *_currentSectionViewControllerObserver;
    DVTObservingToken *_isBusyObserver;
    DVTObservingToken *_busyReasonObserver;
}

+ (id)keyPathsForValuesAffectingBusyReason;
+ (id)keyPathsForValuesAffectingIsBusy;
+ (void)initialize;
- (void).cxx_destruct;
@property(retain) DVTObservingToken *busyReasonObserver; // @synthesize busyReasonObserver=_busyReasonObserver;
@property(retain) DVTObservingToken *isBusyObserver; // @synthesize isBusyObserver=_isBusyObserver;
@property(retain) DVTObservingToken *currentSectionViewControllerObserver; // @synthesize currentSectionViewControllerObserver=_currentSectionViewControllerObserver;
@property(retain) DVTNotificationToken *splitViewResizeObserver; // @synthesize splitViewResizeObserver=_splitViewResizeObserver;
@property(retain) DVTObservingToken *busyObserver; // @synthesize busyObserver=_busyObserver;
@property(retain) DVTObservingToken *inspectableObserver; // @synthesize inspectableObserver=_inspectableObserver;
@property(copy, nonatomic) CDUnknownBlockType showProductAfterInitialLoading; // @synthesize showProductAfterInitialLoading=_showProductAfterInitialLoading;
@property(nonatomic) BOOL hasCompletedInitialLoading; // @synthesize hasCompletedInitialLoading=_hasCompletedInitialLoading;
@property(nonatomic, getter=hasDisplayedLogInErrors) BOOL displayedLogInErrors; // @synthesize displayedLogInErrors=_displayedLogInErrors;
@property(nonatomic, getter=isProgrammaticallyManipulatingProductsSourceListSplitPosition) BOOL programmaticallyManipulatingProductsSourceListSplitPosition; // @synthesize programmaticallyManipulatingProductsSourceListSplitPosition=_programmaticallyManipulatingProductsSourceListSplitPosition;
@property(retain) NSMutableDictionary *sourcesToErrorsMap; // @synthesize sourcesToErrorsMap=_sourcesToErrorsMap;
@property(retain) IDEProductsUtilityViewController *utilityViewController; // @synthesize utilityViewController=_utilityViewController;
@property(retain, nonatomic) id <IDEProductSectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <DVTInvalidation> productSectionSelectionSubscription; // @synthesize productSectionSelectionSubscription=_productSectionSelectionSubscription;
@property(retain, nonatomic) _TtC13IDEProductsUI38ProductSectionSourceListViewController *productSectionSourceListViewController; // @synthesize productSectionSourceListViewController=_productSectionSourceListViewController;
@property(retain, nonatomic) _TtC13IDEProductsUI23ProductSectionSelection *productSectionSelection; // @synthesize productSectionSelection=_productSectionSelection;
@property(retain) _TtC13IDEProductsUI35ProductSectionContentViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(retain) IDEProductsViewSplitViewController *splitViewController; // @synthesize splitViewController=_splitViewController;
@property(retain) IDEProductSectionViewController *currentSectionViewController; // @synthesize currentSectionViewController=_currentSectionViewController;
@property(retain, nonatomic) _TtC11IDEProducts16ProductSelection *productSelection; // @synthesize productSelection=_productSelection;
@property __weak id <IDEProductsWindowToolbarManagerProtocol> toolbarManager; // @synthesize toolbarManager;
@property(readonly) NSArray *toolbarItems;
- (void)replacementView:(id)arg1 willInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (void)productManager:(id)arg1 receivedErrors:(id)arg2 fromSource:(id)arg3;
- (void)splitViewDidResizeSubviewsNotification:(id)arg1;
- (void)primitiveInvalidate;
- (void)didCompleteInitialLoading;
- (void)didSetWithSelected:(id)arg1;
- (void)_saveSourceListSplitPosition;
- (void)_restoreSourceListSplitPosition;
- (void)refresh;
@property(readonly) NSString *busyReason;
@property(readonly) BOOL isBusy;
- (void)_resumeSplitPositions;
- (void)_resetDefaultUtilitiesSplitPosition;
- (id)errorsFromProductSource:(id)arg1;
- (void)toggleUtilitiesVisibility;
- (BOOL)shouldShowUtilities;
- (void)showProductsSectionWithIdentifier:(id)arg1 forProductIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly) IDEProductManager *productManager;
- (void)viewWillAppear;
- (void)setUpSplitViewResizeObserver;
- (void)setUpInspectableObserver;
- (void)setUpCurrentSectionObservation;
- (void)setUpProductSectionSelectionSubscription;
- (void)updateProductSectionClass;
- (void)updateWindowTitle;
- (void)setUpIsBusyObservation;
- (void)setUpUtilityPane;
- (void)setUpContentView;
- (void)setUpSourceList;
- (void)setUpSplitView;
- (void)viewDidLoad;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

