//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s12SourceEditor0aB4ViewCN.h"

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC8DeltaKit25DiffDrawableAuxiliaryView : _$s12SourceEditor0aB4ViewCN
{
    MISSING_TYPE *parentSourceEditorView;
    MISSING_TYPE *hunkLayer;
    MISSING_TYPE *fineGrainCache;
    MISSING_TYPE *lastSizedHash;
    MISSING_TYPE *themeObserver;
    MISSING_TYPE *auxIdentifier;
    MISSING_TYPE *lineIdentifier;
    MISSING_TYPE *diffDescriptor;
    MISSING_TYPE *diffDescriptorIndex;
    MISSING_TYPE *dirty;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)setFrameOrigin:(struct CGPoint)arg1;
- (void)redo:(id)arg1;
- (void)undo:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)dealloc;

@end

