//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MISSING_TYPE;

@interface _TtC8DeltaKit32ComparisonSourceEditorController : NSViewController
{
    MISSING_TYPE *editor;
    MISSING_TYPE *session;
    MISSING_TYPE *$__lazy_storage_$_changeBar;
    MISSING_TYPE *$__lazy_storage_$_inlineDiff;
    MISSING_TYPE *controller;
    MISSING_TYPE *url;
    MISSING_TYPE *foldedRanges;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)sessionDidScrapeDiffResults:(id)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

