//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@interface _TtC8DeltaKitP33_C119A59A2C75F63D429631B0F8F67D5C28MinimapChangeBarContentLayer : CALayer
{
}

+ (id)defaultActionForKey:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithLayer:(id)arg1;
- (id)init;

@end

