//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s15DVTSourceEditor0aB4ViewCN.h"

@class MISSING_TYPE;

@interface _TtC8DeltaKit26ComparisonSourceEditorView : _$s15DVTSourceEditor0aB4ViewCN
{
    MISSING_TYPE *controller;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

